(include "ir_types.lisp")

;; Native portable SSA. Value IDs and block IDs are one-based arena indices.
;; Every value has one definition. Kind 28 is a two-edge PHI; other operation
;; numbers retain the native HIR's scalar meanings without its tree structure.

(defcstruct native_ssa_value
  (kind u32)
  (scalar_code u32)
  (pointee usize)
  (value u64)
  (left usize)
  (right usize)
  (target usize)
  (source usize)
  (block usize)
  (next usize)
  (predecessor_left usize)
  (predecessor_right usize))

(defcstruct native_ssa_block
  (first usize)
  (last usize)
  (terminator u32)
  (condition usize)
  (target_left usize)
  (target_right usize)
  (result usize)
  (visit u8))

(defcstruct native_ssa_arena
  (values (ptr native_ssa_value))
  (types (ptr native_ir_type))
  (value_count usize)
  (value_capacity usize)
  (blocks (ptr native_ssa_block))
  (block_count usize)
  (block_capacity usize)
  (current usize)
  (error u32))

(defun ssa_value_at (arena reference)
  (declare (type (ptr native_ssa_arena) arena)
           (type usize reference) (returns (ptr native_ssa_value)))
  (pointer+ (deref (field-pointer arena 'values))
            (wrap-cast isize (wrap- reference 1))))

(defun ssa_block_at (arena reference)
  (declare (type (ptr native_ssa_arena) arena)
           (type usize reference) (returns (ptr native_ssa_block)))
  (pointer+ (deref (field-pointer arena 'blocks))
            (wrap-cast isize (wrap- reference 1))))

(defun ssa_new_block (arena)
  (declare (type (ptr native_ssa_arena) arena) (returns usize))
  (let ((count (deref (field-pointer arena 'block_count))))
    (if (< count (deref (field-pointer arena 'block_capacity)))
        (let ((reference (wrap+ count 1)))
          (let ((block (ssa_block_at arena reference)))
            (store (field-pointer block 'first) 0)
            (store (field-pointer block 'last) 0)
            (store (field-pointer block 'terminator) 0)
            (store (field-pointer block 'condition) 0)
            (store (field-pointer block 'target_left) 0)
            (store (field-pointer block 'target_right) 0)
            (store (field-pointer block 'result) 0)
            (store (field-pointer block 'visit) 0)
            (store (field-pointer arena 'block_count) reference)
            reference))
        (progn (store (field-pointer arena 'error) 1) 0))))

(defun ssa_append_value (arena reference)
  (declare (type (ptr native_ssa_arena) arena)
           (type usize reference) (returns c-int))
  (let ((block (ssa_block_at arena (deref (field-pointer arena 'current)))))
    (let ((last (deref (field-pointer block 'last))))
      (if (= last 0)
          (store (field-pointer block 'first) reference)
          (store (field-pointer (ssa_value_at arena last) 'next) reference))
      (store (field-pointer block 'last) reference)
      1)))

(defun ssa_new_value (arena node left right)
  (declare (type (ptr native_ssa_arena) arena)
           (type (ptr native_hir_node) node)
           (type usize left right) (returns usize))
  (let ((count (deref (field-pointer arena 'value_count))))
    (if (< count (deref (field-pointer arena 'value_capacity)))
        (let ((reference (wrap+ count 1)))
          (let ((value (ssa_value_at arena reference)))
            (store (field-pointer value 'kind) (deref (field-pointer node 'kind)))
            (store (field-pointer value 'scalar_code) (deref (field-pointer node 'scalar_code)))
            (store (field-pointer value 'pointee) (deref (field-pointer node 'pointee)))
            (store (field-pointer value 'value) (deref (field-pointer node 'value)))
            (store (field-pointer value 'left) left)
            (store (field-pointer value 'right) right)
            (store (field-pointer value 'target) (deref (field-pointer node 'target)))
            (store (field-pointer value 'source) (deref (field-pointer node 'source)))
            (store (field-pointer value 'block) (deref (field-pointer arena 'current)))
            (store (field-pointer value 'next) 0)
            (store (field-pointer value 'predecessor_left) 0)
            (store (field-pointer value 'predecessor_right) 0)
            (ssa_record_type arena reference value)
            (store (field-pointer arena 'value_count) reference)
            (ssa_append_value arena reference)
            reference))
        (progn (store (field-pointer arena 'error) 1) 0))))

;; Terminators: 1 return, 2 jump, 3 branch. A block is terminated once.
(defun ssa_terminate (arena kind condition left right result)
  (declare (type (ptr native_ssa_arena) arena)
           (type u32 kind)
           (type usize condition left right result) (returns c-int))
  (let ((block (ssa_block_at arena (deref (field-pointer arena 'current)))))
    (if (= (deref (field-pointer block 'terminator)) 0)
        (progn
          (store (field-pointer block 'terminator) kind)
          (store (field-pointer block 'condition) condition)
          (store (field-pointer block 'target_left) left)
          (store (field-pointer block 'target_right) right)
          (store (field-pointer block 'result) result)
          1)
        (progn (store (field-pointer arena 'error) 1) 0))))

(defun ssa_record_type (arena reference value)
  (declare (type (ptr native_ssa_arena) arena)
           (type usize reference)
           (type (ptr native_ssa_value) value) (returns c-int))
  (let ((type (ir_type_at (deref (field-pointer arena 'types)) reference)))
    (store (field-pointer type 'kind) (deref (field-pointer value 'kind)))
    (store (field-pointer type 'scalar_code) (deref (field-pointer value 'scalar_code)))
    (store (field-pointer type 'pointee) (deref (field-pointer value 'pointee)))
    (store (field-pointer type 'left)
           (if (= (deref (field-pointer value 'kind)) 17)
               (deref (field-pointer value 'left)) (wrap-cast usize 0)))
    (store (field-pointer type 'right)
           (if (= (deref (field-pointer value 'kind)) 17)
               (deref (field-pointer value 'right)) (wrap-cast usize 0)))
    1))
