;; Layout declarations shared by compiler code and hosted driver storage.
(include "binary_types.lisp")
(include "frontend/parser_types.lisp")
(include "frontend/atoms_types.lisp")
(include "frontend/signatures_types.lisp")
(include "frontend/data_types.lisp")
(include "backend/common_types.lisp")
(include "backend/x86_calls_types.lisp")
(include "ir/hir_types.lisp")
(include "ir/ssa_types.lisp")
(include "ir/lir_types.lisp")

(defcstruct native_compile_context
  (parser (ptr psl_parser))
  (source (ptr u8))
  (integer (ptr psl_parsed_integer))
  (hir (ptr native_hir_arena))
  (code (ptr byte_buffer))
  (fixups (ptr native_fixup_arena))
  (functions (ptr native_function))
  (signatures (ptr native_signature_context))
  (prior_count usize)
  (current_arity usize)
  (current_signature (ptr native_signature))
  (expected_type u32)
  (active_binding usize)
  (local_count usize)
  (expected_pointee usize)
  (ssa (ptr native_ssa_arena))
  (bindings (ptr usize))
  (lir (ptr native_lir_arena))
  (labels (ptr usize))
  (jumps (ptr native_fixup_arena))
  (optimization u32)
  (fold_cursor usize)
  (fold_changed c-int)
  (effects_changed c-int)
  (inline_values (ptr native_ssa_value))
  (inline_count usize)
  (inline_capacity usize)
  (inline_cursor usize)
  (target u32)
  (backend_frame_size usize)
  (backend_outgoing_size usize)
  (backend_prologue_size usize)
  (data_imports (ptr native_data_import))
  (data_count usize)
  (data_capacity usize)
  (data_fixups (ptr native_fixup_arena)))
