;; These observations use SBCL package operations, independent of PSL tables.
(let* ((a (make-package "PSL.OPS.A" :use nil))
       (b (make-package "PSL.OPS.B" :use nil))
       (c (make-package "PSL.OPS.C" :use nil))
       (d (make-package "PSL.OPS.D" :use nil))
       (q (make-package "PSL.OPS.Q" :use nil))
       (ax (intern "X" a)) (bx (intern "X" b)))
  (flet ((rejects (thunk)
           (assert (handler-case (progn (funcall thunk) nil)
                     (package-error () t)))))
    (export ax a) (export bx b) (use-package a c)
    (let ((uses (package-use-list c)))
      (rejects (lambda () (use-package b c)))
      (assert (equal uses (package-use-list c)))
      (assert (eq ax (find-symbol "X" c))))
    (rejects (lambda () (import bx c)))
    (assert (eq ax (find-symbol "X" c)))
    (import ax d) (export ax d) (use-package d c) (import ax c)
    (assert (eq (symbol-package ax) a))
    (let ((ay (intern "Y" a)) (cy (intern "Y" c)))
      (rejects (lambda () (export ay a)))
      (assert (eq cy (find-symbol "Y" c)))
      (shadow "Y" c) (export ay a)
      (rejects (lambda () (use-package d b)))
      (use-package a q) (export ax q)
      (assert (eq (symbol-package ax) a))
      (shadow "X" c) (use-package b c)
      (rejects (lambda () (unintern ax c)))
      (assert (eq ax (find-symbol "X" c)))
      (let ((own (intern "OWN" d)) (foreign (intern "OWN" a)))
        (export own d) (shadowing-import foreign d)
        (assert (null (symbol-package own)))
        (assert (eq (symbol-package foreign) a))
        (assert (eq foreign (find-symbol "OWN" d)))
        (assert (eq (nth-value 1 (find-symbol "OWN" d)) :internal))
        (assert (unintern foreign d))
        (assert (eq (symbol-package foreign) a))
        (assert (null (unintern foreign d))))
      (shadow "Y" q)
      (let ((qy (find-symbol "Y" q)))
        (assert (not (eq qy ay))) (assert (eq (symbol-package qy) q))
        (assert (unintern qy q)) (assert (null (symbol-package qy)))
        (assert (eq (find-symbol "Y" q) ay)))))
  ;; Deleting users before used packages avoids irrelevant cleanup warnings.
  (mapc #'delete-package (list q c d b a)))
(format t "SBCL confirms the package transaction visibility and identity observations~%")

(let* ((p (make-package "PSL.OPS.HOME" :use nil))
       (q (make-package "PSL.OPS.USER" :use nil))
       (fresh (make-symbol "FRESH"))
       (shared (intern "SHARED-Z" p)))
  (import fresh p) (assert (eq (symbol-package fresh) p))
  (unintern fresh p) (assert (null (symbol-package fresh)))
  (shadowing-import fresh p) (assert (null (symbol-package fresh)))
  (import fresh p) (assert (eq (symbol-package fresh) p))
  (export shared p) (use-package p q)
  (unexport shared q) (assert (eq (find-symbol "SHARED-Z" q) shared))
  (unexport shared p) (assert (null (find-symbol "SHARED-Z" q)))
  (export shared p) (assert (eq (find-symbol "SHARED-Z" q) shared))
  (assert (unuse-package p q)) (assert (null (find-symbol "SHARED-Z" q)))
  (assert (unuse-package p q))
  (use-package p q) (assert (eq (find-symbol "SHARED-Z" q) shared))
  (shadowing-import shared q) (export shared q) (unexport shared q)
  (assert (eq (find-symbol "SHARED-Z" q) shared))
  (assert (eq (nth-value 1 (find-symbol "SHARED-Z" q)) :internal))
  (assert (handler-case (progn (use-package p :keyword) nil) (error () t)))
  (assert (handler-case (progn (use-package :keyword :keyword) nil) (error () t)))
  (delete-package q) (delete-package p))
(format t "SBCL confirms ownership adoption, unexport, unuse, and keyword use policy~%")

(let* ((fresh (make-symbol "PSL-OPS-FRESH-KEYWORD"))
       (p (make-package "PSL.OPS.KEYWORD-HOME" :use nil))
       (foreign (intern "PSL-OPS-FOREIGN-KEYWORD" p)))
  (import fresh :keyword) (import foreign :keyword)
  (assert (eq (symbol-package fresh) (find-package :keyword)))
  (assert (eq (symbol-package foreign) p))
  (assert (eq (nth-value 1 (find-symbol (symbol-name fresh) :keyword)) :internal))
  (assert (eq (nth-value 1 (find-symbol (symbol-name foreign) :keyword)) :internal))
  (assert (eq fresh (read-from-string ":PSL-OPS-FRESH-KEYWORD")))
  (assert (eq fresh (read-from-string "keyword:PSL-OPS-FRESH-KEYWORD")))
  (assert (eq foreign (read-from-string "keyword:PSL-OPS-FOREIGN-KEYWORD")))
  (let ((new (read-from-string "keyword:PSL-OPS-NEW-KEYWORD")))
    (assert (eq (symbol-package new) (find-package :keyword)))
    (assert (eq (nth-value 1 (find-symbol (symbol-name new) :keyword)) :external))
    (unintern new :keyword))
  (unintern fresh :keyword) (unintern foreign :keyword) (delete-package p))
(format t "SBCL confirms qualified keyword interning and imported keyword identity~%")
