(load "src/load.lisp")
;; Query the build host's real packages after ordered PSL source reading.
;; These assertions concern symbol identity and public package observations.
(dotimes (iteration 2)
  (declare (ignore iteration))
  (multiple-value-bind (forms unit locations packages)
      (psl.frontend:read-source "tests/bootstrap_package_forms.lisp")
    (declare (ignore locations))
    (unwind-protect
         (let* ((base (find-package "PSL.SOURCE.BASE"))
                (middle (find-package "mixed.source"))
                (leaf (find-package "PSL.SOURCE.LEAF"))
                (helper (find-symbol "PACKAGE_HELPER" base)))
           (assert (= (length forms) 5))
           (assert (= (length packages) 5))
           (assert (member unit packages))
           (assert (eq base (find-package "PSL-SOURCE-B")))
           (assert (eq base (find-package "PSL-SOURCE-C")))
           (assert (not (eq (find-symbol "IF" "PSL.SOURCE.DEFAULT") 'cl:if)))
           (assert (null (package-use-list "PSL.SOURCE.DEFAULT")))
           (assert (eq (symbol-package helper) base))
           (assert (eq helper (find-symbol "PACKAGE_HELPER" middle)))
           (assert (eq helper (find-symbol "PACKAGE_HELPER" leaf)))
           (assert (eq (find-symbol "U64" :psl) (find-symbol "U64" leaf)))
           (multiple-value-bind (symbol status) (find-symbol "PRIVATE" leaf)
             (assert (eq (symbol-package symbol) leaf))
             (assert (eq status :internal)))
           (assert (not (eq (find-symbol "IF" middle) 'cl:if)))
           (assert (member (find-symbol "IF" middle) (package-shadowing-symbols middle)))
           (assert (eq (symbol-package (second (fourth forms))) leaf)))
      (psl.frontend:dispose-source-packages packages)))
  (assert (null (find-package "PSL.SOURCE.BASE")))
  (assert (null (find-package "mixed.source")))
  (assert (null (find-package "PSL.SOURCE.LEAF")))
  (assert (null (find-package "PSL.SOURCE.DEFAULT"))))
;; A reader failure after successful definitions also disposes the environment.
(dolist (path '("tests/bootstrap_package_form_errors/internal-symbol.lisp"
                "tests/bootstrap_package_form_errors/case-sensitive-package.lisp"
                "tests/bootstrap_package_form_errors/missing-import.lisp"))
  (assert (handler-case
              (progn (psl.frontend:read-source path) nil)
            (error () t))))
(assert (null (find-package "PSL.SOURCE.HIDDEN")))
(assert (null (find-package "psl.source.lower")))
(assert (null (find-package "PSL.SOURCE.FAILURE")))
;; The reusable compiler API must dispose packages too, including repeated runs.
(dotimes (iteration 2)
  (declare (ignore iteration))
  (let ((unit (psl.compiler:read-unit "tests/bootstrap_package_forms.lisp")))
    (psl.compiler:dispose-unit unit)
    (psl.compiler:dispose-unit unit))
  (assert (null (find-package "PSL.SOURCE.BASE"))))
(format t "SBCL confirms ordered source package identities and environment cleanup~%")
