(defmacro declaration_passthrough (value unused)
  (declare (ignore unused)) value)
(defmacro declaration_documented (value unused)
  (declare (ignore unused)) "Macro documentation." (declare (ignorable value))
  0 value)
(defmacro declaration_defaults (value &optional (extra 3) &aux (copy extra))
  "Documented default bindings." (declare (ignorable extra copy))
  `(wrap+ ,value ,copy))
(defmacro declaration_empty (unused) (declare (ignore unused)))
(defmacro declaration_unknown (value)
  (declare (ignore absent)) (declare (ignorable nil t :keyword)) value)
(defmacro declaration_no_variables (value) (declare) (declare (ignore) (ignorable)) value)
(defmacro declaration_escaped (value unused) (CL:|DECLARE| (CL:|IGNORE| unused)) value)
(defun declarations_answer (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (wrap+ (declaration_passthrough value (unresolved_call))
    (wrap+ (declaration_documented value (unresolved_call))
      (wrap+ (declaration_defaults value)
        (wrap+ (declaration_unknown value)
          (wrap+ (declaration_no_variables value) (declaration_escaped value (unresolved_call))))))))
(defun declarations_nil ()
  (declare (returns u64) (c-export :c))
  (if (declaration_empty (unresolved_call)) 1 42))
