(defmacro add_default (value &optional (extra 3 supplied) (again extra))
  `(wrap+ (if ,supplied ,extra ,again) ,value))
(defmacro no_default (&optional value) `(if ,value 1 42))
(defmacro add_body (value &optional (extra value) &rest body) `(progn ,@body (wrap+ ,value ,extra)))
(defun optional_answer (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (wrap+ (add_default value) (add_default value 7)))
(defun optional_empty ()
  (declare (returns u64) (c-export :c))
  (no_default))
(defun optional_rest (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (add_body value 9 0 1))
(defmacro default_empty (&optional (value ())) `(if ,value 1 42))
(defmacro empty_result () '())
(defmacro explicit_quote () (quote 42))
(defun optional_nil ()
  (declare (returns u64) (c-export :c))
  (wrap+ (default_empty) (if (empty_result) 1 (explicit_quote))))
(defun reader_empty_nil ()
  (declare (returns u64) (c-export :c))
  (if () 1 42))

(defmacro lazy_default (value &optional (extra unknown_default)) value)
(defmacro single_spec (&optional (value)) value)
(defun optional_lazy (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (lazy_default value 0))
(defun optional_one_spec (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (single_spec value))
