(defpackage "PSL.SOURCE.BASE"
  (:export "PACKAGE_HELPER")
  (:intern "HIDDEN")
  (:nicknames #:psl-source-b)
  (:use #:cl)
  (:use #:cl)
  (:nicknames #:psl-source-c)
  (:import-from #:psl #:u64 #:returns #:wrap+))
(in-package #:psl-source-b)
(defun package_helper (value)
  (declare (type u64 value) (returns u64))
  (wrap+ value 2))

(cl:defpackage "mixed.source"
  (:export #:package_value)
  (:shadowing-import-from #:cl #:cons)
  (:shadow #:if)
  (:use #:cl #:psl-source-b)
  (:import-from #:psl #:u64 #:returns #:wrap+ #:c-export))
(cl:in-package "mixed.source")
(defun package_value (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (cl:if 0 (wrap+ (psl-source-b:package_helper value) 9) 999))
(psl:include "source_packages/body.lisp")
;; An included file changes the current package for subsequent source forms.
(cl:defun package_after_include (value)
  (cl:declare (cl:type psl:u64 value) (psl:returns psl:u64) (psl:c-export :c))
  (psl:wrap+ (package_include value) 5))

(cl:defpackage "PSL.SOURCE.DEFAULT" (:export #:if))
(cl:in-package #:psl.source.default)
(cl:defun package_default (value)
  (cl:declare (cl:type psl:u64 value) (psl:returns psl:u64) (psl:c-export :c))
  (cl:if 0 (psl:wrap+ (|mixed.source|:package_value value) 1) 999))
