(load "src/package.lisp")
(with-open-file (stream (second sb-ext:*posix-argv*)
                        :direction :output :if-exists :supersede)
  (dolist (package '("COMMON-LISP" "PSL" "PSL.FFI"))
    (let ((names nil))
      (do-external-symbols (symbol (find-package package))
        (push (symbol-name symbol) names))
      (dolist (name (sort names #'string<))
        (format stream "~A~C~A~%" package #\Tab name)))))
