(defmacro twice (value) `(wrap+ ,value ,value))
(defmacro nested (value) `(twice (twice ,value)))
(defmacro identity_form (value) value)
(defmacro answer () '42)
(ffi:import-function "macro_tick" ((value u64)) -> u64)

(defun macro_nested (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (nested (identity_form value)))
(defun macro_effects (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (twice (ffi:call macro_tick value)))
(defun macro_bindings (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (let ((twice (twice value))) (wrap+ twice (answer))))
(defun macro_before (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (twice value))
(defmacro twice (value) `(wrap+ ,value 3))
(defun macro_after (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (twice value))
(defmacro choose (value) `(if 0 ,value 999))
(defun macro_truth (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (choose (wrap-cast u64 (choose value))))
(defpackage "PSL.MACRO.ORIGIN" (:use #:cl) (:export #:bump))
(in-package "PSL.MACRO.ORIGIN")
(defmacro bump (value) `(psl:wrap+ ,value 9))
(defpackage "PSL.MACRO.CALLER" (:use #:cl) (:import-from "PSL.MACRO.ORIGIN" #:bump))
(in-package "PSL.MACRO.CALLER")
(defun macro_imported (value)
  (declare (type psl:u64 value) (psl:returns psl:u64) (psl:c-export :c))
  (bump value))
