(defmacro aux_copy (value &aux (copy value) (again copy)) `(wrap+ ,copy ,again))
(defmacro aux_empty (&aux empty (again empty)) `(if ,again 1 42))
(defmacro aux_optional (value &optional (extra 3) &aux (copy extra)) `(wrap+ ,value ,copy))
(defmacro aux_body (value &rest body &aux (copy value) (again body)) `(progn ,@again ,copy))
(defmacro aux_single (&aux (value)) `(if ,value 1 42))
(defmacro aux_no_values (&aux) '42)
(defun aux_answer (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (wrap+ (aux_copy value) (wrap+ (aux_optional value) (aux_optional value 7))))
(defun aux_nil ()
  (declare (returns u64) (c-export :c))
  (wrap+ (aux_empty) (wrap+ (aux_single) (aux_no_values))))
(defun aux_rest (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (aux_body value 1 0))
