(defpackage :key_probe_private (:use) (:export :amount))
(defmacro keyed_defaults (value &key (extra 3 supplied) (copy extra) &aux (chosen (if supplied copy 5)))
  `(wrap+ ,value ,chosen))
(defmacro keyed_rest (value &rest body &key (extra 3))
  (declare (ignore body)) (list 'wrap+ value extra))
(defmacro keyed_explicit (&key ((key_probe_private:amount extra) 3 provided))
  (if provided extra 42))
(defmacro keyed_allow (&key extra &allow-other-keys) (if extra extra 42))
(defmacro keyed_invocation_allow (&key (extra 3)) extra)
(defmacro keyed_optional (value &optional (bias 2) &key (extra 3) &aux (chosen extra))
  `(wrap+ ,value (wrap+ ,bias ,chosen)))
(defmacro keyed_order (&key (left 3) (right left)) right)
(defmacro keyed_lazy (&key (extra missing_key_default)) extra)
(defmacro keyed_truth (&key (extra nil supplied)) (if supplied (if extra 11 12) 13))
(defmacro keyed_control_parameter (&key ((:allow-other-keys extra) 3)) extra)
(defun keys_defaults (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (wrap+ (keyed_defaults value)
    (wrap+ (keyed_defaults value :extra 7)
      (keyed_defaults value :extra 11 :extra 99))))
(defun keys_rest (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (wrap+ (keyed_rest value) (keyed_rest value :extra 7)))
(defun keys_optional (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (wrap+ (keyed_optional value)
    (wrap+ (keyed_optional value 4) (keyed_optional value 4 :extra 7))))
(defun keys_symbols (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (wrap+ (keyed_explicit key_probe_private:amount value)
    (wrap+ (keyed_explicit) (keyed_lazy :extra value))))
(defun keys_allow ()
  (declare (returns u64) (c-export :c))
  (wrap+ (keyed_allow :unknown (unresolved_key_call))
    (wrap+ (keyed_allow :extra 7 :unknown (unresolved_key_call))
      (wrap+ (keyed_invocation_allow :unknown 4 :allow-other-keys (unresolved_key_call))
        (keyed_control_parameter :unknown 4 :allow-other-keys 5)))))
(defun keys_order ()
  (declare (returns u64) (c-export :c))
  (wrap+ (keyed_order) (keyed_order :left 7)))
(defun keys_truth ()
  (declare (returns u64) (c-export :c))
  (wrap+ (keyed_truth)
    (wrap+ (keyed_truth :extra nil)
      (wrap+ (keyed_truth :extra ()) (keyed_truth :extra 0)))))

(defmacro keyed_whole (&whole form &key (extra (if form 3 unknown_whole_default))) extra)
(defmacro keyed_empty (&key &allow-other-keys) 42)
(defun keys_whole ()
  (declare (returns u64) (c-export :c))
  (wrap+ (keyed_whole) (wrap+ (keyed_whole :extra 7) (keyed_empty :unknown (unresolved_key_call)))))
