(defmacro implicit_sequence (value) 0 value)
(defmacro explicit_sequence (value) (progn 0 value))
(defmacro nested_sequence (value) (progn (progn 0 1) (if t value unknown_sequence)))
(defmacro empty_sequence () (progn))
(defmacro empty_body ())
(defmacro documented_sequence (value) "A build-host documentation string." value)
(defmacro default_sequence (value &optional (extra (progn 0 3)) &aux (copy (progn 1 extra))) `(wrap+ ,value ,copy))
(defun sequence_answer (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (wrap+ (implicit_sequence value) (wrap+ (explicit_sequence value) (nested_sequence value))))
(defun sequence_nil ()
  (declare (returns u64) (c-export :c))
  (wrap+ (if (empty_sequence) 1 42) (if (empty_body) 1 42)))
(defun sequence_defaults (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (wrap+ (documented_sequence value) (default_sequence value)))
