(defmacro discard_form (form) '42)
(defmacro capture_whole (&whole form value) `(discard_form ,form))
(defmacro capture_only (&whole form) `(discard_form ,form))
(defmacro capture_sections (&whole form value &optional (extra value) &rest body &aux (copy form))
  `(discard_form ,copy))
(defun whole_answer (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (wrap+ (capture_whole value) (capture_sections value 1 0 2)))
(defun whole_empty ()
  (declare (returns u64) (c-export :c))
  (capture_only))
