(defmacro select_form (condition consequent alternative) (if condition consequent alternative))
(defmacro no_alternative (condition) (if condition '1))
(defmacro constant_keyword () (if :enabled '42 unbound_control))
(defmacro conditional_default (value &optional (extra (if value '3 unbound_control))) `(wrap+ ,value ,extra))
(defmacro conditional_aux (value &aux (extra (if nil unbound_control '7))) `(wrap+ ,value ,extra))
(defun control_answer (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (wrap+ (conditional_default value) (conditional_aux value)))
(defun control_lazy ()
  (declare (returns u64) (c-export :c))
  (wrap+ (select_form nil (unknown_target_call) 7)
         (wrap+ (select_form 0 42 (unknown_target_call))
                (wrap+ (select_form () (unknown_target_call) 3) (constant_keyword)))))
(defun control_false ()
  (declare (returns u64) (c-export :c))
  (if (no_alternative nil) 1 42))
(defun control_syntax_truth ()
  (declare (returns u64) (c-export :c))
  (select_form (quote nil) 42 (unknown_target_call)))
