(defmacro run_forms (&body forms) `(progn ,@forms 42))
(defmacro apply_forms (operator &rest arguments) `(,operator ,@arguments))
(defmacro empty_lambda nil '42)
(defmacro |.| (form) form)
(defmacro splice_nil (value) `(progn ,@value 42))
(ffi:import-function "macro_rest_tick" ((value u64)) -> u64)
(defun macro_rest_value (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (apply_forms wrap+ value (empty_lambda)))
(defun macro_rest_order (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (run_forms (ffi:call macro_rest_tick value) (ffi:call macro_rest_tick (wrap+ value 1))))
(defun macro_rest_empty ()
  (declare (returns u64) (c-export :c))
  (wrap+ (run_forms) (splice_nil nil)))
(defun macro_rest_quote (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (|.| (apply_forms wrap+ value 9)))

(defmacro repeated (value value) value)
(defmacro repeated_rest (value &rest value) `(wrap+ ,@value))
(defun macro_rest_repeated (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (wrap+ (repeated 999 value) (repeated_rest 999 value 7)))

(defmacro ordinary_ampersand (|&rest|) |&rest|)
(defmacro ordinary_unknown (&custom) &custom)
(defun macro_rest_names (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (wrap+ (ordinary_ampersand value) (ordinary_unknown 9)))
