(defmacro add_list (value) (list 'wrap+ value 3))
(defmacro add_nested_list (value) (list 'wrap+ (list 'wrap+ value 3) 7))
(defmacro list_nothing () (list))
(defmacro list_splice (value &aux (body (list value 3))) `(wrap+ ,@body))
(defun lists_answer (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (wrap+ (add_list value) (add_nested_list value)))
(defun lists_nil ()
  (declare (returns u64) (c-export :c))
  (if (list_nothing) 1 42))
(defun lists_default (value)
  (declare (type u64 value) (returns u64) (c-export :c))
  (list_splice value))

(ffi:import-function "lists_tick" () -> u64)
(defmacro list_twice (form) (list 'wrap+ form form))
(defun lists_effects ()
  (declare (returns u64) (c-export :c))
  (list_twice (ffi:call lists_tick)))
