(defun identity_u64 (value)
  (declare (type u64 value) (returns u64))
  value)

(defun weighted_six (a b c d e f)
  (declare (type u64 a b c d e f)
           (returns u64)
           (c-export :c))
  (wrap+ (wrap* a 1)
         (wrap+ (wrap* b 10)
                (wrap+ (wrap* c 100)
                       (wrap+ (wrap* d 1000)
                              (wrap+ (wrap* e 10000)
                                     (wrap* f 100000)))))))

(defun nested_six ()
  (declare (returns u64) (c-export :c))
  (weighted_six (identity_u64 1)
                (identity_u64 2)
                (identity_u64 3)
                (identity_u64 4)
                (identity_u64 5)
                (identity_u64 6)))
