(load (merge-pathnames "../src/load.lisp" *load-truename*))

(defun roots-test (label mutation expected &optional (name "root_probe"))
 (let ((unit (psl.compiler:read-unit (merge-pathnames "managed_roots.lisp" *load-truename*))))
  (unwind-protect
   (let* ((compilation (psl.compiler:analyze-unit unit :profile "hosted"))
          (signatures (psl.compiler:compilation-signatures compilation)))
    (psl.compiler:lower-unit compilation)
    (psl.compiler:linearize-unit compilation)
    (unless (member :gc (psl.compiler:compilation-runtime-modules compilation))
      (error "missing compiler root runtime dependency"))
    (let ((function (find name (psl.compiler:compilation-lir-functions compilation)
                          :key #'psl.ir:lir-function-name :test #'equal)))
     (funcall mutation function)
     (let ((failure (handler-case (progn (psl.ir:verify-lir-function function signatures 64) nil)
                      (error (condition) condition))))
      (if expected
       (unless (and failure (search expected (princ-to-string failure)))
        (error "~A: wrong receiver result ~A" label failure))
       (when failure (error "~A: ~A" label failure))))))
   (psl.compiler:dispose-unit unit))))

(roots-test "valid" #'identity nil)
(roots-test "root catalogue" (lambda (f) (push 0 (psl.ir:lir-function-root-registers f))) "catalogue")
(roots-test "missing roots" (lambda (f) (setf (psl.ir:lir-function-root-registers f) nil)) "no root frame")
(roots-test "missing sync" (lambda (f)
 (setf (psl.ir:lir-function-instructions f)
       (remove :roots-sync (psl.ir:lir-function-instructions f) :key #'psl.ir:lir-instruction-op))) "synchronization")
(roots-test "active return" (lambda (f)
 (setf (psl.ir:lir-function-instructions f)
       (remove :roots-leave (psl.ir:lir-function-instructions f) :key #'psl.ir:lir-instruction-op))) "frame active")
(roots-test "missing entry" (lambda (f)
 (setf (psl.ir:lir-function-instructions f)
       (remove :roots-enter (psl.ir:lir-function-instructions f) :key #'psl.ir:lir-instruction-op))) "outside frame")
(roots-test "duplicate init" (lambda (f)
 (push (psl.ir:make-lir-instruction :op :roots-init) (psl.ir:lir-function-instructions f))) "duplicate")
(roots-test "late argument" (lambda (f)
 (let ((enter (find :roots-enter (psl.ir:lir-function-instructions f) :key #'psl.ir:lir-instruction-op)))
  (setf (psl.ir:lir-function-instructions f)
        (cons (first (psl.ir:lir-function-instructions f))
              (cons enter (remove enter (rest (psl.ir:lir-function-instructions f)))))))) "argument follows")
(roots-test "leaf" (lambda (f)
 (when (psl.ir:lir-function-root-registers f) (error "leaf unexpectedly roots"))) nil "root_leaf")
(roots-test "allocation-free call graph" (lambda (f)
 (when (psl.ir:lir-function-root-registers f) (error "allocation-free wrapper roots"))) nil "root_free")

(let ((unit (psl.compiler:read-unit (merge-pathnames "managed_roots.lisp" *load-truename*))))
 (unwind-protect
  (let* ((compilation (psl.compiler:analyze-unit unit :profile "hosted"))
         (signatures (psl.compiler:compilation-signatures compilation)))
   (psl.compiler:lower-unit compilation)
   (setf (gethash "psl_rt_push_roots" signatures)
         (psl.ir:make-signature :name "psl_rt_push_roots" :arguments nil
                               :result :u64 :external-p t :effect :none))
   (let ((failure (handler-case (progn (psl.compiler:linearize-unit compilation) nil)
                    (error (condition) condition))))
    (unless (and failure (search "conflicts" (princ-to-string failure)))
      (error "root runtime conflict was accepted: ~A" failure))))
  (psl.compiler:dispose-unit unit)))

(format t "managed LIR root receiver tests passed~%")
