(ffi:import-function "root_cons" ((first value) (rest value)) -> value)
(ffi:import-function "root_collect" () -> void)
(ffi:import-function "root_check" ((live value) (local value) (raw u64)) -> u64)
(defcstruct root_pair (integer u64) (floating f64))
(defun root_probe (raw live number)
 (declare (type u64 raw number) (type value live) (returns u64) (c-export :c))
 (let ((local (ffi:call root_cons (box-fixnum (wrap-cast s64 number)) nil)))
  (ffi:call root_check live local raw)))
(defun root_build (tail count)
 (declare (type value tail) (type u64 count) (returns value) (c-export :c))
 (if (= count 0) tail
   (let ((pair (ffi:call root_cons (box-fixnum (wrap-cast s64 count)) tail)))
     (root_build pair (wrap- count 1)))))
(defun root_float (live number)
 (declare (type value live) (type f64 number) (returns f64) (c-export :c))
 (ffi:call root_collect)
 (if (eq live nil) 0.0d0 number))
(defun root_aggregate (live pair)
 (declare (type value live) (type root_pair pair) (returns root_pair) (c-export :c))
 (ffi:call root_collect)
 pair)
(defun root_join (flag)
 (declare (type u64 flag) (returns value) (c-export :c))
 (let ((pair (if (= flag 0)
                 (ffi:call root_cons (box-fixnum 40) nil)
                 (ffi:call root_cons (box-fixnum 42) nil))))
  (ffi:call root_collect)
  pair))
(defun root_stack (a b c d e f g h i j k l)
 (declare (type value a b c d e f g h i j k l) (returns value) (c-export :c))
 (ffi:call root_collect)
 (ffi:call root_cons a (ffi:call root_cons l nil)))
(defun root_leaf (live)
 (declare (type value live) (returns value) (c-export :c))
 live)
(ffi:import-function "root_step" () -> u64)
(ffi:import-function "root_note" ((value value)) -> void)
(defun root_loop ()
 (declare (returns u64) (c-export :c))
 (while (< (ffi:call root_step) 4097)
  (let ((temp (ffi:call root_cons (box-fixnum 42) nil)))
   (ffi:call root_note temp)))
 42)

(defun root_free (live)
 (declare (type value live) (returns value) (c-export :c))
 (root_leaf live))
