(defun source_identity_values ()
  (declare (returns c-int) (c-export :c))
  (multiple-value-bind (first |first|) (values 20 22)
    (collect-garbage)
    (if (= (unbox-fixnum |FIRST|) 20)
        (if (= (unbox-fixnum |first|) 22) 0 1)
        1)))
(defun source_identity_closure ()
  (declare (returns c-int) (c-export :c))
  (let ((value (box-fixnum 20)) (|value| (box-fixnum 22)))
    (let ((closure #'(lambda (value) (cons value (cons |value| nil)))))
      (collect-garbage)
      (let ((result (funcall closure 20)))
        (if (= (unbox-fixnum (car result)) 20)
            (if (= (unbox-fixnum (car (cdr result))) 22) 0 1)
            1)))))
(defun main ()
  (declare (returns c-int) (c-export :c))
  (if (= (source_identity_values) 0) (source_identity_closure) 1))
