(include "index.lisp")
(defun native_ct_find_alias_from (env name length index)
  (declare (type (ptr native_ct_environment) env) (type (ptr u8) name)
           (type usize length index) (returns usize))
  (if (< (deref (field-pointer env 'alias_count)) index) 0
      (let ((alias (native_ct_alias_at env index)))
        (if (= (native_ct_name_matches env (deref (field-pointer alias 'name))
                 (deref (field-pointer alias 'length)) name length) 1)
            (deref (field-pointer alias 'package))
            (native_ct_find_alias_from env name length (wrap+ index 1))))))
(defun native_ct_add_alias (env package name length)
  (declare (type (ptr native_ct_environment) env) (type usize package length)
           (type (ptr u8) name) (returns usize) (c-export :c))
  (if (= (deref (field-pointer env 'error)) 0)
      (if (= (native_ct_package_valid_p env package) 0) (native_ct_fail env 4)
          (let ((prior (native_ct_find_package env name length)))
            (if (< 0 prior) (if (= prior package) package (native_ct_fail env 2))
                (let ((count (deref (field-pointer env 'alias_count))))
                  (if (= (native_ct_record_room_p count (deref (field-pointer env 'alias_capacity))) 0)
                      (native_ct_fail env 1)
                      (if (= (native_ct_names_room_p env length) 0) (native_ct_fail env 1)
                          (let ((next (wrap+ count 1)))
                            (let ((alias (native_ct_alias_at env next)))
                              (store (field-pointer alias 'package) package)
                              (store (field-pointer alias 'name) (native_ct_copy_name env name length))
                              (store (field-pointer alias 'length) length)
                              (store (field-pointer env 'alias_count) next)
                              package))))))))
      0))
