(include "tables.lisp")

(defun native_ct_hash_name (env name length)
  (declare (type (ptr native_ct_environment) env) (type (ptr u8) name)
           (type usize length) (returns usize))
  (store (field-pointer env 'hash) 5381)
  (store (field-pointer env 'name_cursor) 0)
  (while (< (deref (field-pointer env 'name_cursor)) length)
    (let ((index (deref (field-pointer env 'name_cursor))))
      (store (field-pointer env 'hash)
             (wrap+ (wrap* (deref (field-pointer env 'hash)) 33)
                    (wrap-cast u32 (deref (pointer+ name (wrap-cast isize index))))))
      (store (field-pointer env 'name_cursor) (wrap+ index 1))))
  (bits-and (wrap-cast usize (deref (field-pointer env 'hash)))
            (wrap- (deref (field-pointer env 'bucket_count)) 1)))

(defun native_ct_bucket (env package name length)
  (declare (type (ptr native_ct_environment) env) (type usize package length)
           (type (ptr u8) name) (returns (ptr usize)))
  (pointer+ (deref (field-pointer env 'buckets))
     (wrap-cast isize
       (wrap+ (wrap* (wrap- package 1) (deref (field-pointer env 'bucket_count)))
              (native_ct_hash_name env name length)))))

(defun native_ct_index_product_fits (env package count)
  (declare (type (ptr native_ct_environment) env) (type usize package count)
           (returns c-int))
  (store (field-pointer env 'lookup_cursor) 0)
  (store (field-pointer env 'hash) 1)
  (while (if (< (deref (field-pointer env 'lookup_cursor)) count)
             (= (deref (field-pointer env 'hash)) 1) nil)
    (let ((index (deref (field-pointer env 'lookup_cursor))))
      (if (< (wrap* package (wrap+ index 1)) (wrap* package index))
          (store (field-pointer env 'hash) 0) (wrap-cast u32 0))
      (store (field-pointer env 'lookup_cursor) (wrap+ index 1))))
  (if (= (deref (field-pointer env 'hash)) 1) 1 0))

(defun native_ct_index_package_room_p (env package)
  (declare (type (ptr native_ct_environment) env) (type usize package)
           (returns c-int))
  (let ((count (deref (field-pointer env 'bucket_count)))
        (capacity (deref (field-pointer env 'bucket_capacity))))
    (if (= count 0) 1
        (if (= (ptr-address (deref (field-pointer env 'buckets))) 0) 0
            (if (= (bits-and count (wrap- count 1)) 0)
                (if (< 1024 count) 0
                    (if (= (native_ct_index_product_fits env package count) 1)
                        (if (< capacity (wrap* package count)) 0 1) 0))
                0)))))

(defun native_ct_index_presence (env package reference)
  (declare (type (ptr native_ct_environment) env) (type usize package reference)
           (returns c-int))
  (let ((entry (native_ct_presence_at env reference)))
    (store (field-pointer entry 'bucket_next) 0)
    (if (= (deref (field-pointer env 'bucket_count)) 0) 1
        (let ((symbol (native_ct_symbol_at env (deref (field-pointer entry 'symbol)))))
          (let ((head (native_ct_bucket env package
                         (pointer+ (deref (field-pointer env 'names))
                                   (wrap-cast isize (deref (field-pointer symbol 'name))))
                         (deref (field-pointer symbol 'length)))))
            (store (field-pointer entry 'bucket_next) (deref head))
            (store head reference)
            1)))))

(defun native_ct_clear_package_index (env package)
  (declare (type (ptr native_ct_environment) env) (type usize package)
           (returns c-int))
  (let ((count (deref (field-pointer env 'bucket_count))))
    (store (field-pointer env 'lookup_cursor) 0)
    (while (< (deref (field-pointer env 'lookup_cursor)) count)
      (let ((index (deref (field-pointer env 'lookup_cursor))))
        (store (pointer+ (deref (field-pointer env 'buckets))
                         (wrap-cast isize (wrap+ (wrap* (wrap- package 1) count) index))) 0)
        (store (field-pointer env 'lookup_cursor) (wrap+ index 1))))
    1))
