(include "aliases.lisp")
(defun native_ct_find_package_from (env name length index)
  (declare (type (ptr native_ct_environment) env) (type (ptr u8) name)
           (type usize length index) (returns usize))
  (if (< (deref (field-pointer env 'package_count)) index) 0
      (let ((package (native_ct_package_at env index)))
        (if (= (native_ct_name_matches env (deref (field-pointer package 'name))
                 (deref (field-pointer package 'length)) name length) 1) index
            (native_ct_find_package_from env name length (wrap+ index 1))))))
(defun native_ct_find_package (env name length)
  (declare (type (ptr native_ct_environment) env) (type (ptr u8) name)
           (type usize length) (returns usize) (c-export :c))
  (let ((package (native_ct_find_package_from env name length 1)))
    (if (< 0 package) package (native_ct_find_alias_from env name length 1))))
(defun native_ct_make_package (env name length)
  (declare (type (ptr native_ct_environment) env) (type (ptr u8) name)
           (type usize length) (returns usize) (c-export :c))
  (if (= (deref (field-pointer env 'error)) 0)
      (let ((prior (native_ct_find_package env name length)))
        (if (< 0 prior) (native_ct_fail env 2)
            (let ((count (deref (field-pointer env 'package_count))))
              (if (= (native_ct_record_room_p count (deref (field-pointer env 'package_capacity))) 0) (native_ct_fail env 1)
                  (if (= (native_ct_names_room_p env length) 0) (native_ct_fail env 1)
                      (let ((next (wrap+ count 1)))
                        (let ((package (native_ct_package_at env next)))
                          (store (field-pointer package 'name) (native_ct_copy_name env name length))
                          (store (field-pointer package 'length) length)
                          (store (field-pointer package 'present) 0)
                          (store (field-pointer package 'uses) 0)
                          (store (field-pointer env 'package_count) next)
                          next)))))))
      0))
