(include "read_names.lisp")
(defun native_ct_read_compact (env start from length)
  (declare (type (ptr native_ct_environment) env) (type usize start from length)
           (returns c-int))
  (store (field-pointer env 'read_cursor) 0)
  (while (< (deref (field-pointer env 'read_cursor)) length)
    (let ((index (deref (field-pointer env 'read_cursor)))
          (names (deref (field-pointer env 'names))))
      (store (pointer+ names (wrap-cast isize (wrap+ start index)))
             (deref (pointer+ names (wrap-cast isize (wrap+ from index)))))
      (store (field-pointer env 'read_cursor) (wrap+ index 1))))
  (store (field-pointer env 'name_count) (wrap+ start length))
  1)
(defun native_ct_read_intern (env package start from length)
  (declare (type (ptr native_ct_environment) env) (type usize package start from length)
           (returns usize))
  (native_ct_read_compact env start from length)
  (native_ct_intern_name_span env package start length))
(defun native_ct_read_external (env package start from length)
  (declare (type (ptr native_ct_environment) env) (type usize package start from length)
           (returns usize))
  (let ((entry (native_ct_find_present env package
                (pointer+ (deref (field-pointer env 'names)) (wrap-cast isize from)) length 1)))
    (store (field-pointer env 'name_count) start)
    (if (= entry 0) (native_ct_fail env 9)
        (deref (field-pointer (native_ct_presence_at env entry) 'symbol)))))
(defun native_ct_read_qualified (env start)
  (declare (type (ptr native_ct_environment) env) (type usize start) (returns usize))
  (let ((prefix (deref (field-pointer env 'read_prefix))))
    (let ((from (wrap+ start prefix))
          (package (native_ct_find_package env
                    (pointer+ (deref (field-pointer env 'names)) (wrap-cast isize start)) prefix)))
      (let ((length (wrap- (deref (field-pointer env 'name_count)) from)))
        (if (= package 0)
            (progn (store (field-pointer env 'name_count) start) (native_ct_fail env 6))
            (if (= (deref (field-pointer env 'read_separators)) 1)
                (native_ct_read_external env package start from length)
                (native_ct_read_intern env package start from length)))))))
(defun native_ct_read_finish (env start)
  (declare (type (ptr native_ct_environment) env) (type usize start) (returns usize))
  (let ((length (wrap- (deref (field-pointer env 'name_count)) start)))
    (cond
      ((= (deref (field-pointer env 'read_uninterned)) 1)
       (native_ct_uninterned_span env start length))
      ((= (deref (field-pointer env 'read_separators)) 0)
       (native_ct_intern_name_span env (deref (field-pointer env 'current_package)) start length))
      ((= (deref (field-pointer env 'read_separator)) 0)
       (native_ct_read_intern env (deref (field-pointer env 'keyword_package)) start start length))
      (t (native_ct_read_qualified env start)))))
(defun native_ct_read_symbol_body (env data length uninterned cursor)
  (declare (type (ptr native_ct_environment) env) (type (ptr u8) data)
           (type usize length cursor) (type u8 uninterned) (returns usize))
  (let ((start (deref (field-pointer env 'name_count))))
    (native_ct_read_reset env uninterned cursor)
    (if (= (native_ct_read_scan env data length start) 1) (native_ct_read_finish env start)
        (progn (store (field-pointer env 'name_count) start) 0))))
(defun native_ct_read_symbol (env data length)
  (declare (type (ptr native_ct_environment) env) (type (ptr u8) data)
           (type usize length) (returns usize) (c-export :c))
  (if (= (deref (field-pointer env 'error)) 0)
      (if (= length 0) (native_ct_fail env 8)
          (if (= (ptr-address data) 0) (native_ct_fail env 8)
              (if (= (deref data) 35)
                  (if (< 1 length)
                      (if (= (deref (pointer+ data 1)) 58)
                          (native_ct_read_symbol_body env data length 1 2) (native_ct_fail env 8))
                      (native_ct_fail env 8))
                  (native_ct_read_symbol_body env data length 0 0))))
      0))
