(include "seed.lisp")
(defun native_ct_upper (byte)
  (declare (type u8 byte) (returns u8))
  (if (< 96 byte) (if (< byte 123) (wrap- byte 32) byte) byte))
(defun native_ct_read_append (env byte)
  (declare (type (ptr native_ct_environment) env) (type u8 byte) (returns c-int))
  (if (= (native_ct_names_room_p env 1) 0) (progn (native_ct_fail env 1) 0)
      (let ((next (deref (field-pointer env 'name_count))))
        (store (pointer+ (deref (field-pointer env 'names)) (wrap-cast isize next)) byte)
        (store (field-pointer env 'name_count) (wrap+ next 1))
        (store (field-pointer env 'read_body) 1) 1)))
(defun native_ct_read_colon (env start)
  (declare (type (ptr native_ct_environment) env) (type usize start) (returns c-int))
  (if (= (deref (field-pointer env 'read_uninterned)) 1)
      (progn (native_ct_fail env 8) 0)
      (if (= (deref (field-pointer env 'read_separators)) 0)
          (progn
            (store (field-pointer env 'read_prefix)
                   (wrap- (deref (field-pointer env 'name_count)) start))
            (store (field-pointer env 'read_separator) (deref (field-pointer env 'read_cursor)))
            (store (field-pointer env 'read_separators) 1)
            (store (field-pointer env 'read_body) 0) 1)
          (if (if (= (deref (field-pointer env 'read_separators)) 1)
                  (= (deref (field-pointer env 'read_cursor))
                     (wrap+ (deref (field-pointer env 'read_separator)) 1)) nil)
              (progn (store (field-pointer env 'read_separators) 2)
                     (store (field-pointer env 'read_body) 0) 1)
              (progn (native_ct_fail env 8) 0)))))
(defun native_ct_read_delimiter_p (byte)
  (declare (type u8 byte) (returns c-int))
  (cond ((< byte 33) 1) ((= byte 40) 1) ((= byte 41) 1)
        ((= byte 34) 1) ((= byte 59) 1) ((= byte 39) 1)
        ((= byte 96) 1) ((= byte 44) 1) (t 0)))
(defun native_ct_read_byte (env byte start)
  (declare (type (ptr native_ct_environment) env) (type u8 byte)
           (type usize start) (returns c-int))
  (cond
    ((= (deref (field-pointer env 'read_escape)) 1)
     (store (field-pointer env 'read_escape) 0)
     (native_ct_read_append env byte))
    ((= byte 92) (store (field-pointer env 'read_escape) 1) 1)
    ((= byte 124)
     (store (field-pointer env 'read_bar)
            (if (= (deref (field-pointer env 'read_bar)) 0) 1 0))
     (store (field-pointer env 'read_body) 1) 1)
    ((= (deref (field-pointer env 'read_bar)) 1) (native_ct_read_append env byte))
    ((= byte 58) (native_ct_read_colon env start))
    ((= (native_ct_read_delimiter_p byte) 1) (progn (native_ct_fail env 8) 0))
    (t (native_ct_read_append env (native_ct_upper byte)))))
(defun native_ct_read_reset (env uninterned cursor)
  (declare (type (ptr native_ct_environment) env) (type u8 uninterned)
           (type usize cursor) (returns c-int))
  (store (field-pointer env 'read_cursor) cursor)
  (store (field-pointer env 'read_prefix) 0)
  (store (field-pointer env 'read_separator) 0)
  (store (field-pointer env 'read_separators) 0)
  (store (field-pointer env 'read_bar) 0)
  (store (field-pointer env 'read_escape) 0)
  (store (field-pointer env 'read_body) uninterned)
  (store (field-pointer env 'read_uninterned) uninterned)
  1)
(defun native_ct_read_scan (env data length start)
  (declare (type (ptr native_ct_environment) env) (type (ptr u8) data)
           (type usize length start) (returns c-int))
  (while (if (= (deref (field-pointer env 'error)) 0)
             (< (deref (field-pointer env 'read_cursor)) length) nil)
    (let ((cursor (deref (field-pointer env 'read_cursor))))
      (native_ct_read_byte env (deref (pointer+ data (wrap-cast isize cursor))) start)
      (store (field-pointer env 'read_cursor) (wrap+ cursor 1))))
  (if (if (= (deref (field-pointer env 'read_bar)) 0)
          (= (deref (field-pointer env 'read_escape)) 0) nil)
      (if (= (deref (field-pointer env 'read_body)) 1)
          (if (= (deref (field-pointer env 'error)) 0) 1 0)
          (progn (native_ct_fail env 8) 0))
      (progn (native_ct_fail env 8) 0)))
