(include "read_symbols.lisp")
(include "reader_types.lisp")

(defun native_identity_at (reader reference)
  (declare (type (ptr native_reader_environment) reader) (type usize reference)
           (returns (ptr native_source_identity)))
  (pointer+ (deref (field-pointer reader 'identities))
            (wrap-cast isize (wrap- reference 1))))

(defun native_identity_numeric_p (context reference)
  (declare (type (ptr native_compile_context) context) (type usize reference)
           (returns c-int))
  (if (= (scalar_float_atom_p context reference) 0)
      (if (= (scalar_integer_atom_p (deref (field-pointer context 'parser))
                  (deref (field-pointer context 'source)) reference
                  (deref (field-pointer context 'integer))) 0) 0 1)
      1))

(defun native_identity_atom (context reader reference)
  (declare (type (ptr native_compile_context) context)
           (type (ptr native_reader_environment) reader) (type usize reference)
           (returns usize))
  (if (= (native_identity_numeric_p context reference) 1) 0
      (let ((node (parser_node (deref (field-pointer context 'parser)) reference)))
        (native_ct_read_symbol (deref (field-pointer reader 'environment))
           (pointer+ (deref (field-pointer context 'source))
                     (wrap-cast isize (deref (field-pointer node 'start))))
           (deref (field-pointer node 'length))))))

(defun native_identity_resolve_node (context reader reference)
  (declare (type (ptr native_compile_context) context)
           (type (ptr native_reader_environment) reader) (type usize reference)
           (returns c-int))
  (let ((identity (native_identity_at reader reference))
        (node (parser_node (deref (field-pointer context 'parser)) reference)))
    (store (field-pointer identity 'origin) reference)
    (store (field-pointer identity 'symbol)
           (if (= (deref (field-pointer node 'kind)) 8)
               (native_identity_atom context reader reference) (wrap-cast usize 0)))
    (if (= (deref (field-pointer (deref (field-pointer reader 'environment)) 'error)) 0) 1
        (progn (store (field-pointer reader 'error) reference)
               (store (field-pointer reader 'failure) 3) 0))))

(defun native_resolve_source_identities (context reader)
  (declare (type (ptr native_compile_context) context)
           (type (ptr native_reader_environment) reader) (returns c-int) (c-export :c))
  (let ((count (deref (field-pointer (deref (field-pointer context 'parser)) 'count))))
    (if (< (deref (field-pointer reader 'capacity)) count)
        (progn (store (field-pointer reader 'failure) 1) 0)
        (if (< count (deref (field-pointer reader 'count)))
            (progn (store (field-pointer reader 'failure) 2) 0)
            (progn
              (store (field-pointer reader 'cursor) (wrap+ (deref (field-pointer reader 'count)) 1))
              (while (if (= (deref (field-pointer reader 'failure)) 0)
                         (if (< count (deref (field-pointer reader 'cursor))) nil t) nil)
                (let ((reference (deref (field-pointer reader 'cursor))))
                  (if (= (native_identity_resolve_node context reader reference) 1)
                      (store (field-pointer reader 'count) reference) (wrap-cast usize 0))
                  (store (field-pointer reader 'cursor) (wrap+ reference 1))))
              (if (= (deref (field-pointer reader 'failure)) 0) 1 0))))))
