(include "visibility.lisp")
(defun native_ct_seed_word_byte (a b c d e index)
  (declare (type u64 a b c d e) (type usize index) (returns u8))
  (let ((word (if (< index 8) a (if (< index 16) b
                    (if (< index 24) c (if (< index 32) d e)))))
        (shift (wrap-cast u64 (wrap* (bits-and index 7) 8))))
    (wrap-cast u8 (shr64 word shift))))
(defun native_ct_seed_name (env package length a b c d e)
  (declare (type (ptr native_ct_environment) env) (type usize package length)
           (type u64 a b c d e) (returns usize))
  (if (= (deref (field-pointer env 'error)) 0)
      (if (= (native_ct_names_room_p env length) 0) (native_ct_fail env 1)
          (let ((start (deref (field-pointer env 'name_count))))
            (while (< (wrap- (deref (field-pointer env 'name_count)) start) length)
              (let ((next (deref (field-pointer env 'name_count))))
                (store (pointer+ (deref (field-pointer env 'names)) (wrap-cast isize next))
                       (native_ct_seed_word_byte a b c d e (wrap- next start)))
                (store (field-pointer env 'name_count) (wrap+ next 1))))
            (native_ct_intern_name_span env package start length)))
      0))
(defun native_ct_seed_export (env package length a b c d e)
  (declare (type (ptr native_ct_environment) env) (type usize package length)
           (type u64 a b c d e) (returns c-int))
  (let ((symbol (native_ct_seed_name env package length a b c d e)))
    (if (= symbol 0) 0
        (if (= (native_ct_bind_symbol env package symbol 1) 0) 0 1))))
