(include "packages.lisp")
;; Presence flags: 1 means external; 2 means explicitly shadowing.
(defun native_ct_find_present (env package name length external)
  (declare (type (ptr native_ct_environment) env) (type usize package length)
           (type (ptr u8) name) (type c-int external) (returns usize))
  (store (field-pointer env 'lookup_result) 0)
  (store (field-pointer env 'lookup_cursor)
         (if (= (deref (field-pointer env 'bucket_count)) 0)
             (deref (field-pointer (native_ct_package_at env package) 'present))
             (deref (native_ct_bucket env package name length))))
  (while (if (= (deref (field-pointer env 'lookup_result)) 0)
             (< 0 (deref (field-pointer env 'lookup_cursor))) nil)
    (let ((entry (native_ct_presence_at env (deref (field-pointer env 'lookup_cursor)))))
      (let ((symbol (native_ct_symbol_at env (deref (field-pointer entry 'symbol)))))
        (if (if (= external 0) t (= (bits-and (deref (field-pointer entry 'flags)) 1) 1))
            (if (= (native_ct_name_matches env (deref (field-pointer symbol 'name))
                     (deref (field-pointer symbol 'length)) name length) 1)
                (store (field-pointer env 'lookup_result)
                       (deref (field-pointer env 'lookup_cursor))) (wrap-cast usize 0))
            (wrap-cast usize 0)))
      (store (field-pointer env 'lookup_cursor)
             (if (= (deref (field-pointer env 'bucket_count)) 0)
                 (deref (field-pointer entry 'next))
                 (deref (field-pointer entry 'bucket_next))))))
  (deref (field-pointer env 'lookup_result)))
(defun native_ct_find_used (env name length edge inherited)
  (declare (type (ptr native_ct_environment) env) (type (ptr u8) name)
           (type usize length edge inherited) (returns usize))
  (if (= edge 0) inherited
      (let ((use (native_ct_use_at env edge)))
        (let ((entry (native_ct_find_present env (deref (field-pointer use 'package))
                                             name length 1)))
          (let ((found (if (= entry 0) (wrap-cast usize 0)
                          (deref (field-pointer (native_ct_presence_at env entry) 'symbol)))))
            (if (= found 0)
                (native_ct_find_used env name length (deref (field-pointer use 'next)) inherited)
                (if (if (= inherited 0) t (= inherited found))
                    (native_ct_find_used env name length (deref (field-pointer use 'next)) found)
                    (native_ct_fail env 3))))))))
(defun native_ct_find_symbol (env package name length)
  (declare (type (ptr native_ct_environment) env) (type usize package length)
           (type (ptr u8) name) (returns usize) (c-export :c))
  (if (= (native_ct_package_valid_p env package) 0) (native_ct_fail env 4)
      (let ((entry (native_ct_find_present env package name length 0)))
        (if (< 0 entry) (deref (field-pointer (native_ct_presence_at env entry) 'symbol))
            (native_ct_find_used env name length
               (deref (field-pointer (native_ct_package_at env package) 'uses)) 0)))))
(defun native_ct_add_presence (env package symbol flags)
  (declare (type (ptr native_ct_environment) env) (type usize package symbol)
           (type u32 flags) (returns usize))
  (let ((count (deref (field-pointer env 'present_count))))
    (if (= (native_ct_record_room_p count (deref (field-pointer env 'present_capacity))) 0) (native_ct_fail env 1)
        (let ((next (wrap+ count 1)) (owner (native_ct_package_at env package)))
          (let ((entry (native_ct_presence_at env next)))
            (store (field-pointer entry 'symbol) symbol)
            (store (field-pointer entry 'flags) flags)
            (store (field-pointer entry 'next) (deref (field-pointer owner 'present)))
            (store (field-pointer owner 'present) next)
            (store (field-pointer env 'present_count) next)
            (native_ct_index_presence env package next)
            symbol)))))
(defun native_ct_symbol_room_p (env)
  (declare (type (ptr native_ct_environment) env) (returns c-int))
  (if (= (native_ct_record_room_p (deref (field-pointer env 'symbol_count))
           (deref (field-pointer env 'symbol_capacity))) 0) 0
      (native_ct_record_room_p (deref (field-pointer env 'present_count))
                              (deref (field-pointer env 'present_capacity)))))
(defun native_ct_symbol_from_name (env package offset length)
  (declare (type (ptr native_ct_environment) env) (type usize package offset length)
           (returns usize))
  (let ((next (wrap+ (deref (field-pointer env 'symbol_count)) 1)))
    (let ((symbol (native_ct_symbol_at env next)))
      (store (field-pointer symbol 'package) package)
      (store (field-pointer symbol 'name) offset)
      (store (field-pointer symbol 'length) length)
      (store (field-pointer env 'symbol_count) next)
      (native_ct_add_presence env package next
       (if (= package (deref (field-pointer env 'keyword_package))) 1 (wrap-cast u32 0))))))
(defun native_ct_new_symbol (env package name length)
  (declare (type (ptr native_ct_environment) env) (type usize package length)
           (type (ptr u8) name) (returns usize))
  (if (= (native_ct_symbol_room_p env) 0) (native_ct_fail env 1)
      (if (= (native_ct_names_room_p env length) 0) (native_ct_fail env 1)
          (native_ct_symbol_from_name env package (native_ct_copy_name env name length) length))))
(defun native_ct_intern_name_span (env package offset length)
  (declare (type (ptr native_ct_environment) env) (type usize package offset length)
           (returns usize))
  (if (= (deref (field-pointer env 'error)) 0)
      (let ((prior (native_ct_find_symbol env package
                    (pointer+ (deref (field-pointer env 'names)) (wrap-cast isize offset)) length)))
        (if (< 0 prior) (progn (store (field-pointer env 'name_count) offset) prior)
            (if (= (deref (field-pointer env 'error)) 0)
                (if (= (native_ct_symbol_room_p env) 1)
                    (native_ct_symbol_from_name env package offset length)
                    (progn (store (field-pointer env 'name_count) offset) (native_ct_fail env 1)))
                (progn (store (field-pointer env 'name_count) offset) 0))))
      0))
(defun native_ct_uninterned_span (env offset length)
  (declare (type (ptr native_ct_environment) env) (type usize offset length)
           (returns usize))
  (if (= (deref (field-pointer env 'error)) 0)
      (let ((count (deref (field-pointer env 'symbol_count))))
        (if (= (native_ct_record_room_p count (deref (field-pointer env 'symbol_capacity))) 0)
            (progn (store (field-pointer env 'name_count) offset) (native_ct_fail env 1))
            (let ((next (wrap+ count 1)))
              (let ((symbol (native_ct_symbol_at env next)))
                (store (field-pointer symbol 'package) 0)
                (store (field-pointer symbol 'name) offset)
                (store (field-pointer symbol 'length) length)
                (store (field-pointer env 'symbol_count) next)
                next))))
      0))
(defun native_ct_intern (env package name length)
  (declare (type (ptr native_ct_environment) env) (type usize package length)
           (type (ptr u8) name) (returns usize) (c-export :c))
  (if (= (deref (field-pointer env 'error)) 0)
      (let ((prior (native_ct_find_symbol env package name length)))
        (if (= (deref (field-pointer env 'error)) 0)
            (if (< 0 prior) prior (native_ct_new_symbol env package name length)) 0))
      0))
