(include "types.lisp")
(defun native_ct_package_at (env reference)
  (declare (type (ptr native_ct_environment) env) (type usize reference)
           (returns (ptr native_ct_package)))
  (pointer+ (deref (field-pointer env 'packages)) (wrap-cast isize (wrap- reference 1))))
(defun native_ct_symbol_at (env reference)
  (declare (type (ptr native_ct_environment) env) (type usize reference)
           (returns (ptr native_ct_symbol)))
  (pointer+ (deref (field-pointer env 'symbols)) (wrap-cast isize (wrap- reference 1))))
(defun native_ct_presence_at (env reference)
  (declare (type (ptr native_ct_environment) env) (type usize reference)
           (returns (ptr native_ct_presence)))
  (pointer+ (deref (field-pointer env 'present)) (wrap-cast isize (wrap- reference 1))))
(defun native_ct_use_at (env reference)
  (declare (type (ptr native_ct_environment) env) (type usize reference)
           (returns (ptr native_ct_use)))
  (pointer+ (deref (field-pointer env 'uses)) (wrap-cast isize (wrap- reference 1))))
(defun native_ct_fail (env error)
  (declare (type (ptr native_ct_environment) env) (type u32 error) (returns usize))
  (if (= (deref (field-pointer env 'error)) 0)
      (store (field-pointer env 'error) error) (wrap-cast u32 0))
  0)
(defun native_ct_package_valid_p (env reference)
  (declare (type (ptr native_ct_environment) env) (type usize reference) (returns c-int))
  (if (= reference 0) 0
      (if (< (deref (field-pointer env 'package_count)) reference) 0 1)))
(defun native_ct_symbol_valid_p (env reference)
  (declare (type (ptr native_ct_environment) env) (type usize reference) (returns c-int))
  (if (= reference 0) 0
      (if (< (deref (field-pointer env 'symbol_count)) reference) 0 1)))
(defun native_ct_name_matches (env offset length name size)
  (declare (type (ptr native_ct_environment) env) (type usize offset length size)
           (type (ptr u8) name) (returns c-int))
  (store (field-pointer env 'name_cursor) 0)
  (store (field-pointer env 'name_result) (if (= length size) 1 0))
  (while (if (< (deref (field-pointer env 'name_cursor)) length)
             (= (deref (field-pointer env 'name_result)) 1) nil)
    (let ((index (deref (field-pointer env 'name_cursor))))
      (if (= (deref (pointer+ (deref (field-pointer env 'names))
                               (wrap-cast isize (wrap+ offset index))))
             (deref (pointer+ name (wrap-cast isize index))))
          (wrap-cast c-int 0) (store (field-pointer env 'name_result) 0))
      (store (field-pointer env 'name_cursor) (wrap+ index 1))))
  (deref (field-pointer env 'name_result)))
(defun native_ct_names_room_p (env length)
  (declare (type (ptr native_ct_environment) env) (type usize length) (returns c-int))
  (let ((count (deref (field-pointer env 'name_count)))
        (capacity (deref (field-pointer env 'name_capacity))))
    (if (< capacity count) 0 (if (< (wrap- capacity count) length) 0 1))))
(defun native_ct_copy_name (env name length)
  (declare (type (ptr native_ct_environment) env) (type (ptr u8) name)
           (type usize length) (returns usize))
  (let ((start (deref (field-pointer env 'name_count))))
    (while (< (wrap- (deref (field-pointer env 'name_count)) start) length)
      (let ((next (deref (field-pointer env 'name_count))))
        (store (pointer+ (deref (field-pointer env 'names)) (wrap-cast isize next))
               (deref (pointer+ name (wrap-cast isize (wrap- next start)))))
        (store (field-pointer env 'name_count) (wrap+ next 1))))
    start))

(defun native_ct_record_room_p (count capacity)
  (declare (type usize count capacity) (returns c-int))
  (if (< count capacity) 1 0))

(defun native_ct_alias_at (env reference)
  (declare (type (ptr native_ct_environment) env) (type usize reference)
           (returns (ptr native_ct_alias)))
  (pointer+ (deref (field-pointer env 'aliases)) (wrap-cast isize (wrap- reference 1))))
