;; Build-host symbol identity and package visibility in caller-owned arenas.
;; References are one-based table indices; no target addresses enter this state.
(defcstruct native_ct_package
  (name usize)
  (length usize)
  (present usize)
  (uses usize))
(defcstruct native_ct_symbol
  (package usize)
  (name usize)
  (length usize))
(defcstruct native_ct_presence
  (symbol usize)
  (next usize)
  (flags u32))
(defcstruct native_ct_use
  (package usize)
  (next usize))
(defcstruct native_ct_alias
  (package usize)
  (name usize)
  (length usize))
(defcstruct native_ct_environment
  (names (ptr u8))
  (name_count usize)
  (name_capacity usize)
  (packages (ptr native_ct_package))
  (package_count usize)
  (package_capacity usize)
  (symbols (ptr native_ct_symbol))
  (symbol_count usize)
  (symbol_capacity usize)
  (present (ptr native_ct_presence))
  (present_count usize)
  (present_capacity usize)
  (uses (ptr native_ct_use))
  (use_count usize)
  (use_capacity usize)
  (aliases (ptr native_ct_alias))
  (alias_count usize)
  (alias_capacity usize)
  (current_package usize)
  (keyword_package usize)
  (nil_symbol usize)
  (true_symbol usize)
  (name_cursor usize)
  (name_result c-int)
  (lookup_cursor usize)
  (lookup_result usize)
  (read_cursor usize)
  (read_prefix usize)
  (read_separator usize)
  (read_separators u32)
  (read_bar u8)
  (read_escape u8)
  (read_body u8)
  (read_uninterned u8)
  (error u32))
