(include "symbols.lisp")
;; Low-level environment construction: the language package operations validate
;; their transactions before linking these records.
(defun native_ct_bind_symbol (env package symbol flags)
  (declare (type (ptr native_ct_environment) env) (type usize package symbol)
           (type u32 flags) (returns usize) (c-export :c))
  (if (= (deref (field-pointer env 'error)) 0)
      (if (= (native_ct_package_valid_p env package) 0) (native_ct_fail env 4)
          (if (= (native_ct_symbol_valid_p env symbol) 0) (native_ct_fail env 4)
              (let ((definition (native_ct_symbol_at env symbol)))
                (let ((name (pointer+ (deref (field-pointer env 'names))
                                      (wrap-cast isize (deref (field-pointer definition 'name))))))
                  (let ((prior (native_ct_find_present env package name
                                 (deref (field-pointer definition 'length)) 0)))
                    (if (= prior 0) (native_ct_add_presence env package symbol flags)
                        (let ((entry (native_ct_presence_at env prior)))
                          (if (if (= (deref (field-pointer entry 'symbol)) symbol) t
                                  (= (bits-and flags 2) 2))
                              (progn (store (field-pointer entry 'symbol) symbol)
                                     (store (field-pointer entry 'flags) flags) symbol)
                              (native_ct_fail env 3)))))))))
      0))
(defun native_ct_has_use (env edge package)
  (declare (type (ptr native_ct_environment) env) (type usize edge package)
           (returns c-int))
  (if (= edge 0) 0
      (let ((entry (native_ct_use_at env edge)))
        (if (= (deref (field-pointer entry 'package)) package) 1
            (native_ct_has_use env (deref (field-pointer entry 'next)) package)))))
(defun native_ct_link_use (env package used)
  (declare (type (ptr native_ct_environment) env) (type usize package used)
           (returns c-int) (c-export :c))
  (if (= (deref (field-pointer env 'error)) 0)
      (if (= (native_ct_package_valid_p env package) 0)
          (progn (native_ct_fail env 4) 0)
          (if (= (native_ct_package_valid_p env used) 0)
              (progn (native_ct_fail env 4) 0)
              (let ((owner (native_ct_package_at env package)))
                (if (= (native_ct_has_use env (deref (field-pointer owner 'uses)) used) 1) 1
                    (let ((count (deref (field-pointer env 'use_count))))
                      (if (= (native_ct_record_room_p count (deref (field-pointer env 'use_capacity))) 0)
                          (progn (native_ct_fail env 1) 0)
                          (let ((next (wrap+ count 1)))
                            (let ((entry (native_ct_use_at env next)))
                              (store (field-pointer entry 'package) used)
                              (store (field-pointer entry 'next) (deref (field-pointer owner 'uses)))
                              (store (field-pointer owner 'uses) next)
                              (store (field-pointer env 'use_count) next)
                              1))))))))
      0))
