(in-package #:psl.backend.x86-64)

(defstruct relocation offset name)
(defstruct encoded-function name bytes relocations)
(defstruct (emitter (:constructor make-emitter ()))
  (bytes (byte-buffer))
  (relocations nil)
  (labels (make-hash-table))
  (fixups nil))

(defun emit-slot (buffer opcode register slot)
  ;; REX.W + MOV with an RBP-relative 32-bit displacement.
  (emit-bytes buffer (if (>= register 8) #x4c #x48)
              opcode (+ #x85 (ash (mod register 8) 3)))
  (emit-integer buffer (- (* (1+ slot) 8)) 4))

(defun emit-load-slot (buffer register slot)
  (emit-slot buffer #x8b register slot))

(defun emit-store-slot (buffer register slot)
  (emit-slot buffer #x89 register slot))

(defun x86-type-width (type)
  (if (or (pointer-type-p type) (eq type :boolean)) 64
      (type-width type 64)))

(defun normalize-rax (buffer type)
  (let ((width (x86-type-width type)))
    (case width
      (8 (if (signed-type-p type)
             (emit-bytes buffer #x48 #x0f #xbe #xc0)
             (emit-bytes buffer #x0f #xb6 #xc0)))
      (16 (if (signed-type-p type)
              (emit-bytes buffer #x48 #x0f #xbf #xc0)
              (emit-bytes buffer #x0f #xb7 #xc0)))
      (32 (if (signed-type-p type)
              (emit-bytes buffer #x48 #x63 #xc0)
              (emit-bytes buffer #x89 #xc0)))
      (64 nil)
      (otherwise (error "PSL internal error: unsupported type width ~A" width)))))

(defun emit-constant (emitter instruction)
  (let ((buffer (emitter-bytes emitter))
        (value (lir-instruction-value instruction)))
    (emit-bytes buffer #x48 #xb8)
    (emit-integer buffer (car value) 8)
    (normalize-rax buffer (cdr value))
    (emit-store-slot buffer 0 (lir-instruction-dst instruction))))

(defun emit-copy (emitter instruction)
  (let ((buffer (emitter-bytes emitter)))
    (emit-load-slot buffer 0 (first (lir-instruction-args instruction)))
    (emit-store-slot buffer 0 (lir-instruction-dst instruction))))

(defun emit-comparison (buffer operator type)
  (emit-bytes buffer #x48 #x39 #xc1 #x0f
              (cond ((equal operator "=") #x94)
                    ((eq type :s64) #x9c)
                    (t #x92))
              #xc0 #x48 #x0f #xb6 #xc0))

(defun emit-binary-operation (buffer operator type)
  (cond
    ((equal operator "wrap+") (emit-bytes buffer #x48 #x01 #xc8))
    ((equal operator "wrap-")
     (emit-bytes buffer #x48 #x29 #xc1 #x48 #x89 #xc8))
    ((equal operator "wrap*") (emit-bytes buffer #x48 #x0f #xaf #xc1))
    ((member operator '("=" "<") :test #'equal)
     (emit-comparison buffer operator type))
    (t (error "PSL internal error: unknown operation ~A" operator))))

(defun emit-binary (emitter instruction)
  (let ((buffer (emitter-bytes emitter))
        (operands (lir-instruction-args instruction))
        (operation (lir-instruction-value instruction)))
    (emit-load-slot buffer 1 (first operands))
    (emit-load-slot buffer 0 (second operands))
    (emit-binary-operation buffer (car operation) (cdr operation))
    (unless (member (car operation) '("=" "<") :test #'equal)
      (normalize-rax buffer (cdr operation)))
    (emit-store-slot buffer 0 (lir-instruction-dst instruction))))

(defun emit-argument (emitter instruction)
  (let* ((value (lir-instruction-value instruction))
         (register (nth (car value) '(7 6 2 1 8 9)))
         (slot (lir-instruction-dst instruction))
         (buffer (emitter-bytes emitter)))
    (emit-store-slot buffer register slot)
    (when (< (x86-type-width (cdr value)) 64)
      (emit-load-slot buffer 0 slot)
      (normalize-rax buffer (cdr value))
      (emit-store-slot buffer 0 slot))))

(defun emit-call (emitter instruction)
  (let ((buffer (emitter-bytes emitter)))
    (loop for slot in (lir-instruction-args instruction)
          for register in '(7 6 2 1 8 9)
          do (emit-load-slot buffer register slot))
    (emit-byte buffer #xe8)
    (push (make-relocation :offset (length buffer)
                           :name (car (lir-instruction-value instruction)))
          (emitter-relocations emitter))
    (emit-integer buffer 0 4)
    (normalize-rax buffer (cdr (lir-instruction-value instruction)))
    (emit-store-slot buffer 0 (lir-instruction-dst instruction))))

(defun emit-field-pointer (emitter instruction)
  (let ((buffer (emitter-bytes emitter))
        (offset (lir-instruction-value instruction)))
    (unless (<= 0 offset #x7fffffff)
      (error "PSL structure field offset exceeds x86-64 immediate range"))
    (emit-load-slot buffer 0 (first (lir-instruction-args instruction)))
    (emit-bytes buffer #x48 #x05)
    (emit-integer buffer offset 4)
    (emit-store-slot buffer 0 (lir-instruction-dst instruction))))

(defun emit-pointer-add (emitter instruction)
  (let ((buffer (emitter-bytes emitter))
        (scale (lir-instruction-value instruction))
        (operands (lir-instruction-args instruction)))
    (unless (<= 1 scale #x7fffffff)
      (error "PSL pointer element size exceeds x86-64 immediate range"))
    (emit-load-slot buffer 1 (first operands))
    (emit-load-slot buffer 0 (second operands))
    (unless (= scale 1)
      (emit-bytes buffer #x48 #x69 #xc0)
      (emit-integer buffer scale 4))
    (emit-bytes buffer #x48 #x01 #xc8)
    (emit-store-slot buffer 0 (lir-instruction-dst instruction))))

(defun emit-memory-load (buffer type)
  (let ((width (x86-type-width type)))
    (case width
      (8 (if (signed-type-p type)
             (emit-bytes buffer #x48 #x0f #xbe #x00)
             (emit-bytes buffer #x0f #xb6 #x00)))
      (16 (if (signed-type-p type)
              (emit-bytes buffer #x48 #x0f #xbf #x00)
              (emit-bytes buffer #x0f #xb7 #x00)))
      (32 (if (signed-type-p type)
              (emit-bytes buffer #x48 #x63 #x00)
              (emit-bytes buffer #x8b #x00)))
      (64 (emit-bytes buffer #x48 #x8b #x00))
      (otherwise (error "PSL unsupported load width ~A" width)))))

(defun emit-load (emitter instruction)
  (let ((buffer (emitter-bytes emitter)))
    (emit-load-slot buffer 0 (first (lir-instruction-args instruction)))
    (emit-memory-load buffer (lir-instruction-value instruction))
    (emit-store-slot buffer 0 (lir-instruction-dst instruction))))

(defun emit-memory-store (buffer type)
  (case (x86-type-width type)
    (8 (emit-bytes buffer #x88 #x01))
    (16 (emit-bytes buffer #x66 #x89 #x01))
    (32 (emit-bytes buffer #x89 #x01))
    (64 (emit-bytes buffer #x48 #x89 #x01))
    (otherwise (error "PSL unsupported store type ~S" type))))

(defun emit-store (emitter instruction)
  (let ((buffer (emitter-bytes emitter))
        (operands (lir-instruction-args instruction)))
    (emit-load-slot buffer 1 (first operands))
    (emit-load-slot buffer 0 (second operands))
    (emit-memory-store buffer (lir-instruction-value instruction))
    (emit-store-slot buffer 0 (lir-instruction-dst instruction))))

(defun reserve-branch (emitter label &rest opcodes)
  (let ((buffer (emitter-bytes emitter)))
    (apply #'emit-bytes buffer opcodes)
    (push (cons (length buffer) label) (emitter-fixups emitter))
    (emit-integer buffer 0 4)))

(defun emit-branch-zero (emitter instruction)
  (let ((buffer (emitter-bytes emitter)))
    (emit-load-slot buffer 0 (first (lir-instruction-args instruction)))
    (emit-bytes buffer #x48 #x85 #xc0)
    (reserve-branch emitter (lir-instruction-value instruction) #x0f #x84)))

(defun emit-label (emitter instruction)
  (let ((label (lir-instruction-value instruction)))
    (when (gethash label (emitter-labels emitter))
      (error "PSL internal error: duplicate label ~A" label))
    (setf (gethash label (emitter-labels emitter))
          (length (emitter-bytes emitter)))))

(defun emit-return (emitter instruction)
  (let ((buffer (emitter-bytes emitter)))
    (emit-load-slot buffer 0 (first (lir-instruction-args instruction)))
    (emit-bytes buffer #xc9 #xc3)))

(defun emit-instruction (emitter instruction)
  (case (lir-instruction-op instruction)
    (:argument (emit-argument emitter instruction))
    (:constant (emit-constant emitter instruction))
    (:copy (emit-copy emitter instruction))
    (:binary (emit-binary emitter instruction))
    (:call (emit-call emitter instruction))
    (:field-pointer (emit-field-pointer emitter instruction))
    (:pointer-add (emit-pointer-add emitter instruction))
    (:load (emit-load emitter instruction))
    (:store (emit-store emitter instruction))
    (:branch-zero (emit-branch-zero emitter instruction))
    (:jump (reserve-branch emitter (lir-instruction-value instruction) #xe9))
    (:label (emit-label emitter instruction))
    (:return (emit-return emitter instruction))
    (otherwise
     (error "PSL internal error: unsupported LIR operation ~A"
            (lir-instruction-op instruction)))))

(defun patch-branches (emitter)
  (dolist (fixup (emitter-fixups emitter))
    (let ((destination (gethash (cdr fixup) (emitter-labels emitter))))
      (unless destination
        (error "PSL internal error: missing label ~A" (cdr fixup)))
      (patch-i32 (emitter-bytes emitter) (car fixup)
                 (- destination (+ (car fixup) 4))))))

(defun emit-prologue (buffer)
  ;; The frame-size field is patched after all LIR registers are known.
  (emit-bytes buffer #x55 #x48 #x89 #xe5 #x48 #x81 #xec 0 0 0 0))

(defun compile-function (function)
  (let ((emitter (make-emitter)))
    (emit-prologue (emitter-bytes emitter))
    (dolist (instruction (lir-function-instructions function))
      (emit-instruction emitter instruction))
    (patch-branches emitter)
    (patch-i32 (emitter-bytes emitter) 7
               (* 16 (ceiling (* (lir-function-register-count function) 8) 16)))
    (make-encoded-function
     :name (lir-function-name function)
     :bytes (emitter-bytes emitter)
     :relocations (nreverse (emitter-relocations emitter)))))
