(in-package #:psl.ir)

(defun verify-hir-children (node environment signatures pointer-bits)
  (mapcar (lambda (child)
            (verify-hir-node child environment signatures pointer-bits))
          (hir-children node)))

(defun verify-hir-binary (node types)
  (expect-count types 2 "binary operation")
  (let ((operation (car (hir-value node)))
        (operand-type (cdr (hir-value node))))
    (unless (member operation '("wrap+" "wrap-" "wrap*" "=" "<")
                    :test #'equal)
      (fail "unknown HIR binary operation ~S" operation))
    (unless (integer-type-p operand-type)
      (fail "HIR binary operand must be a machine integer"))
    (dolist (type types)
      (expect-same-type type operand-type "binary operand"))
    (expect-same-type
     (hir-type node)
     (if (member operation '("=" "<") :test #'equal)
         :boolean operand-type)
     "binary result")))

(defun verify-hir-let (node environment signatures pointer-bits)
  (let ((bindings (hir-value node))
        (body-environment environment))
    (dolist (binding bindings)
      (unless (and (consp binding) (stringp (car binding)))
        (fail "malformed HIR LET binding"))
      (let ((type (verify-hir-node (cdr binding) environment
                                   signatures pointer-bits)))
        (push (cons (car binding) type) body-environment)))
    (expect-count (hir-children node) 1 "LET body")
    (expect-same-type
     (verify-hir-node (first (hir-children node)) body-environment
                      signatures pointer-bits)
     (hir-type node) "LET result")))

(defun verify-hir-call (node types signatures)
  (let ((signature (gethash (hir-value node) signatures)))
    (unless signature (fail "HIR call has unknown callee ~A" (hir-value node)))
    (unless (equal types (signature-arguments signature))
      (fail "HIR call argument types do not match ~A" (hir-value node)))
    (expect-same-type (hir-type node) (signature-result signature)
                      "call result")))

(defun verify-hir-memory (node types)
  (case (hir-kind node)
    (:load
     (expect-count types 1 "load")
     (unless (and (pointer-type-p (first types))
                  (let ((type (pointed-type (first types))))
                    (or (integer-type-p type) (float-type-p type)
                        (pointer-type-p type))))
       (fail "load needs a pointer to a scalar machine value"))
     (expect-same-type (hir-type node) (pointed-type (first types))
                       "load result"))
    (:store
     (expect-count types 2 "store")
     (unless (and (pointer-type-p (first types))
                  (let ((type (pointed-type (first types))))
                    (or (integer-type-p type) (float-type-p type)
                        (pointer-type-p type))))
       (fail "store needs a pointer to a scalar machine value"))
     (when (pointer-const-p (first types))
       (fail "store through a const pointer"))
     (expect-same-type (second types) (pointed-type (first types))
                       "store value")
     (expect-same-type (hir-type node) (second types) "store result"))
    (:pointer-add
     (expect-count types 2 "pointer addition")
     (unless (and (pointer-type-p (first types))
                  (eq (second types) :isize)
                  (integerp (hir-value node))
                  (plusp (hir-value node)))
       (fail "invalid HIR pointer addition"))
     (expect-same-type (hir-type node) (first types) "pointer result"))
    (:field-pointer
     (expect-count types 1 "field pointer")
     (unless (and (pointer-type-p (first types))
                  (pointer-type-p (hir-type node))
                  (integerp (hir-value node))
                  (<= 0 (hir-value node)))
       (fail "invalid HIR field pointer"))
     (unless (and (eq (pointer-const-p (first types))
                      (pointer-const-p (hir-type node)))
                  (eq (pointer-volatile-p (first types))
                      (pointer-volatile-p (hir-type node))))
       (fail "HIR field pointer lost its qualifiers")))
    (:pointer-cast
     (expect-count types 1 "pointer cast")
     (unless (and (pointer-type-p (hir-type node))
                  (or (pointer-type-p (first types))
                      (eq (first types) :usize)))
       (fail "invalid HIR pointer cast")))))

(defun verify-hir-node (node environment signatures pointer-bits)
  (unless (hir-p node) (fail "expected a HIR node"))
  (let ((*source-location* (or (hir-source node) *source-location*)))
    (unless (valid-type-p (hir-type node))
      (fail "invalid HIR type ~S" (hir-type node)))
    (case (hir-kind node)
      (:literal
       (unless (literal-fits-p (hir-value node) (hir-type node)
                               pointer-bits)
         (fail "HIR literal does not fit ~S" (hir-type node))))
      (:variable
       (let ((entry (assoc (hir-value node) environment :test #'equal)))
         (unless entry (fail "unknown HIR variable ~A" (hir-value node)))
         (expect-same-type (hir-type node) (cdr entry) "variable")))
      (:progn
       (let ((types (verify-hir-children node environment signatures pointer-bits)))
         (unless types (fail "empty HIR PROGN"))
         (expect-same-type (hir-type node) (car (last types)) "PROGN result")))
      (:let (verify-hir-let node environment signatures pointer-bits))
      (:if
       (let ((types (verify-hir-children node environment signatures pointer-bits)))
         (expect-count types 3 "IF")
         (expect-same-type (second types) (third types) "IF branches")
         (expect-same-type (hir-type node) (second types) "IF result")))
      (:binary
       (verify-hir-binary
        node (verify-hir-children node environment signatures pointer-bits)))
      (:call
       (verify-hir-call
        node (verify-hir-children node environment signatures pointer-bits)
        signatures))
      (:data-address
       (unless (and (consp (hir-value node))
                    (stringp (car (hir-value node)))
                    (pointer-type-p (hir-type node))
                    (equal (pointed-type (hir-type node))
                           (cdr (hir-value node))))
         (fail "invalid HIR data address")))
      ((:load :store :pointer-add :field-pointer :pointer-cast)
       (verify-hir-memory
        node (verify-hir-children node environment signatures pointer-bits)))
      (otherwise (fail "unknown HIR node kind ~S" (hir-kind node))))
    (hir-type node)))

(defun verify-hir-function (function signatures pointer-bits)
  (unless (function-def-p function) (fail "expected a HIR function"))
  (let* ((*source-location* (function-def-source function))
         (signature (function-def-signature function))
         (parameters (function-def-parameters function)))
    (unless (= (length parameters) (length (signature-arguments signature)))
      (fail "HIR parameter count mismatch in ~A" (signature-name signature)))
    (loop for parameter in parameters
          for type in (signature-arguments signature)
          do (unless (stringp (car parameter))
               (fail "HIR parameter name must be a string"))
             (expect-same-type (cdr parameter) type "parameter"))
    (expect-same-type
     (verify-hir-node (function-def-body function) parameters
                      signatures pointer-bits)
     (signature-result signature) "function result"))
  t)
