(in-package #:psl.ir)

(defun reachable-blocks (function)
  (let ((seen (make-hash-table))
        (pending (list (ssa-function-entry function))))
    (loop while pending
          for id = (pop pending)
          unless (gethash id seen)
            do (setf (gethash id seen) t)
               (dolist (successor (block-successors (find-block function id)))
                 (push successor pending)))
    seen))

(defun verify-ssa-structure (function)
  (let ((blocks (ssa-function-blocks function))
        (ids (make-hash-table))
        (values (make-hash-table)))
    (unless blocks (fail "SSA function has no blocks"))
    (dolist (block blocks)
      (unless (and (integerp (ssa-block-id block))
                   (<= 0 (ssa-block-id block)))
        (fail "invalid SSA block id"))
      (when (gethash (ssa-block-id block) ids)
        (fail "duplicate SSA block ~D" (ssa-block-id block)))
      (setf (gethash (ssa-block-id block) ids) t)
      (unless (ssa-block-terminator block)
        (fail "SSA block ~D lacks a terminator" (ssa-block-id block)))
      (dolist (instruction (ssa-block-instructions block))
        (let ((id (ssa-instruction-id instruction)))
          (unless (and (integerp id) (<= 0 id)
                       (< id (ssa-function-next-value function)))
            (fail "SSA value id is out of range"))
          (when (gethash id values) (fail "duplicate SSA value ~D" id))
          (setf (gethash id values) t))))
    (unless (gethash (ssa-function-entry function) ids)
      (fail "SSA entry block is missing"))
    (dolist (block blocks)
      (let ((terminator (ssa-block-terminator block)))
        (case (ssa-terminator-op terminator)
          (:return
           (expect-count (ssa-terminator-args terminator) 1 "SSA return")
           (expect-count (ssa-terminator-targets terminator) 0 "SSA return targets"))
          (:jump
           (expect-count (ssa-terminator-args terminator) 0 "SSA jump")
           (expect-count (ssa-terminator-targets terminator) 1 "SSA jump target"))
          (:branch
           (expect-count (ssa-terminator-args terminator) 1 "SSA branch")
           (expect-count (ssa-terminator-targets terminator) 2 "SSA branch targets"))
          (otherwise (fail "invalid SSA terminator ~S"
                           (ssa-terminator-op terminator))))
        (dolist (target (ssa-terminator-targets terminator))
          (unless (gethash target ids)
            (fail "SSA branch targets missing block ~S" target)))))
    (let ((reachable (reachable-blocks function)))
      (dolist (block blocks)
        (unless (gethash (ssa-block-id block) reachable)
          (fail "unreachable SSA block ~D" (ssa-block-id block))))))
  t)

(defun compute-dominators (function)
  (let* ((ids (mapcar #'ssa-block-id (ssa-function-blocks function)))
         (entry (ssa-function-entry function))
         (dominators (make-hash-table)))
    (dolist (id ids)
      (setf (gethash id dominators)
            (if (= id entry) (list id) (copy-list ids))))
    (loop with changed = t
          while changed
          do (setf changed nil)
             (dolist (id ids)
               (unless (= id entry)
                 (let* ((predecessors (block-predecessors function id))
                        (shared (copy-list (gethash (first predecessors)
                                                    dominators))))
                   (unless predecessors
                     (fail "SSA block ~D has no predecessor" id))
                   (dolist (predecessor (rest predecessors))
                     (setf shared (intersection shared
                                                (gethash predecessor dominators))))
                   (let ((new (cons id shared)))
                     (unless (set-equal new (gethash id dominators))
                       (setf (gethash id dominators) new
                             changed t)))))))
    dominators))

(defun set-equal (left right)
  (and (null (set-difference left right))
       (null (set-difference right left))))

(defun definition-sites (function)
  (let ((sites (make-hash-table)))
    (dolist (block (ssa-function-blocks function))
      (loop for instruction in (ssa-block-instructions block)
            for index from 0
            do (setf (gethash (ssa-instruction-id instruction) sites)
                     (cons (ssa-block-id block) index))))
    sites))

(defun verify-ssa-use (value block index sites dominators)
  (let ((site (gethash value sites)))
    (unless site (fail "SSA uses undefined value ~S" value))
    (if (= (car site) block)
        (unless (< (cdr site) index)
          (fail "SSA value ~D is used before its definition" value))
        (unless (member (car site) (gethash block dominators))
          (fail "SSA value ~D does not dominate its use" value)))))

(defun verify-ssa-phi (instruction block function sites dominators)
  (let* ((incoming (ssa-instruction-args instruction))
         (predecessors (block-predecessors function (ssa-block-id block))))
    (unless (and (= (length incoming) (length predecessors))
                 (set-equal (mapcar #'car incoming) predecessors))
      (fail "SSA phi inputs do not match predecessors of block ~D"
            (ssa-block-id block)))
    (dolist (edge incoming)
      (let ((site (gethash (cdr edge) sites)))
        (unless site (fail "SSA phi uses undefined value ~S" (cdr edge)))
        (unless (or (= (car site) (car edge))
                    (member (car site) (gethash (car edge) dominators)))
          (fail "SSA phi input ~D does not dominate predecessor ~D"
                (cdr edge) (car edge)))))))

(defun verify-ssa-dominance (function)
  (let ((sites (definition-sites function))
        (dominators (compute-dominators function)))
    (dolist (block (ssa-function-blocks function))
      (let ((non-phi-seen nil))
        (loop for instruction in (ssa-block-instructions block)
              for index from 0
              do (let ((*source-location*
                         (or (ssa-instruction-source instruction)
                             *source-location*)))
                   (if (eq (ssa-instruction-op instruction) :phi)
                       (progn
                         (when non-phi-seen
                           (fail "SSA phi must precede ordinary instructions"))
                         (verify-ssa-phi instruction block function
                                         sites dominators))
                       (progn
                         (setf non-phi-seen t)
                         (dolist (value (ssa-instruction-args instruction))
                           (verify-ssa-use value (ssa-block-id block) index
                                           sites dominators))))))
        (dolist (value (ssa-terminator-args (ssa-block-terminator block)))
          (verify-ssa-use value (ssa-block-id block)
                          (length (ssa-block-instructions block))
                          sites dominators)))))
  t)

(defun ssa-value-type (id definitions)
  (let ((instruction (gethash id definitions)))
    (unless instruction (fail "SSA uses undefined value ~S" id))
    (ssa-instruction-type instruction)))

(defun verify-ssa-binary (instruction types)
  (expect-count types 2 "SSA binary operation")
  (let* ((operation (ssa-instruction-value instruction))
         (operator (car operation))
         (operand-type (cdr operation)))
    (unless (member operator '("wrap+" "wrap-" "wrap*" "=" "<")
                    :test #'equal)
      (fail "unknown SSA binary operator ~S" operator))
    (unless (integer-type-p operand-type)
      (fail "SSA binary operand type is not an integer"))
    (dolist (type types)
      (expect-same-type type operand-type "SSA binary operand"))
    (expect-same-type
     (ssa-instruction-type instruction)
     (if (member operator '("=" "<") :test #'equal)
         :boolean operand-type)
     "SSA binary result")))

(defun verify-ssa-call (instruction types signatures)
  (let ((signature (gethash (ssa-instruction-value instruction) signatures)))
    (unless signature
      (fail "SSA call has unknown callee ~A" (ssa-instruction-value instruction)))
    (unless (equal types (signature-arguments signature))
      (fail "SSA call arguments do not match ~A" (signature-name signature)))
    (expect-same-type (ssa-instruction-type instruction)
                      (signature-result signature) "SSA call result")))

(defun verify-ssa-memory (instruction types)
  (let ((type (ssa-instruction-type instruction)))
    (case (ssa-instruction-op instruction)
      (:load
       (expect-count types 1 "SSA load")
       (unless (and (pointer-type-p (first types))
                    (integer-type-p (pointed-type (first types))))
         (fail "SSA load needs a pointer to a machine integer"))
       (expect-same-type type (pointed-type (first types)) "SSA load result")
       (unless (eq (ssa-instruction-value instruction)
                   (pointer-volatile-p (first types)))
         (fail "SSA load volatile flag does not match pointer")))
      (:store
       (expect-count types 2 "SSA store")
       (unless (and (pointer-type-p (first types))
                    (integer-type-p (pointed-type (first types))))
         (fail "SSA store needs a pointer to a machine integer"))
       (when (pointer-const-p (first types))
         (fail "SSA store through const pointer"))
       (expect-same-type (second types) (pointed-type (first types))
                         "SSA store value")
       (expect-same-type type (second types) "SSA store result"))
      (:pointer-add
       (expect-count types 2 "SSA pointer addition")
       (unless (and (pointer-type-p (first types))
                    (eq (second types) :isize)
                    (integerp (ssa-instruction-value instruction))
                    (plusp (ssa-instruction-value instruction)))
         (fail "invalid SSA pointer addition"))
       (expect-same-type type (first types) "SSA pointer result"))
      (:field-pointer
       (expect-count types 1 "SSA field pointer")
       (unless (and (pointer-type-p (first types))
                    (pointer-type-p type)
                    (integerp (ssa-instruction-value instruction))
                    (<= 0 (ssa-instruction-value instruction)))
         (fail "invalid SSA field pointer"))
       (unless (and (eq (pointer-const-p (first types))
                        (pointer-const-p type))
                    (eq (pointer-volatile-p (first types))
                        (pointer-volatile-p type)))
         (fail "SSA field pointer lost its qualifiers")))
      (:cast
       (expect-count types 1 "SSA pointer cast")
       (unless (and (pointer-type-p type)
                    (or (pointer-type-p (first types))
                        (eq (first types) :usize)))
         (fail "invalid SSA pointer cast"))))))

(defun verify-ssa-instruction (instruction function definitions
                               signatures pointer-bits block-id)
  (let* ((*source-location* (or (ssa-instruction-source instruction)
                                *source-location*))
         (op (ssa-instruction-op instruction))
         (type (ssa-instruction-type instruction))
         (types (mapcar (lambda (id) (ssa-value-type id definitions))
                        (if (eq op :phi)
                            (mapcar #'cdr (ssa-instruction-args instruction))
                            (ssa-instruction-args instruction)))))
    (unless (valid-type-p type) (fail "invalid SSA type ~S" type))
    (case op
      (:argument
       (expect-count types 0 "SSA argument")
       (unless (= block-id (ssa-function-entry function))
         (fail "SSA argument must be in entry block"))
       (let ((index (ssa-instruction-value instruction))
             (parameters (signature-arguments (ssa-function-signature function))))
         (unless (and (integerp index) (<= 0 index) (< index (length parameters)))
           (fail "SSA argument index is out of range"))
         (expect-same-type type (nth index parameters) "SSA argument")))
      (:constant
       (expect-count types 0 "SSA constant")
       (unless (if (eq type :boolean)
                   (member (ssa-instruction-value instruction) '(0 1))
                   (integer-fits-p (ssa-instruction-value instruction)
                                   type pointer-bits))
         (fail "SSA constant does not fit ~S" type)))
      (:phi
       (dolist (incoming-type types)
         (expect-same-type incoming-type type "SSA phi input")))
      (:copy
       (expect-count types 1 "SSA copy")
       (expect-same-type type (first types) "SSA copy"))
      (:binary (verify-ssa-binary instruction types))
      (:call (verify-ssa-call instruction types signatures))
      ((:load :store :pointer-add :field-pointer :cast)
       (verify-ssa-memory instruction types))
      (otherwise (fail "unknown SSA instruction ~S" op)))))

(defun verify-ssa-terminator (block function definitions)
  (let* ((terminator (ssa-block-terminator block))
         (*source-location* (or (ssa-terminator-source terminator)
                                *source-location*))
         (args (ssa-terminator-args terminator)))
    (case (ssa-terminator-op terminator)
      (:return
       (expect-same-type
        (ssa-value-type (first args) definitions)
        (signature-result (ssa-function-signature function)) "SSA return"))
      (:branch
       (expect-same-type (ssa-value-type (first args) definitions)
                         :boolean "SSA branch condition"))
      (:jump nil))))

(defun verify-ssa-function (function signatures pointer-bits)
  (unless (ssa-function-p function) (fail "expected an SSA function"))
  (unless (equal (ssa-function-name function)
                 (signature-name (ssa-function-signature function)))
    (fail "SSA function name differs from signature"))
  (verify-ssa-structure function)
  (let ((definitions (ssa-definitions function)))
    (dolist (block (ssa-function-blocks function))
      (dolist (instruction (ssa-block-instructions block))
        (verify-ssa-instruction instruction function definitions signatures
                                pointer-bits (ssa-block-id block)))
      (verify-ssa-terminator block function definitions)))
  (verify-ssa-dominance function)
  t)
