(include "float_bigint.lisp")

(defcstruct native_float_parser
  (numerator native_float_uint)
  (denominator native_float_uint)
  (digits usize)
  (fractional usize)
  (discarded usize)
  (exponent s64)
  (code u32)
  (negative u8)
  (sticky u8)
  (saw_digit u8)
  (saw_point u8)
  (saw_marker u8)
  (status c-int)
  (cursor usize))

(defun source_float_code_p (code)
  (declare (type u32 code) (returns c-int))
  (if (= code 13) 1 (if (= code 14) 1 0)))

(defun float_marker_code (byte)
  (declare (type u8 byte) (returns u32))
  (let ((letter (bits-and byte 223)))
    (cond ((= letter 68) 14) ((= letter 76) 14)
          ((= letter 69) 13) ((= letter 70) 13) ((= letter 83) 13)
          (t 0))))

(defun float_parser_initialize (state numerator denominator capacity)
  (declare (type (ptr native_float_parser) state)
           (type (ptr u32) numerator denominator) (type usize capacity)
           (returns c-int))
  (float_uint_initialize (field-pointer state 'numerator) numerator capacity 0)
  (float_uint_initialize (field-pointer state 'denominator) denominator capacity 1)
  (store (field-pointer state 'digits) 0)
  (store (field-pointer state 'fractional) 0)
  (store (field-pointer state 'discarded) 0)
  (store (field-pointer state 'exponent) 0)
  (store (field-pointer state 'code) 13)
  (store (field-pointer state 'negative) 0)
  (store (field-pointer state 'sticky) 0)
  (store (field-pointer state 'saw_digit) 0)
  (store (field-pointer state 'saw_point) 0)
  (store (field-pointer state 'saw_marker) 0)
  (store (field-pointer state 'status) 0)
  (store (field-pointer state 'cursor) 0)
  1)

(defun float_decimal_digit (byte)
  (declare (type u8 byte) (returns c-int))
  (if (< byte 48) 0 (if (< byte 58) 1 0)))

;; Every binary32/binary64 rounding midpoint has a terminating decimal
;; expansion with fewer than 800 significant digits. Retaining that prefix
;; and a sticky bit therefore preserves which side of any midpoint it lies on.
(defun float_accumulate_digit (state digit)
  (declare (type (ptr native_float_parser) state) (type u32 digit)
           (returns c-int))
  (store (field-pointer state 'saw_digit) 1)
  (if (= (deref (field-pointer state 'saw_point)) 1)
      (store (field-pointer state 'fractional)
             (wrap+ (deref (field-pointer state 'fractional)) 1)) (wrap-cast usize 0))
  (let ((kept (deref (field-pointer state 'digits))))
    (if (= kept 0)
        (if (= digit 0) 1
            (progn
              (store (field-pointer state 'digits) 1)
              (float_uint_multiply_add (field-pointer state 'numerator) 10 digit)))
        (if (< kept 800)
            (progn
              (store (field-pointer state 'digits) (wrap+ kept 1))
              (float_uint_multiply_add (field-pointer state 'numerator) 10 digit))
            (progn
              (store (field-pointer state 'discarded)
                     (wrap+ (deref (field-pointer state 'discarded)) 1))
              (if (= digit 0) (wrap-cast u8 0) (store (field-pointer state 'sticky) 1))
              1)))))

(defun float_exponent_digit (state data end limit)
  (declare (type (ptr native_float_parser) state) (type (ptr u8) data)
           (type usize end) (type u64 limit) (returns c-int))
  (let ((index (deref (field-pointer state 'cursor))))
    (let ((byte (deref (pointer+ data (wrap-cast isize index)))))
      (if (= (float_decimal_digit byte) 0)
          (progn (store (field-pointer state 'status) 0)
                 (store (field-pointer state 'cursor) end) 0)
          (let ((next (wrap+ (wrap* (wrap-cast u64 (deref (field-pointer state 'exponent))) 10)
                             (wrap-cast u64 (wrap- byte 48)))))
            (store (field-pointer state 'exponent)
                   (wrap-cast s64 (if (< limit next) limit next)))
            (store (field-pointer state 'cursor) (wrap+ index 1))
            1)))))

(defun float_parse_exponent (state data index end)
  (declare (type (ptr native_float_parser) state) (type (ptr u8) data)
           (type usize index end) (returns c-int))
  (if (= index end) 0
      (let ((first (deref (pointer+ data (wrap-cast isize index)))))
        (let ((digits (if (= first 43) (wrap+ index 1)
                          (if (= first 45) (wrap+ index 1) index))))
          (if (= digits end) 0
              (progn
                (store (field-pointer state 'cursor) digits)
                (store (field-pointer state 'status) 1)
                (while (< (deref (field-pointer state 'cursor)) end)
                  (float_exponent_digit state data end (wrap+ (wrap-cast u64 end) 1024)))
                (if (= first 45)
                    (store (field-pointer state 'exponent)
                           (wrap- 0 (deref (field-pointer state 'exponent))))
                    (wrap-cast s64 0))
                (deref (field-pointer state 'status))))))))

(defun float_scan_mantissa_character (state data end)
  (declare (type (ptr native_float_parser) state) (type (ptr u8) data)
           (type usize end) (returns c-int))
  (let ((index (deref (field-pointer state 'cursor))))
    (let ((byte (deref (pointer+ data (wrap-cast isize index)))))
      (cond
        ((= (float_decimal_digit byte) 1)
         (let ((valid (float_accumulate_digit state (wrap-cast u32 (wrap- byte 48)))))
           (store (field-pointer state 'cursor) (wrap+ index 1))
           valid))
        ((if (= byte 46) (= (deref (field-pointer state 'saw_point)) 0) nil)
         (store (field-pointer state 'saw_point) 1)
         (store (field-pointer state 'cursor) (wrap+ index 1))
         1)
        (t
         (store (field-pointer state 'saw_marker) 1)
         (let ((code (float_marker_code byte)))
           (store (field-pointer state 'status)
                  (if (= code 0) 0
                      (if (= (deref (field-pointer state 'saw_digit)) 0) 0
                          (progn (store (field-pointer state 'code) code)
                                 (float_parse_exponent state data (wrap+ index 1) end)))))
           (store (field-pointer state 'cursor) end)
           (deref (field-pointer state 'status))))))))

(defun float_parse_mantissa (state data index end)
  (declare (type (ptr native_float_parser) state) (type (ptr u8) data)
           (type usize index end) (returns c-int))
  (store (field-pointer state 'cursor) index)
  (while (< (deref (field-pointer state 'cursor)) end)
    (float_scan_mantissa_character state data end))
  (if (= (deref (field-pointer state 'saw_marker)) 1)
      (deref (field-pointer state 'status))
      (if (= (deref (field-pointer state 'saw_digit)) 0) 0
          (if (= (deref (field-pointer state 'saw_point)) 1)
              (if (= (deref (field-pointer state 'fractional)) 0) 0 1) 0))))

(defun float_decimal_exponent (state)
  (declare (type (ptr native_float_parser) state) (returns s64))
  (wrap- (wrap+ (deref (field-pointer state 'exponent))
                 (wrap-cast s64 (deref (field-pointer state 'discarded))))
          (wrap-cast s64 (deref (field-pointer state 'fractional)))))

