(include "package_forms_types.lisp")
(include "environment/operations.lisp")
(include "identity_syntax.lisp")
(include "source.lisp")
(defun native_package_fail (state error)
  (declare (type (ptr native_package_context) state) (type u32 error)
           (returns c-int))
  (if (= (deref (field-pointer state 'error)) 0)
      (store (field-pointer state 'error) error) (wrap-cast u32 0))
  0)

(defun native_package_symbol_name (state reference)
  (declare (type (ptr native_package_context) state) (type usize reference)
           (returns c-int))
  (let ((parser (deref (field-pointer state 'parser)))
        (env (deref (field-pointer state 'environment))))
    (let ((symbol (ast_symbol_identity parser reference)))
      (if (= symbol 0) (native_package_fail state 4)
          (let ((definition (native_ct_symbol_at env symbol)))
            (store (field-pointer state 'offset) (deref (field-pointer definition 'name)))
            (store (field-pointer state 'length) (deref (field-pointer definition 'length)))
            (store (field-pointer state 'name) (native_ct_symbol_name env symbol))
            1)))))

(defun native_package_string_name (state reference)
  (declare (type (ptr native_package_context) state) (type usize reference)
           (returns c-int))
  (let ((parser (deref (field-pointer state 'parser)))
        (env (deref (field-pointer state 'environment))))
    (let ((node (parser_node parser reference)))
      (let ((start (wrap+ (deref (field-pointer node 'start)) 1))
            (end (wrap- (wrap+ (deref (field-pointer node 'start))
                               (deref (field-pointer node 'length))) 1))
            (offset (deref (field-pointer env 'name_count))))
        (let ((length (source_string_decoded_size (deref (field-pointer state 'source)) start end 0)))
          (if (= (native_ct_names_room_p env (wrap+ length 1)) 0)
              (native_package_fail state 1)
              (progn
                (store (field-pointer state 'offset) offset)
                (store (field-pointer state 'length) length)
                (store (field-pointer state 'name)
                       (pointer+ (deref (field-pointer env 'names)) (wrap-cast isize offset)))
                (if (= (source_string_copy (deref (field-pointer state 'source)) start end
                                          (deref (field-pointer state 'name)) 0) 1) 1
                    (native_package_fail state 8)))))))))

(defun native_package_name (state reference)
  (declare (type (ptr native_package_context) state) (type usize reference)
           (returns c-int))
  (let ((parser (deref (field-pointer state 'parser))))
    (if (= reference 0) (native_package_fail state 4)
        (if (= (deref (field-pointer (parser_node parser reference) 'kind)) 7)
            (native_package_string_name state reference)
            (native_package_symbol_name state reference)))))

(defun native_package_find_designator (state reference)
  (declare (type (ptr native_package_context) state) (type usize reference)
           (returns usize))
  (if (= (native_package_name state reference) 0) 0
      (native_ct_find_package (deref (field-pointer state 'environment))
          (deref (field-pointer state 'name)) (deref (field-pointer state 'length)))))
