(include "reader.lisp")

;; References are one-based indices into a caller-owned node arena. Zero means
;; no node, so the parser never embeds host pointers in the syntax tree.
(defcstruct psl_ast_node
  (kind u32)
  (start usize)
  (length usize)
  (first usize)
  (last usize)
  (next usize))

(defcstruct psl_parser
  (scanner (ptr psl_scanner))
  (token (ptr psl_token))
  (has_token u8)
  (nodes (ptr psl_ast_node))
  (count usize)
  (capacity usize)
  (error u32))

(defun parser_node (parser reference)
  (declare (type (ptr psl_parser) parser)
           (type usize reference)
           (returns (ptr psl_ast_node)))
  (pointer+ (deref (field-pointer parser 'nodes))
            (wrap-cast isize (wrap- reference 1))))

(defun parser_peek (parser)
  (declare (type (ptr psl_parser) parser) (returns u32))
  (if (= (deref (field-pointer parser 'has_token)) 0)
      (progn
        (store (field-pointer parser 'has_token) 1)
        (let ((kind (scan_next (deref (field-pointer parser 'scanner))
                               (deref (field-pointer parser 'token)))))
          (if (= kind 255)
              (progn (store (field-pointer parser 'error) 1) kind)
              kind)))
      (deref (field-pointer (deref (field-pointer parser 'token)) 'kind))))

(defun parser_consume (parser)
  (declare (type (ptr psl_parser) parser) (returns u8))
  (store (field-pointer parser 'has_token) 0))

(defun parser_new_node (parser kind start length)
  (declare (type (ptr psl_parser) parser)
           (type u32 kind)
           (type usize start length)
           (returns usize))
  (let ((count (deref (field-pointer parser 'count)))
        (capacity (deref (field-pointer parser 'capacity))))
    (if (< count capacity)
        (let ((reference (wrap+ count 1)))
          (let ((node (parser_node parser reference)))
            (store (field-pointer node 'kind) kind)
            (store (field-pointer node 'start) start)
            (store (field-pointer node 'length) length)
            (store (field-pointer node 'first) 0)
            (store (field-pointer node 'last) 0)
            (store (field-pointer node 'next) 0)
            (store (field-pointer parser 'count) reference)
            reference))
        (progn (store (field-pointer parser 'error) 4) 0))))

(defun parser_append (parser parent-reference child-reference)
  (declare (type (ptr psl_parser) parser)
           (type usize parent-reference child-reference)
           (returns usize))
  (if (= child-reference 0)
      0
      (let ((parent (parser_node parser parent-reference)))
        (let ((last (deref (field-pointer parent 'last))))
          (if (= last 0)
              (store (field-pointer parent 'first) child-reference)
              (store (field-pointer (parser_node parser last) 'next)
                     child-reference)))
        (store (field-pointer parent 'last) child-reference)
        child-reference)))

(defun parser_list_more_p (parser)
  (declare (type (ptr psl_parser) parser) (returns c-int))
  (if (= (deref (field-pointer parser 'error)) 0)
      (let ((kind (parser_peek parser)))
        (if (= kind 2)
            0
            (if (= kind 0)
                (progn (store (field-pointer parser 'error) 3) 0)
                (if (= kind 255) 0 1))))
      0))

(defun parser_list (parser start)
  (declare (type (ptr psl_parser) parser)
           (type usize start)
           (returns usize))
  (let ((reference (parser_new_node parser 1 start 0)))
    (if (= reference 0)
        0
        (progn
          (while (= (parser_list_more_p parser) 1)
            (parser_append parser reference (parser_next parser)))
          (if (= (deref (field-pointer parser 'error)) 0)
              (progn
                (parser_consume parser)
                (store
                 (field-pointer (parser_node parser reference) 'length)
                 (wrap-
                  (deref (field-pointer
                          (deref (field-pointer parser 'scanner)) 'cursor))
                  start))
                reference)
              0)))))

(defun parser_prefix (parser kind start length)
  (declare (type (ptr psl_parser) parser)
           (type u32 kind)
           (type usize start length)
           (returns usize))
  (let ((reference (parser_new_node parser kind start length)))
    (if (= reference 0)
        0
        (if (= (parser_append parser reference (parser_next parser)) 0)
            (progn
              (if (= (deref (field-pointer parser 'error)) 0)
                  (store (field-pointer parser 'error) 3)
                  (wrap-cast u32 0))
              0)
            reference))))

(defun parser_form (parser kind start length)
  (declare (type (ptr psl_parser) parser)
           (type u32 kind)
           (type usize start length)
           (returns usize))
  (cond
    ((= kind 1) (parser_list parser start))
    ((= kind 2) (store (field-pointer parser 'error) 2) 0)
    ((= kind 3) (parser_prefix parser kind start length))
    ((= kind 4) (parser_prefix parser kind start length))
    ((= kind 5) (parser_prefix parser kind start length))
    ((= kind 6) (parser_prefix parser kind start length))
    ((= kind 9) (parser_prefix parser kind start length))
    (t (parser_new_node parser kind start length))))

(defun parser_next (parser)
  (declare (type (ptr psl_parser) parser)
           (returns usize)
           (c-export :c))
  (if (= (deref (field-pointer parser 'error)) 0)
      (let ((kind (parser_peek parser)))
        (if (= kind 0)
            0
            (if (= kind 255)
                0
                (let ((token (deref (field-pointer parser 'token))))
                  (let ((start (deref (field-pointer token 'start)))
                        (length (deref (field-pointer token 'length))))
                    (parser_consume parser)
                    (parser_form parser kind start length))))))
      0))
