(in-package #:psl.frontend)

(defun analyze-children (forms environment context)
  (mapcar (lambda (form) (analyze-expression form environment context)) forms))

(defun integer-bounds (type context)
  (let ((width (type-width type
                           (target-pointer-bits (analysis-context-target context)))))
    (unless width (fail "~S is not an integer type" type))
    (if (signed-type-p type)
        (values (- (ash 1 (1- width))) (1- (ash 1 (1- width))))
        (values 0 (1- (ash 1 width))))))

(defun analyze-literal (value context &optional expected)
  (let ((type (or expected (if (minusp value) :s64 :u64))))
    (multiple-value-bind (minimum maximum) (integer-bounds type context)
      (unless (<= minimum value maximum)
        (fail "integer literal ~S does not fit ~A" value type)))
    (make-hir :kind :literal :type type :value value)))

(defun analyze-variable (name environment)
  (let ((entry (assoc (source-name name) environment :test #'equal)))
    (unless entry (fail "unknown variable ~A" name))
    (make-hir :kind :variable :type (cdr entry) :value (car entry))))

(defun analyze-if (form environment context expected)
  (unless (= (length form) 4)
    (fail "IF requires condition, then, and else"))
  (let* ((parts (list (analyze-expression (second form) environment context)
                      (analyze-expression (third form) environment context expected)
                      (analyze-expression (fourth form) environment context expected)))
         (then (second parts))
         (otherwise (third parts)))
    (unless (equal (hir-type then) (hir-type otherwise))
      (fail "IF branches have different machine types"))
    (make-hir :kind :if :type (hir-type then) :children parts)))

(defun analyze-progn (forms environment context &optional expected)
  (unless forms (fail "empty PROGN is not supported"))
  (let ((parts (append (analyze-children (butlast forms) environment context)
                       (list (analyze-expression (car (last forms))
                                                 environment context expected)))))
    (make-hir :kind :progn :type (hir-type (car (last parts)))
              :children parts)))

(defun analyze-binding (binding environment context)
  (unless (and (listp binding) (= (length binding) 2)
               (symbolp (first binding)))
    (fail "invalid LET binding ~S" binding))
  (cons (source-name (first binding))
        (analyze-expression (second binding) environment context)))

(defun analyze-let (form environment context expected)
  (unless (and (listp (second form)) (cddr form))
    (fail "LET requires bindings and a body"))
  (let* ((bindings (mapcar (lambda (binding)
                             (analyze-binding binding environment context))
                           (second form)))
         (body-env (append (mapcar (lambda (binding)
                                     (cons (car binding) (hir-type (cdr binding))))
                                   bindings)
                           environment))
         (body (analyze-progn (cddr form) body-env context expected)))
    (make-hir :kind :let :type (hir-type body)
              :value bindings :children (list body))))

(defun binary-form-p (form)
  (or (some (lambda (name) (psl-form-p form name))
            '("wrap+" "wrap-" "wrap*"))
      (form-p form "=")
      (form-p form "<")))

(defun analyze-binary (form environment context expected)
  (unless (= (length form) 3)
    (fail "~A currently requires two operands" (first form)))
  (let* ((comparison (or (form-p form "=") (form-p form "<")))
         (operand-expected (unless comparison expected))
         (left-form (second form))
         (right-form (third form))
         (right-first (and (integerp left-form) (not (integerp right-form))))
         (first-node (analyze-expression (if right-first right-form left-form)
                                         environment context operand-expected))
         (second-node (analyze-expression (if right-first left-form right-form)
                                          environment context (hir-type first-node)))
         (parts (if right-first (list second-node first-node)
                    (list first-node second-node)))
         (left (first parts))
         (right (second parts))
         (operator (string-downcase (symbol-name (first form)))))
    (unless (equal (hir-type left) (hir-type right))
      (fail "operands of ~A have different machine types" operator))
    (unless (integer-type-p (hir-type left))
      (fail "~A requires machine integer operands" operator))
    (make-hir :kind :binary
              :type (if (member operator '("=" "<") :test #'equal)
                        :boolean (hir-type left))
              :value (cons operator (hir-type left)) :children parts)))

(defun analyze-call (form signature environment context)
  (let ((arguments
          (mapcar (lambda (source type)
                    (analyze-expression source environment context type))
                  (rest form) (signature-arguments signature))))
    (unless (= (length (rest form)) (length (signature-arguments signature)))
      (fail "argument count mismatch in call to ~A" (signature-name signature)))
    (unless (equal (mapcar #'hir-type arguments)
                   (signature-arguments signature))
      (fail "argument mismatch in call to ~A" (signature-name signature)))
    (make-hir :kind :call :type (signature-result signature)
              :value (signature-name signature) :children arguments)))

(defun analyze-ffi-call (form environment context)
  (unless (and (>= (length form) 2)
               (or (symbolp (second form)) (stringp (second form))))
    (fail "FFI:CALL requires an imported function name"))
  (let* ((name (source-name (second form)))
         (signature (gethash name (analysis-context-signatures context))))
    (unless (and signature (signature-external-p signature))
      (fail "FFI:CALL requires an imported function: ~A" name))
    (analyze-call (cons (second form) (cddr form)) signature
                  environment context)))

(defun quoted-designator (form)
  (unless (and (form-p form "quote") (= (length form) 2))
    (fail "expected a quoted type or field name, got ~S" form))
  (second form))

(defun analyze-layout-query (form context)
  (let ((operator (string-downcase (symbol-name (first form)))))
    (unless (= (length form) (if (equal operator "offset-of") 3 2))
      (fail "wrong number of operands for ~A" operator))
    (let* ((type (type-name (quoted-designator (second form)) context))
           (value
             (cond
               ((equal operator "sizeof") (type-size type context))
               ((equal operator "alignof") (type-alignment type context))
               (t (field-layout-offset
                   (find-structure-field type
                                         (source-name
                                          (quoted-designator (third form)))
                                         context))))))
      (make-hir :kind :literal :type :usize :value value))))

(defun analyze-field-pointer (form environment context)
  (unless (= (length form) 3)
    (fail "field-pointer requires a pointer and quoted field name"))
  (let ((pointer (analyze-expression (second form) environment context)))
    (unless (pointer-type-p (hir-type pointer))
      (fail "field-pointer requires a structure pointer"))
    (let* ((name (source-name (quoted-designator (third form))))
           (field (find-structure-field
                   (pointed-type (hir-type pointer)) name context)))
      (make-hir :kind :field-pointer
                :type (list :ptr (field-layout-type field)
                            (pointer-const-p (hir-type pointer))
                            (pointer-volatile-p (hir-type pointer)))
                :value (field-layout-offset field)
                :children (list pointer)))))

(defun analyze-pointer-add (form environment context)
  (unless (= (length form) 3)
    (fail "pointer+ requires a pointer and element offset"))
  (let ((pointer (analyze-expression (second form) environment context))
        (offset (analyze-expression (third form) environment context :isize)))
    (unless (pointer-type-p (hir-type pointer))
      (fail "pointer+ requires a raw pointer"))
    (unless (eq (hir-type offset) :isize)
      (fail "pointer+ offset must have type psl:isize"))
    (make-hir :kind :pointer-add :type (hir-type pointer)
              :value (type-size (pointed-type (hir-type pointer)) context)
              :children (list pointer offset))))

(defun analyze-load (form environment context)
  (unless (= (length form) 2) (fail "load requires one pointer"))
  (let ((pointer (analyze-expression (second form) environment context)))
    (unless (and (pointer-type-p (hir-type pointer))
                 (integer-type-p (pointed-type (hir-type pointer))))
      (fail "load requires a pointer to a machine integer"))
    (make-hir :kind :load :type (pointed-type (hir-type pointer))
              :children (list pointer))))

(defun analyze-store (form environment context)
  (unless (= (length form) 3) (fail "store requires pointer and value"))
  (let ((pointer (analyze-expression (second form) environment context)))
    (unless (and (pointer-type-p (hir-type pointer))
                 (integer-type-p (pointed-type (hir-type pointer))))
      (fail "store requires a pointer to a machine integer"))
    (when (pointer-const-p (hir-type pointer))
      (fail "cannot store through a const pointer"))
    (let* ((type (pointed-type (hir-type pointer)))
           (value (analyze-expression (third form) environment context type)))
      (unless (equal type (hir-type value))
        (fail "store value has the wrong type"))
      (make-hir :kind :store :type type :children (list pointer value)))))

(defun analyze-pointer-cast (form environment context from-address-p)
  (unless (= (length form) 3)
    (fail "pointer conversion requires type and value"))
  (let* ((type (type-name (second form) context))
         (value (analyze-expression (third form) environment context
                                    (when from-address-p :usize))))
    (unless (pointer-type-p type)
      (fail "pointer conversion destination must be a pointer type"))
    (unless (if from-address-p
                (eq (hir-type value) :usize)
                (pointer-type-p (hir-type value)))
      (fail "invalid source type for pointer conversion"))
    (make-hir :kind :pointer-cast :type type :children (list value))))

(defun analyze-expression (source environment context &optional expected)
  (let ((form (macroexpand source)))
    (cond
      ((eq form nil) (make-hir :kind :literal :type :boolean :value 0))
      ((eq form t) (make-hir :kind :literal :type :boolean :value 1))
      ((integerp form) (analyze-literal form context expected))
      ((symbolp form) (analyze-variable form environment))
      ((not (consp form)) (fail "unsupported expression ~S" form))
      ((form-p form "if") (analyze-if form environment context expected))
      ((form-p form "progn")
       (analyze-progn (rest form) environment context expected))
      ((form-p form "let") (analyze-let form environment context expected))
      ((or (psl-form-p form "sizeof") (psl-form-p form "alignof")
           (psl-form-p form "offset-of"))
       (analyze-layout-query form context))
      ((psl-form-p form "field-pointer")
       (analyze-field-pointer form environment context))
      ((psl-form-p form "pointer+")
       (analyze-pointer-add form environment context))
      ((or (psl-form-p form "load") (psl-form-p form "deref"))
       (analyze-load form environment context))
      ((psl-form-p form "store") (analyze-store form environment context))
      ((psl-form-p form "ptr-cast")
       (analyze-pointer-cast form environment context nil))
      ((psl-form-p form "ptr-from-address")
       (analyze-pointer-cast form environment context t))
      ((ffi-form-p form "call")
       (analyze-ffi-call form environment context))
      ((binary-form-p form) (analyze-binary form environment context expected))
      ((and (symbolp (first form))
            (gethash (source-name (first form))
                     (analysis-context-signatures context)))
       (let ((signature (gethash (source-name (first form))
                                 (analysis-context-signatures context))))
         (when (signature-external-p signature)
           (fail "call imported function ~A with FFI:CALL"
                 (signature-name signature)))
         (analyze-call form signature environment context)))
      (t (fail "unsupported form ~S" form)))))

(defun register-function (form context)
  (let ((external-p (or (psl-form-p form "extern-function")
                        (ffi-form-p form "import-function")))
        (ordinary-p (form-p form "defun")))
    (unless external-p
      (ensure-user-name (second form) "function"))
    (multiple-value-bind (signature parameters body)
        (if ordinary-p
            (parse-ordinary-defun form context)
            (parse-declaration form external-p context))
      (let ((name (signature-name signature)))
        (when (gethash name (analysis-context-signatures context))
          (fail "duplicate function declaration ~A" name))
        (when (> (length parameters) 6)
          (fail "more than six integer arguments are not implemented"))
        (unless (and (every (lambda (type)
                              (or (integer-type-p type) (pointer-type-p type)))
                            (signature-arguments signature))
                     (let ((type (signature-result signature)))
                       (or (integer-type-p type) (pointer-type-p type))))
          (fail "structure values are not yet supported by the C ABI"))
        (setf (gethash name (analysis-context-signatures context)) signature))
      (unless external-p
        (unless body (fail "function ~A has no body" (signature-name signature)))
        (list signature parameters body)))))

(defun register-c-source (form context)
  (unless (and (= (length form) 2)
               (stringp (second form))
               (equal (string-downcase (or (pathname-type (second form)) ""))
                      "c"))
    (fail "FFI:SOURCE requires a C source filename ending in .c"))
  (when (member (second form) (analysis-context-c-sources context)
                :test #'equal)
    (fail "duplicate FFI:SOURCE ~A" (second form)))
  (push (second form) (analysis-context-c-sources context)))

(defun analyze-definition (definition context)
  (destructuring-bind (signature parameters body) definition
    (let ((hir (analyze-progn body parameters context
                              (signature-result signature))))
      (unless (equal (hir-type hir) (signature-result signature))
        (fail "return type mismatch in ~A" (signature-name signature)))
      (make-function-def :signature signature :parameters parameters :body hir))))

(defun analyze-source (forms target)
  "Return typed HIR functions and all known function signatures."
  (let ((context (make-context target))
        (definitions (make-hash-table :test #'eq)))
    (dolist (form forms)
      (cond
        ((form-p form "defmacro")
         (ensure-user-name (second form) "macro"))
        ((ffi-form-p form "source") (register-c-source form context))
        ((psl-form-p form "defstruct/packed")
         (register-packed-structure form context))
        ((or (psl-form-p form "defun/c")
             (psl-form-p form "extern-function")
             (ffi-form-p form "import-function")
             (form-p form "defun"))
         (let ((definition (register-function form context)))
           (when definition (setf (gethash form definitions) definition))))
        (t (fail "unsupported top-level form ~S" form))))
    (let ((functions nil))
      (dolist (form forms)
        (cond
          ((form-p form "defmacro") (eval form))
          ((or (psl-form-p form "defun/c") (form-p form "defun"))
           (push (analyze-definition (gethash form definitions) context)
                 functions))))
      (values (nreverse functions)
              (analysis-context-signatures context)
              (nreverse (analysis-context-c-sources context))))))
