(in-package #:psl.frontend)

(defstruct field-layout name type offset)
(defstruct packed-layout name fields size alignment)
(defstruct analysis-context target signatures layouts c-sources)

(defun ensure-user-name (symbol kind)
  (unless (symbolp symbol)
    (fail "~A name must be a symbol" kind))
  (when (member (symbol-package symbol)
                (list (find-package :cl) (find-package :psl)
                      (find-package :ffi)))
    (fail "~A name ~A conflicts with a Common Lisp or compiler name"
          kind symbol)))

(defun make-context (target)
  (make-analysis-context :target target
                         :signatures (make-hash-table :test #'equal)
                         :layouts (make-hash-table :test #'equal)
                         :c-sources nil))

(defun type-size (type context)
  (cond
    ((integer-type-p type)
     (/ (type-width type (target-pointer-bits (analysis-context-target context)))
        8))
    ((pointer-type-p type)
     (/ (target-pointer-bits (analysis-context-target context)) 8))
    ((and (consp type) (eq (first type) :struct))
     (let ((layout (gethash (second type) (analysis-context-layouts context))))
       (unless layout (fail "unknown structure ~A" (second type)))
       (packed-layout-size layout)))
    (t (fail "type ~S has no fixed layout" type))))

(defun type-alignment (type context)
  (if (and (consp type) (eq (first type) :struct))
      (packed-layout-alignment
       (gethash (second type) (analysis-context-layouts context)))
      (type-size type context)))

(defun parse-layout-field (form offset context)
  (unless (and (listp form) (= (length form) 2) (symbolp (first form)))
    (fail "invalid structure field ~S" form))
  (let ((type (type-name (second form) context)))
    (values (make-field-layout :name (source-name (first form))
                               :type type :offset offset)
            (+ offset (type-size type context)))))

(defun register-packed-structure (form context)
  (unless (and (>= (length form) 3) (symbolp (second form)))
    (fail "expected (psl:defstruct/packed name (field type) ...)"))
  (ensure-user-name (second form) "structure")
  (let* ((name (source-name (second form)))
         (layouts (analysis-context-layouts context))
         (fields nil)
         (offset 0))
    (when (gethash name layouts) (fail "duplicate structure ~A" name))
    (dolist (field-form (cddr form))
      (multiple-value-bind (field next-offset)
          (parse-layout-field field-form offset context)
        (when (find (field-layout-name field) fields
                    :key #'field-layout-name :test #'equal)
          (fail "duplicate field ~A in ~A" (field-layout-name field) name))
        (push field fields)
        (setf offset next-offset)))
    (setf (gethash name layouts)
          (make-packed-layout :name name :fields (nreverse fields)
                              :size offset :alignment 1))))

(defun find-structure-field (type name context)
  (unless (and (consp type) (eq (first type) :struct))
    (fail "field access requires a pointer to a structure"))
  (let* ((layout (gethash (second type) (analysis-context-layouts context)))
         (field (find name (packed-layout-fields layout)
                      :key #'field-layout-name :test #'equal)))
    (unless field (fail "structure ~A has no field ~A" (second type) name))
    field))
