(in-package #:psl.frontend)

(defstruct field-layout name type offset)
(defstruct packed-layout name fields size alignment kind)
(defstruct analysis-context target profile signatures layouts c-sources data
           allocation-regions runtime-modules generated-functions
           runtime-signatures (lambda-counter 0) (string-counter 0))

(defun reserved-prefix-p (name prefix)
  (and (<= (length prefix) (length name))
       (string= prefix name :end2 (length prefix))))

(defun ensure-user-name (symbol kind)
  (unless (symbolp symbol)
    (fail "~A name must be a symbol" kind))
  (when (member (symbol-package symbol)
                (list (find-package :cl) (find-package :psl)
                      (find-package :ffi)))
    (fail "~A name ~A conflicts with a Common Lisp or compiler name"
          kind symbol))
  (let ((name (string-downcase (symbol-name symbol))))
    (when (or (reserved-prefix-p name "psl_rt_")
              (reserved-prefix-p name "psl_lambda_"))
      (fail "~A name ~A is reserved for generated code" kind symbol))))

(defun make-context (target profile)
  (make-analysis-context :target target :profile profile
                         :signatures (make-hash-table :test #'equal)
                         :runtime-signatures (make-hash-table :test #'equal)
                         :layouts (make-hash-table :test #'equal)
                         :c-sources nil))

(defun type-size (type context)
  (cond
    ((eq type :value) 8)
    ((or (integer-type-p type) (float-type-p type))
     (if (float-type-p type)
         (if (eq type :f32) 4 8)
         (/ (type-width type (target-pointer-bits (analysis-context-target context)))
            8)))
    ((pointer-type-p type)
     (/ (target-pointer-bits (analysis-context-target context)) 8))
    ((and (consp type) (eq (first type) :struct))
     (let ((layout (gethash (second type) (analysis-context-layouts context))))
       (unless layout (fail "unknown structure ~A" (second type)))
       (packed-layout-size layout)))
    (t (fail "type ~S has no fixed layout" type))))

(defun type-alignment (type context)
  (if (and (consp type) (eq (first type) :struct))
      (packed-layout-alignment
       (gethash (second type) (analysis-context-layouts context)))
      (type-size type context)))

(defun align-offset (offset alignment)
  (* alignment (ceiling offset alignment)))

(defun parse-layout-field (form offset context &optional c-layout-p)
  (unless (and (listp form) (= (length form) 2) (symbolp (first form)))
    (fail "invalid structure field ~S" form))
  (let* ((type (type-name (second form) context))
         (managed-p (eq type :value))
         (aligned-offset (if c-layout-p
                             (align-offset offset (type-alignment type context))
                             offset)))
    (when managed-p
      (fail "managed values require a traced runtime object, not a raw structure field"))
    (values (make-field-layout :name (source-name (first form))
                               :type type :offset aligned-offset)
            (+ aligned-offset (type-size type context)))))

(defun register-structure (form context c-layout-p)
  (unless (and (>= (length form) 3) (symbolp (second form)))
    (fail "expected structure name followed by typed fields"))
  (ensure-user-name (second form) "structure")
  (let* ((name (source-name (second form)))
         (layouts (analysis-context-layouts context))
         (fields nil)
         (offset 0)
         (alignment 1))
    (when (gethash name layouts) (fail "duplicate structure ~A" name))
    (dolist (field-form (cddr form))
      (multiple-value-bind (field next-offset)
          (parse-layout-field field-form offset context c-layout-p)
        (when (find (field-layout-name field) fields
                    :key #'field-layout-name :test #'equal)
          (fail "duplicate field ~A in ~A" (field-layout-name field) name))
        (push field fields)
        (when c-layout-p
          (setf alignment
                (max alignment (type-alignment (field-layout-type field)
                                               context))))
        (setf offset next-offset)))
    (setf (gethash name layouts)
          (make-packed-layout :name name :fields (nreverse fields)
                              :size (align-offset offset alignment)
                              :alignment alignment
                              :kind (if c-layout-p :c :packed)))))

(defun register-packed-structure (form context)
  (register-structure form context nil))

(defun register-c-structure (form context)
  (register-structure form context t))

(defun mark-c-aggregate-field (type offset context classes)
  (if (and (consp type) (eq (first type) :struct))
      (let ((layout (gethash (second type)
                             (analysis-context-layouts context))))
        (and layout (eq (packed-layout-kind layout) :c)
             (every (lambda (field)
                      (mark-c-aggregate-field
                       (field-layout-type field)
                       (+ offset (field-layout-offset field))
                       context classes))
                    (packed-layout-fields layout))))
      (let ((class (cond ((or (integer-type-p type) (pointer-type-p type))
                          :integer)
                         ((float-type-p type) :sse)))
            (size (type-size type context)))
        (when (and class (<= (+ (mod offset 8) size) 8))
          (let* ((index (floor offset 8))
                 (previous (aref classes index)))
            (setf (aref classes index)
                  (if (or (eq class :integer) (eq previous :integer))
                      :integer :sse)))
          t))))

(defun windows-c-aggregate-field-p (type context)
  (if (and (consp type) (eq (first type) :struct))
      (let ((layout (gethash (second type)
                             (analysis-context-layouts context))))
        (and layout (eq (packed-layout-kind layout) :c)
             (every (lambda (field)
                      (windows-c-aggregate-field-p
                       (field-layout-type field) context))
                    (packed-layout-fields layout))))
      (or (integer-type-p type) (pointer-type-p type)
          (float-type-p type))))

(defun c-leaf-fields (layout context)
  (loop for field in (packed-layout-fields layout)
        for type = (field-layout-type field)
        for offset = (field-layout-offset field)
        append (if (and (consp type) (eq (first type) :struct))
                   (let ((nested (gethash (second type)
                                          (analysis-context-layouts context))))
                     (unless (and nested (eq (packed-layout-kind nested) :c))
                       (fail "unsupported nested C aggregate ~S" type))
                     (loop for (part-offset . part-type)
                             in (c-leaf-fields nested context)
                           collect (cons (+ offset part-offset) part-type)))
                   (list (cons offset type)))))

(defun aapcs-aggregate-class (layout context)
  (let* ((leaves (c-leaf-fields layout context))
         (types (mapcar #'cdr leaves)))
    (when (and leaves
               (every (lambda (type)
                        (or (integer-type-p type) (pointer-type-p type)
                            (float-type-p type))) types))
      (if (and (<= (length leaves) 4)
               (float-type-p (first types))
               (every (lambda (type) (eq type (first types))) types))
          (list :hfa (first types) (mapcar #'car leaves))
          (list :general (packed-layout-size layout))))))

(defun riscv-aggregate-class (layout context)
  (let* ((leaves (c-leaf-fields layout context))
         (floats (count-if (lambda (field) (float-type-p (cdr field)))
                           leaves))
         (integers (count-if (lambda (field)
                               (or (integer-type-p (cdr field))
                                   (pointer-type-p (cdr field))))
                             leaves)))
    (when (and leaves (= (+ floats integers) (length leaves)))
      (if (or (and (= floats 1) (= integers 0))
              (and (= floats 2) (= integers 0))
              (and (= floats 1) (= integers 1)))
          (list :rv-fields leaves (packed-layout-size layout))
          (list :rv-general (packed-layout-size layout))))))

(defun c-aggregate-classes (type context)
  (let ((layout (and (consp type) (eq (first type) :struct)
                     (gethash (second type)
                              (analysis-context-layouts context)))))
    (when (and layout (eq (packed-layout-kind layout) :c)
               (<= 1 (packed-layout-size layout) 16))
      (cond
        ((eq (target-abi (analysis-context-target context)) :aapcs64)
         (aapcs-aggregate-class layout context))
        ((eq (target-abi (analysis-context-target context)) :lp64d)
         (riscv-aggregate-class layout context))
        ((eq (target-abi (analysis-context-target context)) :win64)
         (when (every (lambda (field)
                        (windows-c-aggregate-field-p
                         (field-layout-type field) context))
                      (packed-layout-fields layout))
           (list (if (member (packed-layout-size layout) '(1 2 4 8))
                     :win-direct :win-indirect)
                 (packed-layout-size layout))))
        (t
         (let ((classes (make-array (ceiling (packed-layout-size layout) 8)
                                    :initial-element nil)))
           (when (every (lambda (field)
                          (mark-c-aggregate-field
                           (field-layout-type field)
                           (field-layout-offset field) context classes))
                        (packed-layout-fields layout))
             (map 'list (lambda (class) (or class :integer)) classes))))))))

(defun c-abi-layouts (context)
  (let ((result (make-hash-table :test #'equal)))
    (maphash (lambda (name layout)
               (declare (ignore layout))
               (let ((classes (c-aggregate-classes
                               (list :struct name) context)))
                 (when classes (setf (gethash name result) classes))))
             (analysis-context-layouts context))
    result))

(defun find-structure-field (type name context)
  (unless (and (consp type) (eq (first type) :struct))
    (fail "field access requires a pointer to a structure"))
  (let* ((layout (gethash (second type) (analysis-context-layouts context)))
         (field (find name (packed-layout-fields layout)
                      :key #'field-layout-name :test #'equal)))
    (unless field (fail "structure ~A has no field ~A" (second type) name))
    field))
