(in-package #:psl.frontend)

(defvar *source-locations* nil)
(defvar *source-packages* nil)

(defun named-p (symbol name)
  (and (symbolp symbol) (string= (symbol-name symbol) (string-upcase name))))

(defun form-p (form name)
  (and (consp form)
       (eq (first form) (find-symbol (string-upcase name) :cl))))

(defun psl-form-p (form name)
  (and (consp form) (named-p (first form) name)
       (eq (symbol-package (first form)) (find-package :psl))))

(defun ffi-form-p (form name)
  (and (consp form) (named-p (first form) name)
       (eq (symbol-package (first form)) (find-package :ffi))))

(defun pointer-type (form context)
  (let ((qualifiers (cddr form)))
    (unless (and (>= (length form) 2)
                 (every (lambda (item) (member item '(:const :volatile))) qualifiers)
                 (= (length qualifiers) (length (remove-duplicates qualifiers))))
      (fail "invalid pointer type ~S" form))
    (when (eq (type-name (second form) context) :value)
      (fail "raw pointers to managed values are not supported"))
    (list :ptr (type-name (second form) context)
          (not (null (member :const qualifiers)))
          (not (null (member :volatile qualifiers))))))

(defun type-name (form context)
  (cond
    ((eq form 'psl:value)
     (require-hosted-runtime context)
     :value)
    ((and (consp form) (eq (first form) 'psl:ptr))
     (pointer-type form context))
    ((and (symbolp form)
          (gethash (source-name form) (analysis-context-layouts context)))
     (list :struct (source-name form)))
    (t (or (c-integer-type (analysis-context-target context) form)
           (case form
             (psl:u8 :u8) (psl:u16 :u16) (psl:u32 :u32) (psl:u64 :u64)
             (psl:s8 :s8) (psl:s16 :s16) (psl:s32 :s32) (psl:s64 :s64)
             (psl:usize :usize) (psl:isize :isize)
             ((psl:f32 psl:c-float) :f32)
             ((psl:f64 psl:c-double) :f64)
             (psl:void :void)
             (otherwise (fail "machine type ~S is not implemented yet" form)))))))

(defun source-name (thing)
  (etypecase thing
    (symbol (string-downcase (symbol-name thing)))
    (string thing)))

(defun ascii-letter-p (character)
  (or (char<= #\a character #\z)
      (char<= #\A character #\Z)))

(defun c-identifier-p (name)
  (and (stringp name)
       (plusp (length name))
       (or (ascii-letter-p (char name 0)) (char= (char name 0) #\_))
       (loop for character across name
             always (or (ascii-letter-p character)
                        (digit-char-p character 10)
                        (char= character #\_)))))

(defun parse-parameter (item context)
  (unless (and (listp item) (= (length item) 2)
               (symbolp (first item)))
    (fail "invalid typed parameter ~S" item))
  (cons (lexical-name (first item)) (type-name (second item) context)))

(defun parse-parameters (forms context)
  (unless (listp forms) (fail "parameter list must be a list"))
  (let ((seen (make-hash-table :test #'equal)))
    (loop for form in forms
          for parameter = (parse-parameter form context)
          for name = (car parameter)
          do (when (gethash name seen) (fail "duplicate parameter ~A" name))
             (setf (gethash name seen) t)
          collect parameter)))

(defun parse-declaration (form external-p context)
  (unless (and (>= (length form) 5) (named-p (fourth form) "->"))
    (fail "expected (~A name ((arg type) ...) -> result ...)"
          (if external-p "ffi:import-function" "defun")))
  (when (and external-p (not (c-identifier-p (second form))))
    (fail "FFI:IMPORT-FUNCTION requires a C identifier string"))
  (let* ((annotation (nthcdr 5 form))
         (name (source-name (second form)))
         (parameters (parse-parameters (third form) context))
         (sig (make-signature :name name :arguments (mapcar #'cdr parameters)
                              :result (type-name (fifth form) context)
                              :external-p external-p
                              :effect (if (and external-p
                                               (equal annotation '(:no-allocation)))
                                          :none :unknown))))
    (when (and external-p annotation
               (not (equal annotation '(:no-allocation))))
      (fail "extern function ~A accepts only :NO-ALLOCATION" name))
    (values sig parameters (unless external-p annotation))))

(defun plain-parameters (forms)
  (unless (and (listp forms) (every #'symbolp forms))
    (fail "DEFUN currently requires simple parameter names"))
  (let ((names (mapcar #'lexical-name forms)))
    (unless (= (length names) (length (remove-duplicates names :test #'equal)))
      (fail "duplicate DEFUN parameter"))
    names))

(defun collect-parameter-types (spec names types context)
  (unless (>= (length spec) 3)
    (fail "TYPE declaration needs a type and parameter names"))
  (let ((type (type-name (second spec) context)))
    (dolist (name-form (cddr spec))
      (let ((name (lexical-name name-form)))
        (unless (member name names :test #'equal)
          (fail "TYPE declaration names unknown parameter ~A" name))
        (when (gethash name types)
          (fail "duplicate TYPE declaration for ~A" name))
        (setf (gethash name types) type)))))

(defun parse-defun-declarations (specs names context)
  (let ((types (make-hash-table :test #'equal))
        (result nil)
        (exported nil))
    (dolist (spec specs)
      (let ((*source-location*
              (or (and *source-locations*
                       (gethash spec *source-locations*))
                  *source-location*)))
        (cond
          ((form-p spec "type")
           (collect-parameter-types spec names types context))
          ((psl-form-p spec "returns")
           (unless (= (length spec) 2)
             (fail "PSL:RETURNS requires one type"))
           (when result (fail "duplicate PSL:RETURNS declaration"))
           (setf result (type-name (second spec) context)))
          ((or (psl-form-p spec "export")
               (psl-form-p spec "c-export"))
           (unless (equal (rest spec) '(:c))
             (fail "only (C-EXPORT :C) is supported"))
           (when exported (fail "duplicate C-EXPORT declaration"))
           (setf exported t))
          (t (fail "unsupported DEFUN declaration ~S" spec)))))
    (unless result (fail "DEFUN needs a PSL:RETURNS declaration"))
    (values (mapcar (lambda (name)
                      (let ((type (gethash name types)))
                        (unless type (fail "missing TYPE declaration for ~A" name))
                        (cons name type)))
                    names)
            result exported)))

(defun parse-ordinary-defun (form context)
  (unless (and (>= (length form) 5) (symbolp (second form)))
    (fail "expected (defun name (args...) (declare ...) body...)"))
  (let* ((names (plain-parameters (third form)))
         (declaration (fourth form)))
    (unless (form-p declaration "declare")
      (fail "typed DEFUN needs a leading DECLARE form"))
    (multiple-value-bind (parameters result exported)
        (parse-defun-declarations (rest declaration) names context)
      (values (make-signature :name (source-name (second form))
                              :arguments (mapcar #'cdr parameters)
                              :result result :external-p nil
                              :local-p (not exported))
              parameters (nthcdr 4 form)))))

(defun source-line-starts (path)
  (let ((starts (make-array 1 :adjustable t :fill-pointer 1
                          :initial-element 0))
        (offset 0))
    (with-open-file (stream path :element-type '(unsigned-byte 8))
      (loop for octet = (read-byte stream nil nil)
            while octet
            do (incf offset)
               (when (= octet 10) (vector-push-extend offset starts))))
    starts))

(defun source-location-at (path starts offset)
  (let ((line 1) (line-start 0))
    (loop for start across starts
          for number from 1
          while (<= start offset)
          do (setf line number line-start start))
    (make-source-location :path (namestring (pathname path))
                          :line line :column (1+ (- offset line-start)))))

(defun tracking-readtable (path starts locations)
  (let* ((table (copy-readtable nil))
         (open-parenthesis (get-macro-character #\( table)))
    (set-macro-character
     #\(
     (lambda (stream character)
       (let* ((offset (max 0 (1- (or (file-position stream) 1))))
              (form (funcall open-parenthesis stream character)))
         (when (consp form)
           (setf (gethash form locations)
                 (source-location-at path starts offset)))
         form))
     nil table)
    table))

(defun read-source-forms (path starts locations &optional (process #'list))
  (let ((*readtable* (tracking-readtable path starts locations))
        (forms nil)
        (eof (gensym "SOURCE-EOF")))
    (with-open-file (stream path :direction :input :external-format :utf-8)
      (loop for offset = (file-position stream)
            for form = (handler-case (read stream nil eof)
                         (error (condition)
                           (let ((*source-location*
                                   (source-location-at path starts offset)))
                             (fail "reader error: ~A" condition))))
            until (eq form eof)
            do (when (consp form)
                 (unless (gethash form locations)
                   (setf (gethash form locations)
                         (source-location-at path starts offset))))
               (setf forms (nconc forms (funcall process form)))))
    forms))

(defun included-source-path (form parent)
  (unless (and (= (length form) 2) (stringp (second form)))
    (fail "INCLUDE requires one source filename"))
  (let ((path (merge-pathnames
               (second form)
               (make-pathname :name nil :type nil :defaults parent))))
    (unless (probe-file path)
      (fail "included source file does not exist: ~A" (second form)))
    (truename path)))

(defun read-source-file (path locations included active)
  (let* ((canonical (truename path))
         (key (namestring canonical)))
    (when (member key active :test #'equal)
      (fail "circular source include: ~A" key))
    (when (gethash key included)
      (return-from read-source-file nil))
    (setf (gethash key included) t)
    (read-source-forms
     canonical (source-line-starts canonical) locations
     (lambda (form)
       (let ((*source-location* (gethash form locations)))
         (cond
           ((psl-form-p form "include")
            (read-source-file (included-source-path form canonical)
                              locations included (cons key active)))
           ((form-p form "defpackage") (source-define-package form) nil)
           ((form-p form "in-package") (source-select-package form) nil)
           (t (list form))))))))

(defun read-source (path)
  "Read trusted Stage 0 source and return forms, package, and locations."
  (let* ((unit (make-package (symbol-name (gensym "PSL.SOURCE."))
                             :use '(:cl)))
         (*package* unit)
         (*source-packages* (list unit))
         (locations (make-hash-table :test #'eq)))
    (do-external-symbols (symbol (find-package :psl))
      (unless (find-symbol (symbol-name symbol) :cl)
        (shadowing-import symbol unit)))
    (handler-case
        (values (read-source-file path locations
                                  (make-hash-table :test #'equal) nil)
                unit locations *source-packages*)
      (error (condition)
        (dispose-source-packages *source-packages*)
        (error condition)))))
