(in-package #:psl.frontend)

(defun named-p (symbol name)
  (and (symbolp symbol) (string-equal (symbol-name symbol) name)))

(defun form-p (form name)
  (and (consp form) (named-p (first form) name)))

(defun psl-form-p (form name)
  (and (form-p form name)
       (eq (symbol-package (first form)) (find-package :psl))))

(defun ffi-form-p (form name)
  (and (form-p form name)
       (eq (symbol-package (first form)) (find-package :ffi))))

(defun pointer-type (form context)
  (let ((qualifiers (cddr form)))
    (unless (and (>= (length form) 2)
                 (every (lambda (item) (member item '(:const :volatile))) qualifiers)
                 (= (length qualifiers) (length (remove-duplicates qualifiers))))
      (fail "invalid pointer type ~S" form))
    (list :ptr (type-name (second form) context)
          (not (null (member :const qualifiers)))
          (not (null (member :volatile qualifiers))))))

(defun type-name (form context)
  (cond
    ((and (consp form) (eq (first form) 'psl:ptr))
     (pointer-type form context))
    ((and (symbolp form)
          (gethash (source-name form) (analysis-context-layouts context)))
     (list :struct (source-name form)))
    (t (case form
         (psl:u8 :u8) (psl:u16 :u16) (psl:u32 :u32) (psl:u64 :u64)
         (psl:s8 :s8) (psl:s16 :s16) (psl:s32 :s32) (psl:s64 :s64)
         (psl:usize :usize) (psl:isize :isize)
         (otherwise (fail "machine type ~S is not implemented yet" form))))))

(defun source-name (thing)
  (etypecase thing
    (symbol (string-downcase (symbol-name thing)))
    (string thing)))

(defun parse-parameter (item context)
  (unless (and (listp item) (= (length item) 2)
               (symbolp (first item)))
    (fail "invalid typed parameter ~S" item))
  (cons (source-name (first item)) (type-name (second item) context)))

(defun parse-parameters (forms context)
  (unless (listp forms) (fail "parameter list must be a list"))
  (let ((seen (make-hash-table :test #'equal)))
    (loop for form in forms
          for parameter = (parse-parameter form context)
          for name = (car parameter)
          do (when (gethash name seen) (fail "duplicate parameter ~A" name))
             (setf (gethash name seen) t)
          collect parameter)))

(defun parse-declaration (form external-p context)
  (unless (and (>= (length form) 5) (named-p (fourth form) "->"))
    (fail "expected (~A name ((arg type) ...) -> result ...)"
          (if external-p "ffi:import-function" "defun")))
  (let* ((name (source-name (second form)))
         (parameters (parse-parameters (third form) context))
         (sig (make-signature :name name :arguments (mapcar #'cdr parameters)
                              :result (type-name (fifth form) context)
                              :external-p external-p)))
    (when (and external-p (nthcdr 5 form))
      (fail "extern function ~A cannot have a body" name))
    (values sig parameters (nthcdr 5 form))))

(defun plain-parameters (forms)
  (unless (and (listp forms) (every #'symbolp forms))
    (fail "DEFUN currently requires simple parameter names"))
  (let ((names (mapcar #'source-name forms)))
    (unless (= (length names) (length (remove-duplicates names :test #'equal)))
      (fail "duplicate DEFUN parameter"))
    names))

(defun collect-parameter-types (spec names types context)
  (unless (>= (length spec) 3)
    (fail "TYPE declaration needs a type and parameter names"))
  (let ((type (type-name (second spec) context)))
    (dolist (name-form (cddr spec))
      (let ((name (source-name name-form)))
        (unless (member name names :test #'equal)
          (fail "TYPE declaration names unknown parameter ~A" name))
        (when (gethash name types)
          (fail "duplicate TYPE declaration for ~A" name))
        (setf (gethash name types) type)))))

(defun parse-defun-declarations (specs names context)
  (let ((types (make-hash-table :test #'equal))
        (result nil)
        (exported nil))
    (dolist (spec specs)
      (cond
        ((form-p spec "type")
         (collect-parameter-types spec names types context))
        ((psl-form-p spec "returns")
         (unless (= (length spec) 2)
           (fail "PSL:RETURNS requires one type"))
         (when result (fail "duplicate PSL:RETURNS declaration"))
         (setf result (type-name (second spec) context)))
        ((or (psl-form-p spec "export")
             (psl-form-p spec "c-export"))
         (unless (equal (rest spec) '(:c))
           (fail "only (C-EXPORT :C) is supported"))
         (when exported (fail "duplicate C-EXPORT declaration"))
         (setf exported t))
        (t (fail "unsupported DEFUN declaration ~S" spec))))
    (unless result (fail "DEFUN needs a PSL:RETURNS declaration"))
    (unless exported (fail "DEFUN needs (C-EXPORT :C) in Stage 0"))
    (values (mapcar (lambda (name)
                      (let ((type (gethash name types)))
                        (unless type (fail "missing TYPE declaration for ~A" name))
                        (cons name type)))
                    names)
            result)))

(defun parse-ordinary-defun (form context)
  (unless (and (>= (length form) 5) (symbolp (second form)))
    (fail "expected (defun name (args...) (declare ...) body...)"))
  (let* ((names (plain-parameters (third form)))
         (declaration (fourth form)))
    (unless (form-p declaration "declare")
      (fail "typed DEFUN needs a leading DECLARE form"))
    (multiple-value-bind (parameters result)
        (parse-defun-declarations (rest declaration) names context)
      (values (make-signature :name (source-name (second form))
                              :arguments (mapcar #'cdr parameters)
                              :result result :external-p nil)
              parameters (nthcdr 4 form)))))

(defun read-source (path)
  "Read trusted Stage 0 source. DEFMACRO forms execute on the build host."
  (let* ((unit (make-package (symbol-name (gensym "PSL.SOURCE."))
                             :use '(:cl)))
         (*package* unit)
         (forms nil))
    (do-external-symbols (symbol (find-package :psl))
      (unless (find-symbol (symbol-name symbol) :cl)
        (shadowing-import symbol unit)))
    (handler-case
        (progn
          (with-open-file (stream path :direction :input
                                       :external-format :utf-8)
            (loop for form = (read stream nil :eof)
                  until (eq form :eof)
                  do (push form forms)))
          (values (nreverse forms) unit))
      (error (condition)
        (delete-package unit)
        (error condition)))))
