(include "compiler_diagnostics.lisp")

(defun compiler_emit_object (state source_path output_path)
  (declare (type (ptr native_compiler_state) state) (type (ptr u8) source_path output_path)
           (returns c-int))
  (let ((driver (field-pointer state 'driver))
        (result (field-pointer state 'result)))
    (if (= (ffi:call native_compile_unit (field-pointer driver 'context)
                     (field-pointer driver 'object) result) 0)
        (progn
          (compiler_report_unit_error driver result)
          (ffi:call native_host_report_error 3 source_path 0 0)
          1)
        (if (= (ffi:call native_host_write_object output_path
                         (field-pointer driver 'object)) 0)
            (compiler_path_error 4 output_path)
            0))))

(defun compiler_load_and_prepare (state source_path output_path)
  (declare (type (ptr native_compiler_state) state) (type (ptr u8) source_path output_path)
           (returns c-int))
  (let ((driver (field-pointer state 'driver)))
    (store (field-pointer driver 'source)
      (ffi:call native_read_source_unit source_path (field-pointer driver 'length)))
    (if (= (ptr-address (deref (field-pointer driver 'source))) 0)
        (compiler_path_error 1 source_path)
        (if (= (ffi:call native_prepare_driver driver) 0)
            (compiler_path_error 2 (ptr-from-address (ptr u8) 0))
            (progn
              (store (field-pointer (field-pointer driver 'context) 'optimization)
                     (deref (field-pointer state 'optimization)))
              (compiler_emit_object state source_path output_path))))))

(defun compiler_run_options (source_path output_path optimization)
  (declare (type (ptr u8) source_path output_path) (type u32 optimization) (returns c-int))
  (let ((state (ptr-cast (ptr native_compiler_state)
                (ffi:call calloc 1 (sizeof 'native_compiler_state)))))
    (if (= (ptr-address state) 0)
        (compiler_path_error 2 (ptr-from-address (ptr u8) 0))
        (progn
          (store (field-pointer state 'optimization) optimization)
          (let ((status (compiler_load_and_prepare state source_path output_path)))
            (ffi:call native_release_driver (field-pointer state 'driver))
            (ffi:call free (ptr-cast (ptr void) state))
            status)))))

(defun native_run_compiler_options (source_path output_path optimization)
  (declare (type (ptr u8) source_path output_path) (type u32 optimization)
           (returns c-int) (c-export :c))
  (if (< 1 optimization) (compiler_path_error 5 (ptr-from-address (ptr u8) 0))
      (compiler_run_options source_path output_path optimization)))

(defun native_run_compiler (source_path output_path)
  (declare (type (ptr u8) source_path output_path) (returns c-int) (c-export :c))
  (native_run_compiler_options source_path output_path 1))

(defun compiler_parse_optimization (text)
  (declare (type (ptr u8) text) (returns c-int))
  (if (= (deref text) 45)
      (if (= (deref (pointer+ text 1)) 79)
          (let ((digit (deref (pointer+ text 2))))
            (if (if (= digit 48) t (= digit 49))
                (if (= (deref (pointer+ text 3)) 0)
                    (wrap-cast c-int (wrap- digit 48)) -1)
                -1))
          -1)
      -1))

(defun compiler_main_options (argv)
  (declare (type (ptr (ptr u8)) argv) (returns c-int))
  (let ((level (compiler_parse_optimization (deref (pointer+ argv 1)))))
    (if (< level 0) (compiler_path_error 5 (ptr-from-address (ptr u8) 0))
        (native_run_compiler_options (deref (pointer+ argv 2))
                                    (deref (pointer+ argv 3)) (wrap-cast u32 level)))))

(defun native_compiler_main (argc argv)
  (declare (type c-int argc) (type (ptr (ptr u8)) argv)
           (returns c-int) (c-export :c))
  (cond
    ((= argc 3) (native_run_compiler (deref (pointer+ argv 1)) (deref (pointer+ argv 2))))
    ((= argc 4) (compiler_main_options argv))
    (t (compiler_path_error 5 (ptr-from-address (ptr u8) 0)))))
