(include "../compile_scalar_types.lisp")

;; The driver owns the source and these separately allocated, zeroed arenas.
(defcstruct native_storage
  (syntax (ptr psl_ast_node))
  (layouts (ptr native_layout))
  (fields (ptr native_layout_field))
  (parameters (ptr native_parameter))
  (functions (ptr native_function))
  (signatures (ptr native_signature))
  (data_imports (ptr native_data_import))
  (data_bytes (ptr u8))
  (hir (ptr native_hir_node))
  (ssa (ptr native_ssa_value))
  (ssa_blocks (ptr native_ssa_block))
  (types (ptr native_ir_type))
  (lir (ptr native_lir_instruction))
  (lir_blocks (ptr native_lir_block))
  (calls (ptr native_call_fixup))
  (jumps (ptr native_call_fixup))
  (data_fixups (ptr native_call_fixup))
  (bindings (ptr usize))
  (labels (ptr usize))
  (code (ptr u8))
  (object (ptr u8))
  (inline_values (ptr native_ssa_value))
  (symbol_names (ptr u8))
  (packages (ptr native_ct_package))
  (symbols (ptr native_ct_symbol))
  (present (ptr native_ct_presence))
  (uses (ptr native_ct_use))
  (aliases (ptr native_ct_alias))
  (identities (ptr native_source_identity))
  (buckets (ptr usize))
  (macro_definitions (ptr native_macro_definition))
  (macro_bindings (ptr native_macro_binding)))

(defcstruct native_driver
  (source (ptr u8))
  (length usize)
  (storage native_storage)
  (scanner psl_scanner)
  (token psl_token)
  (parser psl_parser)
  (integer psl_parsed_integer)
  (shape native_type_shape)
  (layouts native_layout_context)
  (signature_context native_signature_context)
  (hir native_hir_arena)
  (ssa native_ssa_arena)
  (lir native_lir_arena)
  (calls native_fixup_arena)
  (jumps native_fixup_arena)
  (data_fixups native_fixup_arena)
  (code byte_buffer)
  (object byte_buffer)
  (context native_compile_context)
  (environment native_ct_environment)
  (reader native_reader_environment))
