(include "driver_types.lisp")

(defun native_environment_name_capacity (capacity)
  (declare (type usize capacity) (returns usize))
  (wrap+ capacity 12000))

(defun native_environment_symbol_capacity (capacity)
  (declare (type usize capacity) (returns usize))
  (wrap+ capacity 1049))

(defun native_environment_presence_capacity (capacity)
  (declare (type usize capacity) (returns usize))
  (wrap+ capacity 1111))

(defun native_environment_counts_fit (capacity)
  (declare (type usize capacity) (returns c-int))
  (if (< capacity (native_environment_name_capacity capacity)) 1 0))

(defun native_allocate_environment (storage capacity)
  (declare (type (ptr native_storage) storage) (type usize capacity)
           (returns c-int))
  (store (field-pointer storage 'symbol_names)
         (ptr-cast (ptr u8) (ffi:call calloc (native_environment_name_capacity capacity) (sizeof 'u8))))
  (store (field-pointer storage 'packages)
         (ptr-cast (ptr native_ct_package) (ffi:call calloc 5 (sizeof 'native_ct_package))))
  (store (field-pointer storage 'symbols)
         (ptr-cast (ptr native_ct_symbol) (ffi:call calloc (native_environment_symbol_capacity capacity) (sizeof 'native_ct_symbol))))
  (store (field-pointer storage 'present)
         (ptr-cast (ptr native_ct_presence) (ffi:call calloc (native_environment_presence_capacity capacity) (sizeof 'native_ct_presence))))
  (store (field-pointer storage 'uses)
         (ptr-cast (ptr native_ct_use) (ffi:call calloc 2 (sizeof 'native_ct_use))))
  (store (field-pointer storage 'aliases)
         (ptr-cast (ptr native_ct_alias) (ffi:call calloc 2 (sizeof 'native_ct_alias))))
  (store (field-pointer storage 'identities)
         (ptr-cast (ptr native_source_identity) (ffi:call calloc capacity (sizeof 'native_source_identity))))
  (store (field-pointer storage 'buckets)
         (ptr-cast (ptr usize) (ffi:call calloc 5120 (sizeof 'usize))))
  (cond
    ((= (ptr-address (deref (field-pointer storage 'buckets))) 0) 0)
    ((= (ptr-address (deref (field-pointer storage 'symbol_names))) 0) 0)
    ((= (ptr-address (deref (field-pointer storage 'packages))) 0) 0)
    ((= (ptr-address (deref (field-pointer storage 'symbols))) 0) 0)
    ((= (ptr-address (deref (field-pointer storage 'present))) 0) 0)
    ((= (ptr-address (deref (field-pointer storage 'uses))) 0) 0)
    ((= (ptr-address (deref (field-pointer storage 'aliases))) 0) 0)
    ((= (ptr-address (deref (field-pointer storage 'identities))) 0) 0)
    (t 1)))

(defun native_release_environment (storage)
  (declare (type (ptr native_storage) storage) (returns c-int))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer storage 'symbol_names))))
  (store (field-pointer storage 'symbol_names) (ptr-from-address (ptr u8) 0))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer storage 'packages))))
  (store (field-pointer storage 'packages) (ptr-from-address (ptr native_ct_package) 0))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer storage 'symbols))))
  (store (field-pointer storage 'symbols) (ptr-from-address (ptr native_ct_symbol) 0))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer storage 'present))))
  (store (field-pointer storage 'present) (ptr-from-address (ptr native_ct_presence) 0))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer storage 'uses))))
  (store (field-pointer storage 'uses) (ptr-from-address (ptr native_ct_use) 0))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer storage 'aliases))))
  (store (field-pointer storage 'aliases) (ptr-from-address (ptr native_ct_alias) 0))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer storage 'identities))))
  (store (field-pointer storage 'identities) (ptr-from-address (ptr native_source_identity) 0))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer storage 'buckets))))
  (store (field-pointer storage 'buckets) (ptr-from-address (ptr usize) 0))
  1)
