(include "driver_types.lisp")
(ffi:import-function "native_ct_seed_standard" ((env (ptr native_ct_environment))) -> c-int)

(defun native_initialize_environment (driver capacity)
  (declare (type (ptr native_driver) driver) (type usize capacity)
           (returns c-int))
  (let ((env (field-pointer driver 'environment))
        (reader (field-pointer driver 'reader))
        (storage (field-pointer driver 'storage)))
    (store (field-pointer env 'names) (deref (field-pointer storage 'symbol_names)))
    (store (field-pointer env 'packages) (deref (field-pointer storage 'packages)))
    (store (field-pointer env 'symbols) (deref (field-pointer storage 'symbols)))
    (store (field-pointer env 'present) (deref (field-pointer storage 'present)))
    (store (field-pointer env 'uses) (deref (field-pointer storage 'uses)))
    (store (field-pointer env 'aliases) (deref (field-pointer storage 'aliases)))
    (store (field-pointer env 'name_count) 0)
    (store (field-pointer env 'package_count) 0)
    (store (field-pointer env 'symbol_count) 0)
    (store (field-pointer env 'present_count) 0)
    (store (field-pointer env 'use_count) 0)
    (store (field-pointer env 'alias_count) 0)
    (store (field-pointer env 'current_package) 0)
    (store (field-pointer env 'keyword_package) 0)
    (store (field-pointer env 'nil_symbol) 0)
    (store (field-pointer env 'true_symbol) 0)
    (store (field-pointer env 'name_cursor) 0)
    (store (field-pointer env 'name_result) 0)
    (store (field-pointer env 'lookup_cursor) 0)
    (store (field-pointer env 'lookup_result) 0)
    (store (field-pointer env 'read_cursor) 0)
    (store (field-pointer env 'read_prefix) 0)
    (store (field-pointer env 'read_separator) 0)
    (store (field-pointer env 'read_separators) 0)
    (store (field-pointer env 'read_bar) 0)
    (store (field-pointer env 'read_escape) 0)
    (store (field-pointer env 'read_body) 0)
    (store (field-pointer env 'read_uninterned) 0)
    (store (field-pointer env 'error) 0)
    (store (field-pointer env 'buckets) (deref (field-pointer storage 'buckets)))
    (store (field-pointer env 'bucket_count) 1024)
    (store (field-pointer env 'bucket_capacity) 131072)
    (store (field-pointer env 'hash) 0)
    (store (field-pointer env 'name_capacity) (native_environment_name_capacity capacity))
    (store (field-pointer env 'package_capacity) 128)
    (store (field-pointer env 'symbol_capacity) (native_environment_symbol_capacity capacity))
    (store (field-pointer env 'present_capacity) (native_environment_presence_capacity capacity))
    (store (field-pointer env 'use_capacity) 512)
    (store (field-pointer env 'alias_capacity) 128)
    (store (field-pointer reader 'environment) env)
    (store (field-pointer reader 'identities) (deref (field-pointer storage 'identities)))
    (store (field-pointer reader 'capacity) capacity)
    (store (field-pointer reader 'count) 0)
    (store (field-pointer reader 'cursor) 0)
    (store (field-pointer reader 'error) 0)
    (store (field-pointer reader 'failure) 0)
    (ffi:call native_ct_seed_standard env)))
