(include "driver_types.lisp")

;; Reset every logical field, including scalar scratch state and parser lookahead.

(defun native_initialize_scanner (driver capacity)
  (declare (type (ptr native_driver) driver) (type usize capacity)
           (returns c-int))
  (let ((record (field-pointer driver 'scanner)))
    (store (field-pointer record 'data) (deref (field-pointer driver 'source)))
    (store (field-pointer record 'length) (deref (field-pointer driver 'length)))
    (store (field-pointer record 'cursor) 0)
    (store (field-pointer record 'error) 0)
    1))

(defun native_initialize_token (driver capacity)
  (declare (type (ptr native_driver) driver) (type usize capacity)
           (returns c-int))
  (let ((record (field-pointer driver 'token)))
    (store (field-pointer record 'kind) 0)
    (store (field-pointer record 'start) 0)
    (store (field-pointer record 'length) 0)
    1))

(defun native_initialize_parser (driver capacity)
  (declare (type (ptr native_driver) driver) (type usize capacity)
           (returns c-int))
  (let ((record (field-pointer driver 'parser)))
    (store (field-pointer record 'scanner) (field-pointer driver 'scanner))
    (store (field-pointer record 'token) (field-pointer driver 'token))
    (store (field-pointer record 'has_token) 0)
    (store (field-pointer record 'nodes) (deref (field-pointer (field-pointer driver 'storage) 'syntax)))
    (store (field-pointer record 'count) 0)
    (store (field-pointer record 'capacity) capacity)
    (store (field-pointer record 'error) 0)
    1))

(defun native_initialize_integer (driver capacity)
  (declare (type (ptr native_driver) driver) (type usize capacity)
           (returns c-int))
  (let ((record (field-pointer driver 'integer)))
    (store (field-pointer record 'magnitude) 0)
    (store (field-pointer record 'negative) 0)
    (store (field-pointer record 'radix) 0)
    1))

(defun native_initialize_shape (driver capacity)
  (declare (type (ptr native_driver) driver) (type usize capacity)
           (returns c-int))
  (let ((record (field-pointer driver 'shape)))
    (store (field-pointer record 'size) 0)
    (store (field-pointer record 'alignment) 0)
    (store (field-pointer record 'kind) 0)
    (store (field-pointer record 'pointee) 0)
    1))

(defun native_initialize_layouts (driver capacity)
  (declare (type (ptr native_driver) driver) (type usize capacity)
           (returns c-int))
  (let ((record (field-pointer driver 'layouts)))
    (store (field-pointer record 'parser) (field-pointer driver 'parser))
    (store (field-pointer record 'source) (deref (field-pointer driver 'source)))
    (store (field-pointer record 'layouts) (deref (field-pointer (field-pointer driver 'storage) 'layouts)))
    (store (field-pointer record 'layout_count) 0)
    (store (field-pointer record 'layout_capacity) capacity)
    (store (field-pointer record 'fields) (deref (field-pointer (field-pointer driver 'storage) 'fields)))
    (store (field-pointer record 'field_count) 0)
    (store (field-pointer record 'field_capacity) capacity)
    (store (field-pointer record 'scratch) (field-pointer driver 'shape))
    (store (field-pointer record 'error) 0)
    1))

(defun native_initialize_signature_context (driver capacity)
  (declare (type (ptr native_driver) driver) (type usize capacity)
           (returns c-int))
  (let ((record (field-pointer driver 'signature_context)))
    (store (field-pointer record 'layouts) (field-pointer driver 'layouts))
    (store (field-pointer record 'signatures) (deref (field-pointer (field-pointer driver 'storage) 'signatures)))
    (store (field-pointer record 'signature_count) 0)
    (store (field-pointer record 'signature_capacity) capacity)
    (store (field-pointer record 'parameters) (deref (field-pointer (field-pointer driver 'storage) 'parameters)))
    (store (field-pointer record 'parameter_count) 0)
    (store (field-pointer record 'parameter_capacity) capacity)
    (store (field-pointer record 'error) 0)
    1))

(defun native_initialize_hir (driver capacity)
  (declare (type (ptr native_driver) driver) (type usize capacity)
           (returns c-int))
  (let ((record (field-pointer driver 'hir)))
    (store (field-pointer record 'nodes) (deref (field-pointer (field-pointer driver 'storage) 'hir)))
    (store (field-pointer record 'count) 0)
    (store (field-pointer record 'capacity) capacity)
    (store (field-pointer record 'error) 0)
    1))

(defun native_initialize_ssa (driver capacity)
  (declare (type (ptr native_driver) driver) (type usize capacity)
           (returns c-int))
  (let ((record (field-pointer driver 'ssa)))
    (store (field-pointer record 'values) (deref (field-pointer (field-pointer driver 'storage) 'ssa)))
    (store (field-pointer record 'types) (deref (field-pointer (field-pointer driver 'storage) 'types)))
    (store (field-pointer record 'value_count) 0)
    (store (field-pointer record 'value_capacity) capacity)
    (store (field-pointer record 'blocks) (deref (field-pointer (field-pointer driver 'storage) 'ssa_blocks)))
    (store (field-pointer record 'block_count) 0)
    (store (field-pointer record 'block_capacity) capacity)
    (store (field-pointer record 'current) 0)
    (store (field-pointer record 'error) 0)
    1))

(defun native_initialize_lir (driver capacity)
  (declare (type (ptr native_driver) driver) (type usize capacity)
           (returns c-int))
  (let ((record (field-pointer driver 'lir)))
    (store (field-pointer record 'instructions) (deref (field-pointer (field-pointer driver 'storage) 'lir)))
    (store (field-pointer record 'count) 0)
    (store (field-pointer record 'capacity) (wrap* capacity 6))
    (store (field-pointer record 'types) (deref (field-pointer (field-pointer driver 'storage) 'types)))
    (store (field-pointer record 'value_count) 0)
    (store (field-pointer record 'value_capacity) capacity)
    (store (field-pointer record 'blocks) (deref (field-pointer (field-pointer driver 'storage) 'lir_blocks)))
    (store (field-pointer record 'label_count) 0)
    (store (field-pointer record 'label_capacity) (wrap* capacity 3))
    (store (field-pointer record 'error) 0)
    1))

(defun native_initialize_calls (driver capacity)
  (declare (type (ptr native_driver) driver) (type usize capacity)
           (returns c-int))
  (let ((record (field-pointer driver 'calls)))
    (store (field-pointer record 'items) (deref (field-pointer (field-pointer driver 'storage) 'calls)))
    (store (field-pointer record 'count) 0)
    (store (field-pointer record 'capacity) capacity)
    (store (field-pointer record 'error) 0)
    1))

(defun native_initialize_jumps (driver capacity)
  (declare (type (ptr native_driver) driver) (type usize capacity)
           (returns c-int))
  (let ((record (field-pointer driver 'jumps)))
    (store (field-pointer record 'items) (deref (field-pointer (field-pointer driver 'storage) 'jumps)))
    (store (field-pointer record 'count) 0)
    (store (field-pointer record 'capacity) (wrap* capacity 3))
    (store (field-pointer record 'error) 0)
    1))

(defun native_initialize_data_fixups (driver capacity)
  (declare (type (ptr native_driver) driver) (type usize capacity)
           (returns c-int))
  (let ((record (field-pointer driver 'data_fixups)))
    (store (field-pointer record 'items)
           (deref (field-pointer (field-pointer driver 'storage) 'data_fixups)))
    (store (field-pointer record 'count) 0)
    (store (field-pointer record 'capacity) capacity)
    (store (field-pointer record 'error) 0)
    1))

(defun native_initialize_code (driver capacity)
  (declare (type (ptr native_driver) driver) (type usize capacity)
           (returns c-int))
  (let ((record (field-pointer driver 'code)))
    (store (field-pointer record 'data) (deref (field-pointer (field-pointer driver 'storage) 'code)))
    (store (field-pointer record 'length) 0)
    (store (field-pointer record 'capacity) (native_code_capacity capacity))
    1))

(defun native_initialize_object (driver capacity)
  (declare (type (ptr native_driver) driver) (type usize capacity)
           (returns c-int))
  (let ((record (field-pointer driver 'object)))
    (store (field-pointer record 'data) (deref (field-pointer (field-pointer driver 'storage) 'object)))
    (store (field-pointer record 'length) 0)
    (store (field-pointer record 'capacity) (native_object_capacity capacity))
    1))

(defun native_initialize_context (driver capacity)
  (declare (type (ptr native_driver) driver) (type usize capacity)
           (returns c-int))
  (let ((record (field-pointer driver 'context)))
    (store (field-pointer record 'parser) (field-pointer driver 'parser))
    (store (field-pointer record 'source) (deref (field-pointer driver 'source)))
    (store (field-pointer record 'integer) (field-pointer driver 'integer))
    (store (field-pointer record 'hir) (field-pointer driver 'hir))
    (store (field-pointer record 'code) (field-pointer driver 'code))
    (store (field-pointer record 'fixups) (field-pointer driver 'calls))
    (store (field-pointer record 'functions) (deref (field-pointer (field-pointer driver 'storage) 'functions)))
    (store (field-pointer record 'signatures) (field-pointer driver 'signature_context))
    (store (field-pointer record 'prior_count) 0)
    (store (field-pointer record 'current_arity) 0)
    (store (field-pointer record 'current_signature) (ptr-from-address (ptr native_signature) 0))
    (store (field-pointer record 'expected_type) 0)
    (store (field-pointer record 'active_binding) 0)
    (store (field-pointer record 'local_count) 0)
    (store (field-pointer record 'expected_pointee) 0)
    (store (field-pointer record 'ssa) (field-pointer driver 'ssa))
    (store (field-pointer record 'bindings) (deref (field-pointer (field-pointer driver 'storage) 'bindings)))
    (store (field-pointer record 'lir) (field-pointer driver 'lir))
    (store (field-pointer record 'labels) (deref (field-pointer (field-pointer driver 'storage) 'labels)))
    (store (field-pointer record 'jumps) (field-pointer driver 'jumps))
    (store (field-pointer record 'optimization) 1)
    (store (field-pointer record 'fold_cursor) 0)
    (store (field-pointer record 'fold_changed) 0)
    (store (field-pointer record 'effects_changed) 0)
    (store (field-pointer record 'inline_values) (deref (field-pointer (field-pointer driver 'storage) 'inline_values)))
    (store (field-pointer record 'inline_count) 0)
    (store (field-pointer record 'inline_capacity) capacity)
    (store (field-pointer record 'inline_cursor) 0)
    (store (field-pointer record 'target) 0)
    (store (field-pointer record 'backend_frame_size) 0)
    (store (field-pointer record 'backend_outgoing_size) 0)
    (store (field-pointer record 'backend_prologue_size) 0)
    (store (field-pointer record 'data_imports)
           (deref (field-pointer (field-pointer driver 'storage) 'data_imports)))
    (store (field-pointer record 'data_count) 0)
    (store (field-pointer record 'data_capacity) capacity)
    (store (field-pointer record 'data_bytes)
           (deref (field-pointer (field-pointer driver 'storage) 'data_bytes)))
    (store (field-pointer record 'data_byte_count) 0)
    (store (field-pointer record 'data_byte_capacity) capacity)
    (store (field-pointer record 'data_fixups) (field-pointer driver 'data_fixups))
    1))

(defun native_initialize_driver (driver capacity)
  (declare (type (ptr native_driver) driver) (type usize capacity)
           (returns c-int))
  (native_initialize_scanner driver capacity)
  (native_initialize_token driver capacity)
  (native_initialize_parser driver capacity)
  (native_initialize_integer driver capacity)
  (native_initialize_shape driver capacity)
  (native_initialize_layouts driver capacity)
  (native_initialize_signature_context driver capacity)
  (native_initialize_hir driver capacity)
  (native_initialize_ssa driver capacity)
  (native_initialize_lir driver capacity)
  (native_initialize_calls driver capacity)
  (native_initialize_jumps driver capacity)
  (native_initialize_data_fixups driver capacity)
  (native_initialize_code driver capacity)
  (native_initialize_object driver capacity)
  (native_initialize_context driver capacity)
  1)
