(include "driver_types.lisp")

;; The hosted driver declares its libc boundary. The native core stays independent.
(ffi:import-function "calloc" ((count usize) (size usize)) -> (ptr void))
(ffi:import-function "free" ((memory (ptr void))) -> void)

;; Check each partial product, before deriving the larger IR arena counts.
;; FACTOR is a small arena multiplier, not an input-dependent iteration bound.
(defun native_count_product_fits (count factor)
  (declare (type usize count factor) (returns c-int))
  (if (= factor 0) 1
      (if (< (wrap* count factor) (wrap* count (wrap- factor 1)))
          0 (native_count_product_fits count (wrap- factor 1)))))

(defun native_allocate_frontend (storage capacity)
  (declare (type (ptr native_storage) storage) (type usize capacity)
           (returns c-int))
  (store (field-pointer storage 'syntax)
         (ptr-cast (ptr psl_ast_node) (ffi:call calloc capacity (sizeof 'psl_ast_node))))
  (store (field-pointer storage 'layouts)
         (ptr-cast (ptr native_layout) (ffi:call calloc capacity (sizeof 'native_layout))))
  (store (field-pointer storage 'fields)
         (ptr-cast (ptr native_layout_field) (ffi:call calloc capacity (sizeof 'native_layout_field))))
  (store (field-pointer storage 'parameters)
         (ptr-cast (ptr native_parameter) (ffi:call calloc capacity (sizeof 'native_parameter))))
  (store (field-pointer storage 'functions)
         (ptr-cast (ptr native_function) (ffi:call calloc capacity (sizeof 'native_function))))
  (store (field-pointer storage 'signatures)
         (ptr-cast (ptr native_signature) (ffi:call calloc capacity (sizeof 'native_signature))))
  (cond
    ((= (ptr-address (deref (field-pointer storage 'syntax))) 0) 0)
    ((= (ptr-address (deref (field-pointer storage 'layouts))) 0) 0)
    ((= (ptr-address (deref (field-pointer storage 'fields))) 0) 0)
    ((= (ptr-address (deref (field-pointer storage 'parameters))) 0) 0)
    ((= (ptr-address (deref (field-pointer storage 'functions))) 0) 0)
    ((= (ptr-address (deref (field-pointer storage 'signatures))) 0) 0)
    (t 1)))

(defun native_release_frontend (storage)
  (declare (type (ptr native_storage) storage) (returns c-int))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer storage 'syntax))))
  (store (field-pointer storage 'syntax) (ptr-from-address (ptr psl_ast_node) 0))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer storage 'layouts))))
  (store (field-pointer storage 'layouts) (ptr-from-address (ptr native_layout) 0))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer storage 'fields))))
  (store (field-pointer storage 'fields) (ptr-from-address (ptr native_layout_field) 0))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer storage 'parameters))))
  (store (field-pointer storage 'parameters) (ptr-from-address (ptr native_parameter) 0))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer storage 'functions))))
  (store (field-pointer storage 'functions) (ptr-from-address (ptr native_function) 0))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer storage 'signatures))))
  (store (field-pointer storage 'signatures) (ptr-from-address (ptr native_signature) 0))
  1)

(defun native_allocate_ir (storage capacity)
  (declare (type (ptr native_storage) storage) (type usize capacity)
           (returns c-int))
  (store (field-pointer storage 'hir)
         (ptr-cast (ptr native_hir_node) (ffi:call calloc capacity (sizeof 'native_hir_node))))
  (store (field-pointer storage 'ssa)
         (ptr-cast (ptr native_ssa_value) (ffi:call calloc capacity (sizeof 'native_ssa_value))))
  (store (field-pointer storage 'ssa_blocks)
         (ptr-cast (ptr native_ssa_block) (ffi:call calloc capacity (sizeof 'native_ssa_block))))
  (store (field-pointer storage 'types)
         (ptr-cast (ptr native_ir_type) (ffi:call calloc capacity (sizeof 'native_ir_type))))
  (store (field-pointer storage 'bindings)
         (ptr-cast (ptr usize) (ffi:call calloc capacity (sizeof 'usize))))
  (store (field-pointer storage 'lir)
         (ptr-cast (ptr native_lir_instruction) (ffi:call calloc (wrap* capacity 6) (sizeof 'native_lir_instruction))))
  (store (field-pointer storage 'lir_blocks)
         (ptr-cast (ptr native_lir_block) (ffi:call calloc (wrap* capacity 3) (sizeof 'native_lir_block))))
  (store (field-pointer storage 'inline_values)
         (ptr-cast (ptr native_ssa_value) (ffi:call calloc capacity (sizeof 'native_ssa_value))))
  (cond
    ((= (ptr-address (deref (field-pointer storage 'hir))) 0) 0)
    ((= (ptr-address (deref (field-pointer storage 'ssa))) 0) 0)
    ((= (ptr-address (deref (field-pointer storage 'ssa_blocks))) 0) 0)
    ((= (ptr-address (deref (field-pointer storage 'types))) 0) 0)
    ((= (ptr-address (deref (field-pointer storage 'bindings))) 0) 0)
    ((= (ptr-address (deref (field-pointer storage 'lir))) 0) 0)
    ((= (ptr-address (deref (field-pointer storage 'lir_blocks))) 0) 0)
    ((= (ptr-address (deref (field-pointer storage 'inline_values))) 0) 0)
    (t 1)))

(defun native_release_ir (storage)
  (declare (type (ptr native_storage) storage) (returns c-int))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer storage 'hir))))
  (store (field-pointer storage 'hir) (ptr-from-address (ptr native_hir_node) 0))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer storage 'ssa))))
  (store (field-pointer storage 'ssa) (ptr-from-address (ptr native_ssa_value) 0))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer storage 'ssa_blocks))))
  (store (field-pointer storage 'ssa_blocks) (ptr-from-address (ptr native_ssa_block) 0))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer storage 'types))))
  (store (field-pointer storage 'types) (ptr-from-address (ptr native_ir_type) 0))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer storage 'bindings))))
  (store (field-pointer storage 'bindings) (ptr-from-address (ptr usize) 0))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer storage 'lir))))
  (store (field-pointer storage 'lir) (ptr-from-address (ptr native_lir_instruction) 0))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer storage 'lir_blocks))))
  (store (field-pointer storage 'lir_blocks) (ptr-from-address (ptr native_lir_block) 0))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer storage 'inline_values))))
  (store (field-pointer storage 'inline_values) (ptr-from-address (ptr native_ssa_value) 0))
  1)

(defun native_allocate_output (storage capacity)
  (declare (type (ptr native_storage) storage) (type usize capacity)
           (returns c-int))
  (store (field-pointer storage 'calls)
         (ptr-cast (ptr native_call_fixup) (ffi:call calloc capacity (sizeof 'native_call_fixup))))
  (store (field-pointer storage 'jumps)
         (ptr-cast (ptr native_call_fixup) (ffi:call calloc (wrap* capacity 3) (sizeof 'native_call_fixup))))
  (store (field-pointer storage 'labels)
         (ptr-cast (ptr usize) (ffi:call calloc (wrap* capacity 3) (sizeof 'usize))))
  (store (field-pointer storage 'code)
         (ptr-cast (ptr u8) (ffi:call calloc 1048576 (sizeof 'u8))))
  (store (field-pointer storage 'object)
         (ptr-cast (ptr u8) (ffi:call calloc 1200000 (sizeof 'u8))))
  (cond
    ((= (ptr-address (deref (field-pointer storage 'calls))) 0) 0)
    ((= (ptr-address (deref (field-pointer storage 'jumps))) 0) 0)
    ((= (ptr-address (deref (field-pointer storage 'labels))) 0) 0)
    ((= (ptr-address (deref (field-pointer storage 'code))) 0) 0)
    ((= (ptr-address (deref (field-pointer storage 'object))) 0) 0)
    (t 1)))

(defun native_release_output (storage)
  (declare (type (ptr native_storage) storage) (returns c-int))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer storage 'calls))))
  (store (field-pointer storage 'calls) (ptr-from-address (ptr native_call_fixup) 0))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer storage 'jumps))))
  (store (field-pointer storage 'jumps) (ptr-from-address (ptr native_call_fixup) 0))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer storage 'labels))))
  (store (field-pointer storage 'labels) (ptr-from-address (ptr usize) 0))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer storage 'code))))
  (store (field-pointer storage 'code) (ptr-from-address (ptr u8) 0))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer storage 'object))))
  (store (field-pointer storage 'object) (ptr-from-address (ptr u8) 0))
  1)

;; Release is safe after any partial allocation and is idempotent. SOURCE is
;; owned by this driver and must have been obtained from a free-compatible allocator.
(defun native_release_driver (driver)
  (declare (type (ptr native_driver) driver) (returns c-int) (c-export :c))
  (let ((storage (field-pointer driver 'storage)))
    (native_release_frontend storage)
    (native_release_ir storage)
    (native_release_output storage))
  (ffi:call free (ptr-cast (ptr void) (deref (field-pointer driver 'source))))
  (store (field-pointer driver 'source) (ptr-from-address (ptr u8) 0))
  (store (field-pointer driver 'length) 0)
  1)
