(defun main ()
  (declare (returns c-int) (c-export :c))
  (let ((unused-machine-value 7))
    (let ((first (box-fixnum 40))
          (second (box-fixnum 2)))
      (let ((closure #'(lambda (argument)
                         (cons first (cons second argument)))))
        (collect-garbage)
        (let ((result (funcall closure 5)))
          (if (= (unbox-fixnum (car result)) 40)
              (if (= (unbox-fixnum (car (cdr result))) 2)
                  (if (= (unbox-fixnum (cdr (cdr result))) 5) 0 1)
                  1)
              1))))))
