(defun main ()
  (declare (returns c-int) (c-export :c))
  (let ((name "ASL"))
    (set-string-byte name 0 80)
    (let ((package (make-package-from-name name)))
      (let ((symbol (intern-symbol package name)))
        (collect-garbage)
        (if (eq symbol (intern-symbol package name))
            (if (= (string-byte (symbol-name symbol) 0) 80)
                (if (eq (package-name package) name) 0 1)
                1)
            1)))))
