(include "types.lisp")

(defun native_macro_declaration_p (registry reference)
  (declare (type (ptr native_macro_registry) registry) (type usize reference) (returns c-int))
  (if (= reference 0) 0
      (let ((parser (native_macro_parser registry)))
        (let ((node (parser_node parser reference)))
          (if (= (deref (field-pointer node 'kind)) 1)
              (ast_builtin_word_p parser (deref (field-pointer registry 'source))
                                  (deref (field-pointer node 'first)) #x6572616c636564 0 7) 0)))))

(defun native_macro_declared_variables_p (registry reference)
  (declare (type (ptr native_macro_registry) registry) (type usize reference) (returns c-int))
  (let ((tree (deref (field-pointer registry 'tree))))
    (store (field-pointer tree 'cursor) reference)
    (while (if (= (deref (field-pointer registry 'error)) 0)
               (< 0 (deref (field-pointer tree 'cursor))) nil)
      (let ((variable (deref (field-pointer tree 'cursor))))
        (if (if (= (ast_symbol_identity (native_macro_parser registry) variable) 0) t
                (= (native_macro_raw_dot_p registry variable) 1))
            (native_macro_fail registry 10)
            (store (field-pointer tree 'cursor) (native_macro_next registry variable)))))
    (if (= (deref (field-pointer registry 'error)) 0) 1 0)))

(defun native_macro_declaration_spec_p (registry reference)
  (declare (type (ptr native_macro_registry) registry) (type usize reference) (returns c-int))
  (let ((parser (native_macro_parser registry)) (source (deref (field-pointer registry 'source))))
    (let ((node (parser_node parser reference)))
      (if (= (deref (field-pointer node 'kind)) 1)
          (let ((head (deref (field-pointer node 'first))))
            (if (if (= (ast_builtin_word_p parser source head #x65726f6e6769 0 6) 1) t
                    (= (ast_builtin_word_p parser source head #x6c6261726f6e6769 #x65 9) 1))
                (native_macro_declared_variables_p registry (native_macro_next registry head)) 0))
          0))))

(defun native_macro_validate_declaration (registry reference)
  (declare (type (ptr native_macro_registry) registry) (type usize reference) (returns c-int))
  (let ((tree (deref (field-pointer registry 'tree))) (parser (native_macro_parser registry)))
    (store (field-pointer tree 'cursor)
           (native_macro_next registry (deref (field-pointer (parser_node parser reference) 'first))))
    (while (if (= (deref (field-pointer registry 'error)) 0)
               (< 0 (deref (field-pointer tree 'cursor))) nil)
      (let ((spec (deref (field-pointer tree 'cursor))))
        (let ((next (native_macro_next registry spec)))
          (if (= (native_macro_declaration_spec_p registry spec) 1)
              (store (field-pointer tree 'cursor) next) (native_macro_fail registry 10)))))
    (if (= (deref (field-pointer registry 'error)) 0) 1 0)))

(defun native_macro_body_prefix_step (registry reference)
  (declare (type (ptr native_macro_registry) registry) (type usize reference) (returns usize))
  (let ((tree (deref (field-pointer registry 'tree))) (parser (native_macro_parser registry)))
    (let ((next (native_macro_next registry reference)))
      (cond
        ((if (= (deref (field-pointer (parser_node parser reference) 'kind)) 7)
             (if (< 0 next) (= (deref (field-pointer tree 'remaining)) 0) nil) nil)
         (store (field-pointer tree 'remaining) 1) next)
        ((= (native_macro_declaration_p registry reference) 1)
         (if (= (native_macro_validate_declaration registry reference) 1) next 0))
        (t reference)))))

(defun native_macro_body_start (registry reference)
  (declare (type (ptr native_macro_registry) registry) (type usize reference) (returns usize))
  (let ((tree (deref (field-pointer registry 'tree))))
    (store (field-pointer tree 'cursor) reference)
    (store (field-pointer tree 'remaining) 0)
    (store (field-pointer tree 'last) 0)
    (while (if (= (deref (field-pointer registry 'error)) 0)
               (if (< 0 (deref (field-pointer tree 'cursor))) (= (deref (field-pointer tree 'last)) 0) nil) nil)
      (let ((form (deref (field-pointer tree 'cursor))))
        (let ((next (native_macro_body_prefix_step registry form)))
          (if (= form next) (store (field-pointer tree 'last) 1)
              (store (field-pointer tree 'cursor) next)))))
    (if (= (deref (field-pointer registry 'error)) 0) (deref (field-pointer tree 'cursor)) 0)))
