(include "bindings.lisp")
(defun native_macro_apply_definition (call definition form)
  (declare (type (ptr native_macro_call) call) (type usize definition form) (returns usize))
  (if (= (native_macro_prepare_call call definition form) 0) 0
      (let ((registry (deref (field-pointer call 'registry)))
            (tree (native_macro_tree call)))
        (let ((origin (deref (field-pointer tree 'origin))))
          (store (field-pointer tree 'origin) form)
          (let ((copy (native_macro_eval call (deref (field-pointer (native_macro_definition_at registry definition) 'body)))))
            (store (field-pointer tree 'origin) origin)
            copy)))))

(defun native_macroexpand_1 (call form result)
  (declare (type (ptr native_macro_call) call) (type usize form)
           (type (ptr native_macro_expansion) result)
           (returns c-int) (c-export :c))
  (store (field-pointer result 'form) form)
  (store (field-pointer result 'expanded) 0)
  (let ((registry (deref (field-pointer call 'registry)))
        (tree (native_macro_tree call))
        (parser (native_macro_call_parser call)))
    (if (< 0 (deref (field-pointer call 'error))) 0
        (if (= (native_tree_verify tree form) 0) (progn (native_macro_call_fail call 4) 0)
            (let ((node (parser_node parser form)))
              (if (if (= (deref (field-pointer node 'kind)) 1) nil t) 1
                  (let ((definition (native_macro_lookup registry
                                      (ast_symbol_identity parser (deref (field-pointer node 'first))))))
                    (if (= definition 0) 1
                        (let ((saved (deref (field-pointer parser 'count)))
                              (saved_error (deref (field-pointer parser 'error))))
                          (let ((copy (native_macro_apply_definition call definition form)))
                            (if (if (= copy 0) t (= (native_tree_verify tree copy) 0))
                                (progn
                                  (store (field-pointer call 'count) 0)
                                  (store (field-pointer parser 'count) saved)
                                  (store (field-pointer parser 'error) saved_error)
                                  (store (field-pointer (deref (field-pointer tree 'reader)) 'count) saved)
                                  (if (= (deref (field-pointer call 'error)) 0)
                                      (native_macro_call_fail call (deref (field-pointer tree 'error))) (wrap-cast usize 0))
                                  0)
                                (progn (store (field-pointer result 'form) copy)
                                       (store (field-pointer result 'expanded) 1) 1))))))))))))

(defun native_macroexpand_steps (call form result)
  (declare (type (ptr native_macro_call) call) (type usize form)
           (type (ptr native_macro_expansion) result) (returns c-int))
  (store (field-pointer result 'form) form)
  (store (field-pointer result 'expanded) 0)
  (let ((step (field-pointer call 'expansion)))
    (store (field-pointer step 'expanded) 1)
    (while (if (= (deref (field-pointer call 'error)) 0)
               (= (deref (field-pointer step 'expanded)) 1) nil)
      (if (= (native_macroexpand_1 call (deref (field-pointer result 'form)) step) 0)
          (wrap-cast usize 0)
          (if (= (deref (field-pointer step 'expanded)) 1)
              (if (< (deref (field-pointer call 'steps)) (deref (field-pointer call 'step_limit)))
                  (progn
                    (store (field-pointer call 'steps) (wrap+ (deref (field-pointer call 'steps)) 1))
                    (store (field-pointer result 'form) (deref (field-pointer step 'form)))
                    (store (field-pointer result 'expanded) 1)
                    (wrap-cast usize 1))
                  (native_macro_call_fail call 5))
              (wrap-cast usize 0))))
    (if (= (deref (field-pointer call 'error)) 0) 1 0)))

;; The repeated operation is transactional too; its embedded one-step scratch
;; must be distinct from RESULT.
(defun native_macroexpand (call form result)
  (declare (type (ptr native_macro_call) call) (type usize form)
           (type (ptr native_macro_expansion) result) (returns c-int) (c-export :c))
  (let ((parser (native_macro_call_parser call)) (tree (native_macro_tree call)))
    (let ((count (deref (field-pointer parser 'count)))
          (error (deref (field-pointer parser 'error))))
      (if (= (native_macroexpand_steps call form result) 1) 1
          (progn
            (let ((origin (native_macro_origin_reference tree (deref (field-pointer call 'origin)) 2048)))
              (store (field-pointer call 'origin) origin))
            (store (field-pointer call 'count) 0)
            (store (field-pointer parser 'count) count)
            (store (field-pointer parser 'error) error)
            (store (field-pointer (deref (field-pointer tree 'reader)) 'count) count)
            (store (field-pointer result 'form) form)
            (store (field-pointer result 'expanded) 0)
            0)))))
