(include "expressions.lisp")
(include "../../compile_scalar_types.lisp")

(defun native_macro_definition_form_p (context reference)
  (declare (type (ptr native_compile_context) context) (type usize reference) (returns c-int))
  (let ((parser (deref (field-pointer context 'parser))))
    (if (= (deref (field-pointer (parser_node parser reference) 'kind)) 1)
        (ast_builtin_word_p parser (deref (field-pointer context 'source))
            (deref (field-pointer (parser_node parser reference) 'first)) #x6f7263616d666564 0 8) 0)))

(defun native_macro_attach_unit (context)
  (declare (type (ptr native_compile_context) context) (returns c-int))
  (let ((tree (field-pointer context 'macro_tree))
        (registry (field-pointer context 'macro_registry))
        (call (field-pointer context 'macro_call))
        (parser (deref (field-pointer context 'parser))))
    (store (field-pointer tree 'parser) parser)
    (store (field-pointer tree 'reader) (deref (field-pointer parser 'environment)))
    (store (field-pointer tree 'origin) 0)
    (store (field-pointer tree 'depth) 0)
    (store (field-pointer tree 'limit) 128)
    (store (field-pointer tree 'cursor) 0)
    (store (field-pointer tree 'error) 0)
    (store (field-pointer tree 'remaining) 0)
    (store (field-pointer tree 'last) 0)
    (store (field-pointer registry 'parser) parser)
    (store (field-pointer registry 'source) (deref (field-pointer context 'source)))
    (store (field-pointer registry 'tree) tree)
    (store (field-pointer registry 'count) 0)
    (store (field-pointer registry 'error) 0)
    (store (field-pointer call 'registry) registry)
    (store (field-pointer call 'count) 0)
    (store (field-pointer call 'origin) 0)
    (store (field-pointer call 'error) 0)
    (store (field-pointer call 'steps) 0)
    (store (field-pointer call 'step_limit) 2048)
    (store (field-pointer (field-pointer call 'expansion) 'form) 0)
    (store (field-pointer (field-pointer call 'expansion) 'expanded) 0)
    (store (field-pointer (field-pointer call 'repeated) 'form) 0)
    (store (field-pointer (field-pointer call 'repeated) 'expanded) 0)
    1))

(defun native_macro_copy_function_prefix (call copy reference count)
  (declare (type (ptr native_macro_call) call) (type usize copy reference count) (returns usize))
  (if (= count 0) reference
      (if (= (native_macro_append_static call copy reference) 0) 0
          (native_macro_copy_function_prefix call copy
             (native_macro_next (deref (field-pointer call 'registry)) reference) (wrap- count 1)))))

(defun native_macro_function_body_start (call form)
  (declare (type (ptr native_macro_call) call) (type usize form) (returns usize))
  (let ((parser (native_macro_call_parser call)))
    (let ((head (deref (field-pointer (parser_node parser form) 'first))))
      (if (= (native_macro_head_p call form #x6e75666564 0 5) 1)
          (let ((name (native_macro_next (deref (field-pointer call 'registry)) head)))
            (let ((parameters (native_macro_next (deref (field-pointer call 'registry)) name)))
              (let ((declaration (native_macro_next (deref (field-pointer call 'registry)) parameters)))
                (native_macro_next (deref (field-pointer call 'registry)) declaration))))
          0))))

(defun native_macro_clone_function (call form)
  (declare (type (ptr native_macro_call) call) (type usize form) (returns usize))
  (if (= (native_macro_function_body_start call form) 0) (native_macro_call_fail call 4)
      (let ((parser (native_macro_call_parser call)))
        (let ((copy (native_macro_clone_shell call form)))
          (let ((body (native_macro_copy_function_prefix call copy
                         (deref (field-pointer (parser_node parser form) 'first)) 4)))
            (if (= body 0) (native_macro_call_fail call 4)
                (if (= (native_macro_expression_arguments call copy body) 1) copy (wrap-cast usize 0))))))))

(defun native_expand_function_macros (context form)
  (declare (type (ptr native_compile_context) context) (type usize form)
           (returns usize) (c-export :c))
  (let ((registry (field-pointer context 'macro_registry)))
    (if (= (deref (field-pointer registry 'count)) 0) form
        (let ((call (field-pointer context 'macro_call))
              (tree (field-pointer context 'macro_tree))
              (parser (deref (field-pointer context 'parser))))
          (store (field-pointer call 'steps) 0)
          (if (= (native_tree_verify tree form) 0) (native_macro_call_fail call 4)
              (let ((saved (deref (field-pointer parser 'count)))
                    (saved_error (deref (field-pointer parser 'error))))
                (let ((copy (native_macro_clone_function call form)))
                  (if (if (= copy 0) t (= (native_tree_verify tree copy) 0))
                      (progn
                        (if (= (deref (field-pointer call 'error)) 0)
                            (native_macro_call_fail call (deref (field-pointer tree 'error))) (wrap-cast usize 0))
                        (let ((origin (native_macro_origin_reference tree (deref (field-pointer call 'origin)) 2048)))
                          (store (field-pointer call 'origin) origin))
                        (store (field-pointer parser 'count) saved)
                        (store (field-pointer parser 'error) saved_error)
                        (store (field-pointer (deref (field-pointer tree 'reader)) 'count) saved)
                        (wrap-cast usize 0))
                      copy))))))))
