(include "aux_bindings.lisp")

(defun native_macro_implicit_key_matches_p (registry parameter symbol)
  (declare (type (ptr native_macro_registry) registry) (type usize parameter symbol) (returns c-int))
  (let ((parser (native_macro_parser registry)))
    (let ((env (deref (field-pointer (deref (field-pointer parser 'environment)) 'environment))))
      (let ((key (native_ct_symbol_at env symbol))
            (name (ast_symbol_identity parser (native_macro_key_name registry parameter))))
        (if (= (deref (field-pointer key 'package)) (deref (field-pointer env 'keyword_package)))
            (native_ct_name_matches env (deref (field-pointer key 'name)) (deref (field-pointer key 'length))
                                   (native_ct_symbol_name env name)
                                   (deref (field-pointer (native_ct_symbol_at env name) 'length))) 0)))))

(defun native_macro_key_matches_p (call parameter argument)
  (declare (type (ptr native_macro_call) call) (type usize parameter argument) (returns c-int))
  (let ((registry (deref (field-pointer call 'registry))) (parser (native_macro_call_parser call)))
    (let ((symbol (ast_symbol_identity parser argument)) (explicit (native_macro_key_explicit registry parameter)))
      (if (= symbol 0) 0
          (if (< 0 explicit)
              (if (= symbol (ast_symbol_identity parser explicit)) 1 0)
              (native_macro_implicit_key_matches_p registry parameter symbol))))))

(defun native_macro_allow_key_name_p (call argument index)
  (declare (type (ptr native_macro_call) call) (type usize argument index) (returns c-int))
  (let ((parser (native_macro_call_parser call)))
    (let ((symbol (ast_symbol_identity parser argument)))
      (if (= symbol 0) 0
          (let ((env (deref (field-pointer (deref (field-pointer parser 'environment)) 'environment))))
            (let ((key (native_ct_symbol_at env symbol)))
              (if (if (= (deref (field-pointer key 'package)) (deref (field-pointer env 'keyword_package)))
                      (= (deref (field-pointer key 'length)) 16) nil)
                  (if (= index 16) 1
                      (if (= (deref (pointer+ (native_ct_symbol_name env symbol) (wrap-cast isize index)))
                             (native_ct_seed_word_byte #x544f2d574f4c4c41 #x5359454b2d524548 0 0 0 index))
                          (native_macro_allow_key_name_p call argument (wrap+ index 1)) 0)) 0)))))))

(defun native_macro_key_pairs_p (call arguments)
  (declare (type (ptr native_macro_call) call) (type usize arguments) (returns c-int))
  (let ((registry (deref (field-pointer call 'registry))) (tree (native_macro_tree call)))
    (store (field-pointer tree 'cursor) arguments)
    (while (if (= (deref (field-pointer call 'error)) 0) (< 0 (deref (field-pointer tree 'cursor))) nil)
      (let ((value (native_macro_next registry (deref (field-pointer tree 'cursor)))))
        (if (= value 0) (native_macro_call_fail call 2)
            (store (field-pointer tree 'cursor) (native_macro_next registry value)))))
    (if (= (deref (field-pointer call 'error)) 0) 1 0)))

(defun native_macro_key_value (call parameter arguments)
  (declare (type (ptr native_macro_call) call) (type usize parameter arguments) (returns usize))
  (let ((registry (deref (field-pointer call 'registry))) (tree (native_macro_tree call)))
    (store (field-pointer tree 'cursor) arguments)
    (store (field-pointer tree 'last) 0)
    (while (if (= (deref (field-pointer tree 'last)) 0) (< 0 (deref (field-pointer tree 'cursor))) nil)
      (let ((argument (deref (field-pointer tree 'cursor))))
        (let ((value (native_macro_next registry argument)))
          (if (= (native_macro_key_matches_p call parameter argument) 1)
              (store (field-pointer tree 'last) value)
              (store (field-pointer tree 'cursor) (native_macro_next registry value))))))
    (deref (field-pointer tree 'last))))

(defun native_macro_keys_allow_p (call parameters)
  (declare (type (ptr native_macro_call) call) (type usize parameters) (returns c-int))
  (let ((registry (deref (field-pointer call 'registry))) (tree (native_macro_tree call)))
    (store (field-pointer tree 'cursor) parameters)
    (store (field-pointer tree 'last) 0)
    (while (if (= (deref (field-pointer tree 'last)) 0) (< 0 (deref (field-pointer tree 'cursor))) nil)
      (let ((parameter (deref (field-pointer tree 'cursor))))
        (cond
          ((= (native_macro_aux_marker_p registry parameter) 1) (store (field-pointer tree 'cursor) 0))
          ((= (native_macro_allow_keys_marker_p registry parameter) 1) (store (field-pointer tree 'last) 1))
          (t (store (field-pointer tree 'cursor) (native_macro_next registry parameter))))))
    (if (= (deref (field-pointer tree 'last)) 0) 0 1)))

(defun native_macro_arguments_allow_p (call arguments)
  (declare (type (ptr native_macro_call) call) (type usize arguments) (returns c-int))
  (let ((registry (deref (field-pointer call 'registry))) (tree (native_macro_tree call)))
    (store (field-pointer tree 'cursor) arguments)
    (store (field-pointer tree 'last) 0)
    (store (field-pointer tree 'remaining) 0)
    (while (if (= (deref (field-pointer tree 'remaining)) 0) (< 0 (deref (field-pointer tree 'cursor))) nil)
      (let ((argument (deref (field-pointer tree 'cursor))))
        (let ((value (native_macro_next registry argument)))
          (if (= (native_macro_allow_key_name_p call argument 0) 1)
              (progn (store (field-pointer tree 'remaining) 1)
                     (store (field-pointer tree 'last) (if (= (native_macro_value_false_p call value) 1) 0 1)))
              (store (field-pointer tree 'cursor) (native_macro_next registry value))))))
    (if (= (deref (field-pointer tree 'last)) 0) 0 1)))

(defun native_macro_key_known_p (call parameters argument)
  (declare (type (ptr native_macro_call) call) (type usize parameters argument) (returns c-int))
  (let ((registry (deref (field-pointer call 'registry))) (tree (native_macro_tree call)))
    (store (field-pointer tree 'cursor) parameters)
    (store (field-pointer tree 'last) 0)
    (while (if (= (deref (field-pointer tree 'last)) 0) (< 0 (deref (field-pointer tree 'cursor))) nil)
      (let ((parameter (deref (field-pointer tree 'cursor))))
        (cond
          ((if (= (native_macro_aux_marker_p registry parameter) 1) t
               (= (native_macro_allow_keys_marker_p registry parameter) 1)) (store (field-pointer tree 'cursor) 0))
          ((= (native_macro_key_matches_p call parameter argument) 1) (store (field-pointer tree 'last) 1))
          (t (store (field-pointer tree 'cursor) (native_macro_next registry parameter))))))
    (if (= (deref (field-pointer tree 'last)) 0) 0 1)))

(defun native_macro_key_arguments_p (call parameters arguments)
  (declare (type (ptr native_macro_call) call) (type usize parameters arguments) (returns c-int))
  (let ((registry (deref (field-pointer call 'registry))) (tree (native_macro_tree call)))
    (store (field-pointer tree 'cursor) arguments)
    (while (if (= (deref (field-pointer call 'error)) 0) (< 0 (deref (field-pointer tree 'cursor))) nil)
      (let ((argument (deref (field-pointer tree 'cursor))))
        (let ((next (native_macro_next registry (native_macro_next registry argument))))
          (if (if (= (native_macro_allow_key_name_p call argument 0) 1) t
                  (= (native_macro_key_known_p call parameters argument) 1))
              (store (field-pointer tree 'cursor) next) (native_macro_call_fail call 2)))))
    (if (= (deref (field-pointer call 'error)) 0) 1 0)))

(defun native_macro_bind_key (call parameter arguments)
  (declare (type (ptr native_macro_call) call) (type usize parameter arguments) (returns c-int))
  (let ((argument (native_macro_key_value call parameter arguments)))
    (let ((value (if (< 0 argument) argument
                     (native_macro_default_value call parameter (native_macro_optional_default call parameter)))))
      (if (= value 0) 0
          (let ((registry (deref (field-pointer call 'registry))))
            (if (= (native_macro_add_binding call (native_macro_key_name registry parameter) value) 0) 0
                (let ((supplied (native_macro_next registry (native_macro_optional_default call parameter))))
                  (if (= supplied 0) 1
                      (let ((flag (native_macro_boolean_form call supplied (if (= argument 0) 0 1))))
                        (if (= flag 0) 0 (native_macro_add_binding call supplied flag)))))))))))

(defun native_macro_bind_key_parameters (call parameters arguments)
  (declare (type (ptr native_macro_call) call) (type usize parameters arguments) (returns c-int))
  (let ((registry (deref (field-pointer call 'registry))) (tree (native_macro_tree call)))
    (store (field-pointer tree 'cursor) parameters)
    (while (if (= (deref (field-pointer call 'error)) 0) (< 0 (deref (field-pointer tree 'cursor))) nil)
      (let ((parameter (deref (field-pointer tree 'cursor))))
        (let ((next (native_macro_next registry parameter)))
          (cond
            ((= (native_macro_aux_marker_p registry parameter) 1)
             (native_macro_bind_aux call next) (store (field-pointer tree 'cursor) 0))
            ((= (native_macro_allow_keys_marker_p registry parameter) 1) (store (field-pointer tree 'cursor) next))
            (t (native_macro_bind_key call parameter arguments) (store (field-pointer tree 'cursor) next))))))
    (if (= (deref (field-pointer call 'error)) 0) 1 0)))

(defun native_macro_bind_keys (call parameters arguments)
  (declare (type (ptr native_macro_call) call) (type usize parameters arguments) (returns c-int))
  (if (= (native_macro_key_pairs_p call arguments) 0) 0
      (if (if (= (native_macro_keys_allow_p call parameters) 1) t
              (= (native_macro_arguments_allow_p call arguments) 1))
          (native_macro_bind_key_parameters call parameters arguments)
          (if (= (native_macro_key_arguments_p call parameters arguments) 1)
              (native_macro_bind_key_parameters call parameters arguments) 0))))
