(include "tree_verify.lisp")

(defun native_tree_copy_identity (context source destination)
  (declare (type (ptr native_tree_context) context) (type usize source destination)
           (returns c-int))
  (let ((reader (deref (field-pointer context 'reader))))
    (let ((old (pointer+ (deref (field-pointer reader 'identities))
                         (wrap-cast isize (wrap- source 1))))
          (new (pointer+ (deref (field-pointer reader 'identities))
                         (wrap-cast isize (wrap- destination 1)))))
      (store (field-pointer new 'symbol) (deref (field-pointer old 'symbol)))
      (store (field-pointer new 'origin)
             (if (= (deref (field-pointer context 'origin)) 0)
                 (deref (field-pointer old 'origin))
                 (deref (field-pointer context 'origin))))
      (store (field-pointer reader 'count) destination)
      1)))

(defun native_tree_copy_children (context parent reference)
  (declare (type (ptr native_tree_context) context) (type usize parent reference)
           (returns c-int))
  (let ((parser (deref (field-pointer context 'parser))))
    (store (field-pointer context 'cursor) reference)
    (while (if (= (deref (field-pointer context 'error)) 0)
               (< 0 (deref (field-pointer context 'cursor))) nil)
      (let ((source (deref (field-pointer context 'cursor))))
        (let ((next (deref (field-pointer (parser_node parser source) 'next)))
              (copy (native_tree_copy_node context source)))
          (if (= copy 0) (wrap-cast usize 0) (parser_append parser parent copy))
          (store (field-pointer context 'cursor) next))))
    (if (= (deref (field-pointer context 'error)) 0) 1 0)))

(defun native_tree_allocate_copy (context reference)
  (declare (type (ptr native_tree_context) context) (type usize reference)
           (returns usize))
  (let ((parser (deref (field-pointer context 'parser))))
    (let ((node (parser_node parser reference)))
      (let ((copy (parser_new_node parser (deref (field-pointer node 'kind))
                   (deref (field-pointer node 'start)) (deref (field-pointer node 'length)))))
        (if (= copy 0) (native_tree_fail context 1)
            (progn
              (native_tree_copy_identity context reference copy)
              (store (field-pointer context 'depth) (wrap+ (deref (field-pointer context 'depth)) 1))
              (native_tree_copy_children context copy (deref (field-pointer node 'first)))
              (store (field-pointer context 'depth) (wrap- (deref (field-pointer context 'depth)) 1))
              (if (= (deref (field-pointer context 'error)) 0) copy (wrap-cast usize 0))))))))

(defun native_tree_copy_node (context reference)
  (declare (type (ptr native_tree_context) context) (type usize reference)
           (returns usize))
  (let ((parser (deref (field-pointer context 'parser)))
        (reader (deref (field-pointer context 'reader))))
    (cond
      ((< 0 (deref (field-pointer context 'error))) 0)
      ((= reference 0) (native_tree_fail context 4))
      ((< (deref (field-pointer reader 'count)) reference) (native_tree_fail context 4))
      ((if (< (deref (field-pointer context 'depth)) (deref (field-pointer context 'limit))) nil t)
       (native_tree_fail context 5))
      ((if (< (deref (field-pointer parser 'count)) (deref (field-pointer reader 'capacity))) nil t)
       (native_tree_fail context 1))
      (t (native_tree_allocate_copy context reference)))))

(defun native_tree_copy (context reference)
  (declare (type (ptr native_tree_context) context) (type usize reference)
           (returns usize) (c-export :c))
  (if (= (native_tree_verify context reference) 0) 0
      (let ((parser (deref (field-pointer context 'parser)))
            (reader (deref (field-pointer context 'reader))))
        (let ((saved (deref (field-pointer parser 'count)))
              (saved_error (deref (field-pointer parser 'error))))
          (let ((copy (native_tree_copy_node context reference)))
            (if (= copy 0)
                (progn (store (field-pointer parser 'count) saved)
                       (store (field-pointer parser 'error) saved_error)
                       (store (field-pointer reader 'count) saved)
                       (wrap-cast usize 0))
                copy))))))

(defun native_macro_origin_reference (tree reference budget)
  (declare (type (ptr native_tree_context) tree) (type usize reference budget) (returns usize))
  (if (= budget 0) 0
      (if (= reference 0) 0
          (let ((reader (deref (field-pointer tree 'reader))))
            (if (< (deref (field-pointer reader 'count)) reference) 0
                (let ((origin (deref (field-pointer
                             (pointer+ (deref (field-pointer reader 'identities))
                                       (wrap-cast isize (wrap- reference 1))) 'origin))))
                  (if (= origin reference) reference
                      (if (< origin reference)
                          (native_macro_origin_reference tree origin (wrap- budget 1)) 0))))))))

