(include "tree_base.lisp")

(defun native_tree_valid_reference_p (context reference)
  (declare (type (ptr native_tree_context) context) (type usize reference)
           (returns c-int))
  (if (= reference 0) 0
      (if (< (deref (field-pointer (deref (field-pointer context 'reader)) 'count)) reference) 0
          (if (< (deref (field-pointer (deref (field-pointer context 'parser)) 'count)) reference) 0 1))))

(defun native_tree_verify_identity (context reference)
  (declare (type (ptr native_tree_context) context) (type usize reference)
           (returns c-int))
  (let ((reader (deref (field-pointer context 'reader))))
    (let ((identity (pointer+ (deref (field-pointer reader 'identities))
                              (wrap-cast isize (wrap- reference 1)))))
      (let ((symbol (deref (field-pointer identity 'symbol)))
            (node (parser_node (deref (field-pointer context 'parser)) reference)))
        (cond
          ((= (native_tree_valid_reference_p context (deref (field-pointer identity 'origin))) 0)
           (progn (native_tree_fail context 4) 0))
          ((< reference (deref (field-pointer identity 'origin)))
           (progn (native_tree_fail context 4) 0))
          ((< (deref (field-pointer (deref (field-pointer reader 'environment)) 'symbol_count)) symbol)
           (progn (native_tree_fail context 4) 0))
          ((if (< 0 symbol) (if (= (deref (field-pointer node 'kind)) 8) nil t) nil)
           (progn (native_tree_fail context 4) 0))
          (t 1))))))

(defun native_tree_verify_span (context reference)
  (declare (type (ptr native_tree_context) context) (type usize reference) (returns c-int))
  (let ((parser (deref (field-pointer context 'parser))))
    (let ((node (parser_node parser reference))
          (length (deref (field-pointer (deref (field-pointer parser 'scanner)) 'length))))
      (let ((start (deref (field-pointer node 'start))))
        (if (< length start) (progn (native_tree_fail context 4) 0)
            (if (< (wrap- length start) (deref (field-pointer node 'length)))
                (progn (native_tree_fail context 4) 0) 1))))))

(defun native_tree_verify_children (context reference child)
  (declare (type (ptr native_tree_context) context) (type usize reference child)
           (returns c-int))
  (let ((parser (deref (field-pointer context 'parser))))
    (store (field-pointer context 'cursor) child)
    (store (field-pointer context 'last) 0)
    (while (if (= (deref (field-pointer context 'error)) 0)
               (< 0 (deref (field-pointer context 'cursor))) nil)
      (let ((current (deref (field-pointer context 'cursor))))
        (if (= (native_tree_verify_node context current) 0) (wrap-cast usize 0)
            (progn
              (store (field-pointer context 'cursor)
                     (deref (field-pointer (parser_node parser current) 'next)))
              (store (field-pointer context 'last) current)))))
    (if (= (deref (field-pointer context 'error)) 0)
        (if (= (deref (field-pointer context 'last))
               (deref (field-pointer (parser_node parser reference) 'last))) 1
            (progn (native_tree_fail context 4) 0)) 0)))

(defun native_tree_verify_shape (context reference)
  (declare (type (ptr native_tree_context) context) (type usize reference)
           (returns c-int))
  (let ((parser (deref (field-pointer context 'parser))))
    (let ((node (parser_node parser reference)))
      (let ((kind (deref (field-pointer node 'kind)))
            (first (deref (field-pointer node 'first))))
        (cond
          ((= kind 1)
           (native_tree_verify_children context reference first))
          ((if (= kind 3) t (if (= kind 4) t (if (= kind 5) t (if (= kind 6) t (= kind 9)))))
           (if (= (native_tree_valid_reference_p context first) 0) (progn (native_tree_fail context 4) 0)
               (if (= (deref (field-pointer node 'last)) first)
                   (if (= (deref (field-pointer (parser_node parser first) 'next)) 0)
                       (native_tree_verify_node context first) (progn (native_tree_fail context 4) 0))
                   (progn (native_tree_fail context 4) 0))))
          ((if (= kind 7) t (= kind 8))
           (if (if (= first 0) (= (deref (field-pointer node 'last)) 0) nil) 1
               (progn (native_tree_fail context 4) 0)))
          (t (progn (native_tree_fail context 4) 0)))))))

(defun native_tree_verify_node (context reference)
  (declare (type (ptr native_tree_context) context) (type usize reference) (returns c-int))
  (cond
    ((< 0 (deref (field-pointer context 'error))) 0)
    ((= (native_tree_valid_reference_p context reference) 0) (progn (native_tree_fail context 4) 0))
    ((if (< (deref (field-pointer context 'depth)) (deref (field-pointer context 'limit))) nil t)
     (progn (native_tree_fail context 5) 0))
    ((= (native_tree_verify_identity context reference) 0) 0)
    ((= (native_tree_verify_span context reference) 0) 0)
    ((= (deref (field-pointer context 'remaining)) 0) (progn (native_tree_fail context 4) 0))
    (t
     (store (field-pointer context 'remaining) (wrap- (deref (field-pointer context 'remaining)) 1))
     (store (field-pointer context 'depth) (wrap+ (deref (field-pointer context 'depth)) 1))
     (let ((valid (native_tree_verify_shape context reference)))
       (store (field-pointer context 'depth) (wrap- (deref (field-pointer context 'depth)) 1))
       valid))))

(defun native_tree_tables_valid_p (context)
  (declare (type (ptr native_tree_context) context) (returns c-int))
  (let ((parser (deref (field-pointer context 'parser)))
        (reader (deref (field-pointer context 'reader))))
    (if (if (= (ptr-address parser) 0) t (= (ptr-address reader) 0)) 0
        (cond
          ((if (= (ptr-address (deref (field-pointer parser 'environment))) (ptr-address reader)) nil t) 0)
          ((= (ptr-address (deref (field-pointer reader 'environment))) 0) 0)
          ((= (ptr-address (deref (field-pointer reader 'identities))) 0) 0)
          ((= (ptr-address (deref (field-pointer parser 'scanner))) 0) 0)
          ((= (ptr-address (deref (field-pointer parser 'nodes))) 0) 0)
          ((< (deref (field-pointer parser 'capacity)) (deref (field-pointer parser 'count))) 0)
          ((< (deref (field-pointer reader 'capacity)) (deref (field-pointer reader 'count))) 0)
          ((if (= (deref (field-pointer parser 'count)) (deref (field-pointer reader 'count))) nil t) 0)
          (t 1)))))

(defun native_tree_verify (context reference)
  (declare (type (ptr native_tree_context) context) (type usize reference)
           (returns c-int) (c-export :c))
  (if (= (native_tree_tables_valid_p context) 0) (progn (native_tree_fail context 4) 0)
      (progn
        (store (field-pointer context 'remaining)
               (deref (field-pointer (deref (field-pointer context 'parser)) 'count)))
        (native_tree_verify_node context reference))))
