(in-package #:psl.ir)

(defun simple-inline-body (function)
  (let ((blocks (ssa-function-blocks function)))
    (when (and (= (length blocks) 1)
               (eq (ssa-terminator-op
                    (ssa-block-terminator (first blocks))) :return)
               (<= (length (ssa-block-instructions (first blocks))) 12)
               (every (lambda (instruction)
                        (member (ssa-instruction-op instruction)
                                '(:argument :constant :binary :copy :cast
                                  :integer-cast)))
                      (ssa-block-instructions (first blocks))))
      (first blocks))))

(defun remap-value (id mapping)
  (multiple-value-bind (mapped found) (gethash id mapping)
    (unless found (fail "inliner could not map SSA value ~D" id))
    mapped))

(defun inline-call (caller call callee)
  (let ((mapping (make-hash-table))
        (clones nil)
        (body (simple-inline-body callee)))
    (dolist (instruction (ssa-block-instructions body))
      (if (eq (ssa-instruction-op instruction) :argument)
          (setf (gethash (ssa-instruction-id instruction) mapping)
                (nth (ssa-instruction-value instruction)
                     (ssa-instruction-args call)))
          (let ((new-id (ssa-function-next-value caller)))
            (incf (ssa-function-next-value caller))
            (push (make-ssa-instruction
                   :id new-id :op (ssa-instruction-op instruction)
                   :type (ssa-instruction-type instruction)
                   :value (ssa-instruction-value instruction)
                   :args (mapcar (lambda (id) (remap-value id mapping))
                                 (ssa-instruction-args instruction))
                   :source (ssa-instruction-source call))
                  clones)
            (setf (gethash (ssa-instruction-id instruction) mapping)
                  new-id))))
    (let ((result (first (ssa-terminator-args
                          (ssa-block-terminator body)))))
      (setf (ssa-instruction-op call) :copy
            (ssa-instruction-value call) nil
            (ssa-instruction-args call)
            (list (remap-value result mapping))))
    (nreverse clones)))

(defun inline-simple-functions (functions)
  (let ((callees (make-hash-table :test #'equal)))
    (dolist (function functions)
      (when (simple-inline-body function)
        (setf (gethash (ssa-function-name function) callees) function)))
    (dolist (caller functions)
      (dolist (block (ssa-function-blocks caller))
        (let ((rewritten nil))
          (dolist (instruction (ssa-block-instructions block))
            (let ((callee (and (eq (ssa-instruction-op instruction) :call)
                               (gethash (ssa-instruction-value instruction)
                                        callees))))
              (when callee
                (setf rewritten
                      (nconc rewritten (inline-call caller instruction callee))))
              (setf rewritten (nconc rewritten (list instruction)))))
          (setf (ssa-block-instructions block) rewritten)))))
  functions)

(defun wrap-integer (value type pointer-bits)
  (let* ((width (type-width type pointer-bits))
         (modulus (ash 1 width))
         (bits (mod value modulus)))
    (if (and (signed-type-p type) (logbitp (1- width) bits))
        (- bits modulus)
        bits)))

(defun folded-binary (operation left right pointer-bits)
  (let ((operator (car operation))
        (type (cdr operation)))
    (cond
      ((equal operator "wrap+")
       (wrap-integer (+ left right) type pointer-bits))
      ((equal operator "wrap-")
       (wrap-integer (- left right) type pointer-bits))
      ((equal operator "wrap*")
       (wrap-integer (* left right) type pointer-bits))
      ((equal operator "bits-and") (logand left right))
      ((equal operator "shr64") (ash left (- (mod right 64))))
      ((equal operator "=") (if (= left right) 1 0))
      ((equal operator "<") (if (< left right) 1 0))
      (t (fail "unknown constant-fold operation ~A" operator)))))

(defun known-constants (ids constants)
  (let ((values nil))
    (dolist (id ids (values (nreverse values) t))
      (multiple-value-bind (value found) (gethash id constants)
        (unless found (return-from known-constants (values nil nil)))
        (push value values)))))

(defun replace-with-constant (instruction value constants)
  (setf (ssa-instruction-op instruction) :constant
        (ssa-instruction-value instruction) value
        (ssa-instruction-args instruction) nil
        (gethash (ssa-instruction-id instruction) constants) value)
  t)

(defun fold-instruction (instruction constants pointer-bits)
  (let ((op (ssa-instruction-op instruction))
        (type (ssa-instruction-type instruction)))
    (case op
      (:constant
       (setf (gethash (ssa-instruction-id instruction) constants)
             (ssa-instruction-value instruction))
       nil)
      ((:copy :phi)
       (when (or (integer-type-p type) (eq type :boolean))
         (multiple-value-bind (values known)
             (known-constants
              (if (eq op :phi)
                  (mapcar #'cdr (ssa-instruction-args instruction))
                  (ssa-instruction-args instruction))
              constants)
           (when (and known values (every (lambda (item) (= item (first values)))
                                          (rest values)))
             (replace-with-constant instruction (first values) constants)))))
      (:binary
       (multiple-value-bind (values known)
           (known-constants (ssa-instruction-args instruction) constants)
         (when known
           (replace-with-constant
            instruction
            (folded-binary (ssa-instruction-value instruction)
                           (first values) (second values) pointer-bits)
            constants))))
      (otherwise nil))))

(defun fold-branch (block constants)
  (let ((terminator (ssa-block-terminator block)))
    (when (eq (ssa-terminator-op terminator) :branch)
      (multiple-value-bind (value known)
          (gethash (first (ssa-terminator-args terminator)) constants)
        (when known
          (setf (ssa-terminator-op terminator) :jump
                (ssa-terminator-args terminator) nil
                (ssa-terminator-targets terminator)
                (list (if (zerop value)
                          (second (ssa-terminator-targets terminator))
                          (first (ssa-terminator-targets terminator)))))
          t)))))

(defun prune-unreachable-blocks (function)
  (let ((reachable (reachable-blocks function)))
    (setf (ssa-function-blocks function)
          (remove-if-not (lambda (block)
                           (gethash (ssa-block-id block) reachable))
                         (ssa-function-blocks function)))
    (dolist (block (ssa-function-blocks function))
      (dolist (instruction (ssa-block-instructions block))
        (when (eq (ssa-instruction-op instruction) :phi)
          (setf (ssa-instruction-args instruction)
                (remove-if-not
                 (lambda (edge) (gethash (car edge) reachable))
                 (ssa-instruction-args instruction)))
          (when (= (length (ssa-instruction-args instruction)) 1)
            (setf (ssa-instruction-op instruction) :copy
                  (ssa-instruction-args instruction)
                  (list (cdar (ssa-instruction-args instruction)))))))))
  function)

(defun fold-constants (function pointer-bits)
  (let ((constants (make-hash-table))
        (changed t))
    (loop while changed
          do (setf changed nil)
             (dolist (block (ssa-function-blocks function))
               (dolist (instruction (ssa-block-instructions block))
                 (when (fold-instruction instruction constants pointer-bits)
                   (setf changed t)))
               (when (fold-branch block constants)
                 (setf changed t)))
             (when changed (prune-unreachable-blocks function))))
  function)

(defun effectful-instruction-p (instruction)
  (or (member (ssa-instruction-op instruction) '(:call :store))
      (and (eq (ssa-instruction-op instruction) :load)
           (ssa-instruction-value instruction))))

(defun mark-live-value (id definitions live)
  (unless (gethash id live)
    (let ((instruction (gethash id definitions)))
      (unless instruction (fail "dead-code pass found missing SSA value ~D" id))
      (setf (gethash id live) t)
      (dolist (dependency
               (if (eq (ssa-instruction-op instruction) :phi)
                   (mapcar #'cdr (ssa-instruction-args instruction))
                   (ssa-instruction-args instruction)))
        (mark-live-value dependency definitions live)))))

(defun eliminate-dead-code (function)
  (let ((definitions (ssa-definitions function))
        (live (make-hash-table)))
    (dolist (block (ssa-function-blocks function))
      (dolist (id (ssa-terminator-args (ssa-block-terminator block)))
        (mark-live-value id definitions live))
      (dolist (instruction (ssa-block-instructions block))
        (when (effectful-instruction-p instruction)
          (mark-live-value (ssa-instruction-id instruction)
                           definitions live))))
    (dolist (block (ssa-function-blocks function))
      (setf (ssa-block-instructions block)
            (remove-if-not
             (lambda (instruction)
               (gethash (ssa-instruction-id instruction) live))
             (ssa-block-instructions block)))))
  function)

(defun optimize-functions (functions pointer-bits)
  (inline-simple-functions functions)
  (dolist (function functions)
    (fold-constants function pointer-bits)
    (eliminate-dead-code function))
  functions)
