(load (merge-pathnames "load.lisp" *load-truename*))

(in-package #:cl-user)

(defstruct cli-options
  source output compile-only
  (kind :executable)
  (emit-specified-p nil)
  (link-inputs nil)
  (target "x86_64-linux-gnu")
  (profile "freestanding")
  startup linker-script (entry "_start") map-file
  (optimize t)
  (dump-ir nil))

(defun usage (&optional (stream *standard-output*))
  (format stream "Usage: pslcc [-c|--emit=exe|static|shared] SOURCE.lisp -o OUTPUT [--link-input=FILE]... [--target=TRIPLE] [--profile=PROFILE] [-O0|-O1] [--dump-ir=hir|ssa|lir|all]~%")
  (format stream "Freestanding link: [--startup=linux-exit|qemu-virt] [--entry=SYMBOL] [--linker-script=FILE] [--map=FILE]~%")
  (format stream "Targets: x86_64-linux-gnu, x86_64-none-elf, x86_64-windows-gnu, aarch64-linux-gnu, riscv64-linux-gnu, riscv64-none-elf~%")
  (format stream "Profiles: hosted, freestanding~%"))

(defun required-value (option remaining)
  (unless remaining (error "~A requires a value" option))
  (values (first remaining) (rest remaining)))

(defun parse-output-kind (value)
  (cond ((equal value "exe") :executable)
        ((equal value "static") :static)
        ((equal value "shared") :shared)
        (t (error "unknown output kind ~A" value))))

(defun apply-option (argument remaining options)
  (cond
    ((equal argument "-c")
     (setf (cli-options-compile-only options) t))
    ((equal argument "-O0")
     (setf (cli-options-optimize options) nil))
    ((equal argument "-O1")
     (setf (cli-options-optimize options) t))
    ((equal argument "-o")
     (multiple-value-bind (value rest) (required-value argument remaining)
       (setf (cli-options-output options) value
             remaining rest)))
    ((equal argument "--link-input")
     (multiple-value-bind (value rest) (required-value argument remaining)
       (push value (cli-options-link-inputs options))
       (setf remaining rest)))
    ((and (<= 13 (length argument))
          (string= argument "--link-input=" :end1 13))
     (push (subseq argument 13) (cli-options-link-inputs options)))
    ((and (<= 7 (length argument))
          (string= argument "--emit=" :end1 7))
     (setf (cli-options-kind options)
           (parse-output-kind (subseq argument 7))
           (cli-options-emit-specified-p options) t))
    ((equal argument "--target")
     (multiple-value-bind (value rest) (required-value argument remaining)
       (setf (cli-options-target options) value
             remaining rest)))
    ((equal argument "--profile")
     (multiple-value-bind (value rest) (required-value argument remaining)
       (setf (cli-options-profile options) value
             remaining rest)))
    ((and (<= 9 (length argument))
          (string= argument "--target=" :end1 9))
     (setf (cli-options-target options) (subseq argument 9)))
    ((and (<= 10 (length argument))
          (string= argument "--profile=" :end1 10))
     (setf (cli-options-profile options) (subseq argument 10)))
    ((and (<= 10 (length argument))
          (string= argument "--startup=" :end1 10))
     (setf (cli-options-startup options)
           (let ((name (subseq argument 10)))
             (cond ((equal name "linux-exit") :linux-exit)
                   ((equal name "qemu-virt") :qemu-virt)
                   (t (error "unknown startup ~A" name))))))
    ((and (<= 8 (length argument))
          (string= argument "--entry=" :end1 8))
     (setf (cli-options-entry options) (subseq argument 8)))
    ((and (<= 16 (length argument))
          (string= argument "--linker-script=" :end1 16))
     (setf (cli-options-linker-script options) (subseq argument 16)))
    ((and (<= 6 (length argument))
          (string= argument "--map=" :end1 6))
     (setf (cli-options-map-file options) (subseq argument 6)))
    ((and (<= 10 (length argument))
          (string= argument "--dump-ir=" :end1 10))
     (let ((stage (subseq argument 10)))
       (setf (cli-options-dump-ir options)
             (cond ((equal stage "hir") '(:hir))
                   ((equal stage "ssa") '(:ssa))
                   ((equal stage "lir") '(:lir))
                   ((equal stage "all") '(:hir :ssa :lir))
                   (t (error "unknown IR dump mode ~A" stage))))))
    ((member argument '("-h" "--help") :test #'equal)
     (usage)
     (sb-ext:exit :code 0))
    ((and (plusp (length argument)) (char= (char argument 0) #\-))
     (error "unknown option ~A" argument))
    ((null (cli-options-source options))
     (setf (cli-options-source options) argument))
    (t (error "unexpected argument ~A" argument)))
  remaining)

(defun parse-arguments (arguments)
  (let ((options (make-cli-options)))
    (loop while arguments
          do (setf arguments (apply-option (pop arguments) arguments options)))
    options))

(defun main (arguments)
  (let ((options (parse-arguments arguments)))
    (unless (and (cli-options-source options) (cli-options-output options))
      (error "SOURCE and -o OUTPUT are required"))
    (when (and (cli-options-compile-only options)
               (cli-options-emit-specified-p options))
      (error "-c cannot be combined with --emit"))
    (if (cli-options-compile-only options)
        (progn
          (when (cli-options-link-inputs options)
            (error "-c does not accept link inputs"))
          (when (or (cli-options-startup options)
                    (cli-options-linker-script options)
                    (cli-options-map-file options)
                    (not (equal (cli-options-entry options) "_start")))
            (error "-c does not accept freestanding link options"))
          (psl.compiler:compile-source
           (cli-options-source options) (cli-options-output options)
           :target (cli-options-target options)
           :profile (cli-options-profile options)
           :optimize (cli-options-optimize options)
           :dump-ir (cli-options-dump-ir options)))
        (psl.compiler:compile-and-link
         (cli-options-source options) (cli-options-output options)
         :target (cli-options-target options)
         :profile (cli-options-profile options)
         :optimize (cli-options-optimize options)
         :dump-ir (cli-options-dump-ir options)
         :kind (cli-options-kind options)
         :startup (cli-options-startup options)
         :linker-script (cli-options-linker-script options)
         :entry (cli-options-entry options)
         :map-file (cli-options-map-file options)
         :inputs (nreverse (cli-options-link-inputs options))))
    0))

(handler-case
    (sb-ext:exit :code (main (cdr sb-ext:*posix-argv*)))
  (error (condition)
    (format *error-output* "~A~%" condition)
    (usage *error-output*)
    (sb-ext:exit :code 1)))
