(let ((root (make-pathname :name nil :type nil :defaults *load-truename*)))
  (dolist (file '("package.lisp"
                  "common.lisp"
                  "ir/hir.lisp"
                  "ir/types.lisp"
                  "ir/ssa.lisp"
                  "binary.lisp"
                  "target.lisp"
                  "frontend/layout.lisp"
                  "frontend/reader.lisp"
                  "frontend/runtime.lisp"
                  "frontend/closures.lisp"
                  "frontend/strings.lisp"
                  "frontend/multiple-values.lisp"
                  "frontend/analyze.lisp"
                  "frontend/effects.lisp"
                  "ir/lower.lisp"
                  "ir/verify/common.lisp"
                  "ir/verify/hir.lisp"
                  "ir/verify/ssa.lisp"
                  "ir/verify/lir.lisp"
                  "ir/optimize.lisp"
                  "ir/dump.lisp"
                  "backend/x86-64.lisp"
                  "object/elf64.lisp"
                  "ffi/toolchain.lisp"
                  "driver.lisp"))
    (load (merge-pathnames file root))))
